### ISSUE TITLE
Getting pixel color of GPUImageView on touch

### ISSUE THREAD

**Issue by fivesand** [BradLarson/GPUImage#1061]
Hi,

I would like to get the pixel color of the pixel that I touch.
I am using GPUImageView to store the Live preview of my camera
However, it seems the pickedColor always returns the pixel of the color behind the GPUImageView. How can I get the pixel color of the GPUImageView?
Please help

Here is my code that I use for this:
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event {
  UITouch *touch = [[event allTouches] anyObject];
  CGPoint loc = [touch locationInView:self.view];
  self.pickedColor = [self colorOfPoint:loc];
  }
- (UIColor *) colorOfPoint:(CGPoint)point
  {
  unsigned char pixel[4] = {0};
  CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
  CGContextRef context = CGBitmapContextCreate(pixel, 1, 1, 8, 4, colorSpace, kCGImageAlphaPremultipliedLast);
  
  CGContextTranslateCTM(context, -point.x, -point.y);
  
  [self.view.layer renderInContext:context];
  
  CGContextRelease(context);
  CGColorSpaceRelease(colorSpace);
  [(GPUImageChromaKeyBlendFilter *)filter setColorToReplaceRed:(pixel[0]/255.0) green:(pixel[1]/255.0) blue:(pixel[2]/255.0)];
  [(GPUImageChromaKeyBlendFilter *)filter setThresholdSensitivity:0.5];
  UIColor *color = [UIColor colorWithRed:pixel[0]/255.0 green:pixel[1]/255.0 blue:pixel[2]/255.0 alpha:pixel[3]/255.0];
  
  return color;

}

**Comment by Maulik699** [comment]
@BradLarson How can I get color of touch on live camera?
can you please help me?
