### ISSUE TITLE
Photo Capturing/Processing takes a lot of time

### ISSUE THREAD

**Issue by kinjaldua** [BradLarson/GPUImage#1063]
Hey!

Please help me with this issue I am facing.

When I capture an image(with or without a filter), it takes too long to capture and process it. Following is the code. Check out "takePhoto" method. Any help is much appreciated. Thanks!!! 
- (void)viewDidLoad
  {
  [super viewDidLoad];
  // Do any additional setup after loading the view from its nib.
  self.capturedImage = nil;
     [self loadview];
  }

-(void)viewDidUnload
{
    if (stillCamera) {
        [stillCamera stopCameraCapture];
        [stillCamera pauseCameraCapture];
        [stillCamera removeAllTargets];
        [stillCamera release];
        stillCamera = nil;
    }
    if (filter) {
        [filter release];
        filter = nil;
    }
}
- (void)didReceiveMemoryWarning
  {
  [super didReceiveMemoryWarning];
  // Dispose of any resources that can be recreated.
  }

-(void)loadview
{
    stillCamera = [[GPUImageStillCamera alloc] init];
    stillCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
    filter = [[GPUImageBrightnessFilter alloc] init];
    [stillCamera addTarget:filter];
    filterView = (GPUImageView *)self.view;

```
[filter addTarget:filterView];
[stillCamera startCameraCapture];
```

}

// this is the method used to capture an image
- (IBAction)takePhoto:(id)sender
  {
  [btn_CapturePhoto setUserInteractionEnabled:NO];
  [btn_back setUserInteractionEnabled:NO];
  [btn_grayscale setUserInteractionEnabled:NO];
  [btn_Haze setUserInteractionEnabled:NO];
  [btn_noFilter setUserInteractionEnabled:NO];
  [btn_Sepia setUserInteractionEnabled:NO];
  [btn_switch setUserInteractionEnabled:NO];
  [btn_Effects setUserInteractionEnabled:NO];
  
  ```
  [stillCamera capturePhotoAsPNGProcessedUpToFilter:filter withCompletionHandler:^(NSData *processedPNG, NSError *error)
   {
       self.capturedImage =  [UIImage imageWithData:processedPNG];
   }];
  
   [stillCamera stopCameraCapture];
   btn_Accept.hidden = NO;
  ```
  
  }
- (void)image:(UIImage *)image didFinishSavingWithError:(NSError *)errorInSaving contextInfo:(void *)contextInfo
  {
  NSLog(@"saved");

}
- (IBAction)setupFilter:(id)sender
  {
  UIButton _btn = (UIButton_)sender;
  if (btn.tag == 1) {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImageSepiaFilter alloc] init];
      [stillCamera addTarget:filter];
  
  }
  else if (btn.tag == 2)
  {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImageGrayscaleFilter alloc] init];
      [stillCamera addTarget:filter];
  
  }
  else if (btn.tag==3)
  {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImageHazeFilter alloc] init];
      [stillCamera addTarget:filter];
  
  }
  else if (btn.tag==4)
  {
  
  ```
  [stillCamera removeAllTargets];
  if (filter) {
      [filter release];
      filter = nil;
  }
  filter = [[GPUImageBrightnessFilter alloc] init];
  [stillCamera addTarget:filter];
  ```
  
  }
  
  else if (btn.tag==5)
  {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter =[[ GPUImageSketchFilter alloc] init];
  
  ```
  [stillCamera addTarget:filter];
  ```
  
  }
  
  else if (btn.tag==6)
  {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImagePixellateFilter alloc] init];
  
  ```
  [stillCamera addTarget:filter];
  ```
  
  }
  
  else if (btn.tag==7)
  {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImageColorInvertFilter alloc] init];
  
  ```
  [stillCamera addTarget:filter];
  ```
  
  }
  
  else if (btn.tag==8)
  {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImageToonFilter alloc] init];
  
  ```
  [stillCamera addTarget:filter];
  ```
  
  }
  
  else if (btn.tag==9)
  {
      [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImagePinchDistortionFilter alloc] init];        
  
  ```
  [stillCamera addTarget:filter];
  ```
  
  }
  
  else
  {
     /\* [stillCamera removeAllTargets];
      if (filter) {
          [filter release];
          filter = nil;
      }
      filter = [[GPUImageBrightnessFilter alloc] init];
      [stillCamera addTarget:filter];
      */
  
     // filter =[[ GPUImageSketchFilter alloc] init];
  
  }
  
  filterView = (GPUImageView *)self.view;
  [filter addTarget:filterView];
  // lk changes here ++++++
  
  // [self DismissEffectsView];
  [stillCamera startCameraCapture];

}

**Comment by VivekGoswami** [comment]
Hey @BradLarson  any solution for processing time decrease in Swift for just simple filter,  It takes almost same time of video duration. i mean for 1 minute video will take 1 minute time to write.. and some time crash with memory warning. 


`func loadVideo(){        
let path = Bundle.main.path(forResource: "SampleVideo", ofType: "mp4")
        let pathURL = URL(fileURLWithPath: path!)
        
        player = AVPlayer()
        playerItem = AVPlayerItem(url: pathURL)
        player.replaceCurrentItem(with: playerItem)
        self.movieFile = GPUImageMovie(playerItem: playerItem)
        frameView.addSubview(filteredView)
        filteredView.frame = frameView.bounds
        self.movieFile.playAtActualSpeed = false
        
        
        movieFile.addTarget(saturation)
        saturation.addTarget(contrast)
        contrast.addTarget(sharpen)
        sharpen.addTarget(exposure)
        exposure.addTarget(filteredView)

        self.movieFile.startProcessing()
        player.play()


}
func applyEffect(url: URL, complete: @escaping (URL?) -> Void) -> Void {

        self.movieFile = GPUImageMovie(url: url as URL!)
        
        self.movieFile.runBenchmark = false
        self.movieFile.playAtActualSpeed = false
        
        let dirPaths = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)
        let docsDir = dirPaths[0] as String
        
        var Timestamp: String {
            return "\(NSDate().timeIntervalSince1970 * 1000)"
        }
        
        let pathToMovie = "\(docsDir)/tempMovieFile-\(Timestamp).mp4"
        
        let processedMovieURL = URL(fileURLWithPath: pathToMovie)
        
        let anAsset = AVAsset(url: url)
        
        let videoAssetTrack = anAsset.tracks(withMediaType: AVMediaTypeVideo)[0]
        var naturalSize = CGSize()
        
        print(naturalSize)
        naturalSize = videoAssetTrack.naturalSize
        
        
        self.movieWriter = GPUImageMovieWriter(movieURL: processedMovieURL, size: naturalSize)

        let exposure2 = GPUImageExposureFilter()
        exposure2.exposure = CGFloat(exposureValue)
        let saturation2 = GPUImageSaturationFilter()
        saturation2.saturation = CGFloat(saturationValue)
        let contrast2 = GPUImageContrastFilter()
        contrast2.contrast = CGFloat(contrastValue)
        let sharpen2 = GPUImageSharpenFilter()
        sharpen2.sharpness = CGFloat(sharpenValue)

        
        contrast2.addTarget(self.movieWriter)
        saturation2.addTarget(self.movieWriter)
        sharpen2.addTarget(self.movieWriter)
        exposure2.addTarget(self.movieWriter)

        
        self.movieFile.addTarget(exposure2)
        self.movieFile.addTarget(sharpen2)
        self.movieFile.addTarget(saturation2)
        self.movieFile.addTarget(contrast2)

        self.movieWriter?.shouldPassthroughAudio = true
        self.movieFile.audioEncodingTarget = self.movieWriter
        self.movieFile.enableSynchronizedEncoding(using: self.movieWriter)
        DispatchQueue.main.async {
            
            
            self.movieWriter?.startRecording()
            self.movieFile.startProcessing()
            
            self.movieWriter?.completionBlock = { () -> Void in
            self.movieWriter?.finishRecording()
            }
        }
    }

`

**Comment by IphoneCoder** [comment]
@VivekGoswami  I have the same question，deal the video take long time when use the gpuimage，did you get the method to solve the question? thanks
