### ISSUE TITLE
GPUImageCropFilter vs forceProcessingAtSize

### ISSUE THREAD

**Issue by mattgalloway** [BradLarson/GPUImage#1151]
I'm new to GPUImage but am so impressed with what I've seen so far.

Like many folks I'm interested in capturing square images and videos and I'm curious what the pros and cons are between using a GPUImageCropFilter vs just using forceProcessingAtSize on another filter in the chain.

I know what my target resolution is and that makes it easy to to use forceProcessingAtSize (because I just get to specify the size I want).   With GPUImageCropFilter it appears I have to determine the ration of the input to my desired output. The math isn't hard but it's not clear to me how I determine the image dimensions coming out of a preceding GPUImage filter or source. I'd love an example of how to do that as well - especially if there is a strong recommendation to use GPUImageCropFilter over forceProcessingAtSize.

Thanks in advance!

-M.

**Comment by darkterrorooo** [comment]
ok, ths BradLarson for this gpuimage 
if your input solution is 1280x720, and you want a square.(720x720), which  is just center of (1280x720)

just set GPUImageCropFilter your first filter like this:

[[GPUImageCropFilter alloc]initWithCropRegion:CGRectMake(0, 0.218, 1, 0.562)];

 (0, 0.218, 1, 0.562) mean (x,y, width, height)
(1280 - 720)\* 1280 \* 2 = 0.218 
720 \* 1280 = 0.562

**Comment by 1510207073** [comment]
> ok, ths BradLarson for this gpuimage
> if your input solution is 1280x720, and you want a square.(720x720), which is just center of (1280x720)
> 
> just set GPUImageCropFilter your first filter like this:
> 
> [[GPUImageCropFilter alloc]initWithCropRegion:CGRectMake(0, 0.218, 1, 0.562)];
> 
> (0, 0.218, 1, 0.562) mean (x,y, width, height)
> (1280 - 720)* 1280 * 2 = 0.218
> 720 * 1280 = 0.562

Thanks for helping me out
