### ISSUE TITLE
Multiple Filters + Blend Filter + Multiple Filters

### ISSUE THREAD

**Issue by userich** [BradLarson/GPUImage#1185]
Hi, All!

What is the best way to solve such task:

There are two images.
To First image should be applied Saturation and Opacity filter.
To the Second image should be applied Contrast filter.
Two images with Applied filters should be blended with GPUImageScreenBlendFilter.
To the Blend filter result image should be applied Hue filter.
And result should be exported to UIimage.

**Comment by RajIET** [comment]
Hi All,
I have 4 sliders called Saturation slider, Hue slider, Brightness Slider and Contrast slider. on change of the value in any of the slider, Filter should be applied to previously applied filters.
eg. i change brightness 0.5 then applying hue to 180 degree so Hue should be applied on the modified image from brightness filter.
Please suggest me the process or give me some sample code to achieve this.
