### ISSUE TITLE
Duplicate interface definition for class 'CCGLProgram'

### ISSUE THREAD

**Issue by vkinelev** [BradLarson/GPUImage#1190]
I get compiler error:

.../Pods/Headers/GPUImage/GLProgram.h:10:1: Duplicate interface definition for class 'CCGLProgram'

I have coco2d 2.1 and GPUImage installed using cocoapods.

I guess it's possible to refactor GPUImage and rename GLProgram to something else, but maybe there's a more simple solution? I see other developers here use cocos2d and GPUImage, but nobody reports the same problem

Any thoughts?

**Comment by humza-ios** [comment]
HI , i also getting same error : see screen shot , 
<img width="1082" alt="screen shot 2016-04-25 at 5 30 50 pm" src="https://cloud.githubusercontent.com/assets/11255864/14783666/9b56a11a-0b0a-11e6-9867-f28fa1c14b0b.png">

i am using : 
pod 'GPUImage', :git => 'https://github.com/BradLarson/GPUImage.git' 
and it has same error with manual drag GPUImage libraray , but when i pod install with new Project create it seem sok , but i need to update pod in my old project . any idea how to fix this error ?
