### ISSUE TITLE
GPUImageStillCamera freezes on cameraCapture

### ISSUE THREAD

**Issue by ShadeApps** [BradLarson/GPUImage#1218]
When using the method

[stillCamera capturePhotoAsImageProcessedUpToFilter:filter withCompletionHandler:completion];

the live feed from GPUImageStillCamera freezes for a couple of seconds, then shows me the photo I've taken and then the feed continues. How do I override this behaviour so it wouldn't show the photo I've taken in the live video feed and it wouldn't freeze?

I'm seeing the same exact behaviour in the example SimplePhotoFilter app. Isn't there a way to make the UI a lot smoother?

**Comment by shashank108** [comment]
Hi,
I am facing same issue.Can someone help me out regarding the same?

Thanks.
