### ISSUE TITLE
Struggling To Sort Out Rotation For Output

### ISSUE THREAD

**Issue by OlyRice** [BradLarson/GPUImage#126]
Hi

I am trying to sort out the rotation, its seems that when the video file is created and then copied to the camera roll the rotation is completely out.  Videos that are produced in portrait mode seem to be rotated to the right, the code below is an example of the live video recording. 

@interface VideoScreen : UIViewController {

```
GPUImageVideoCamera *videoCamera;
GPUImageOutput<GPUImageInput> *filter;
GPUImageMovieWriter *movieWriter;

int recordingOn;

NSURL *moviePath;
```

}

The following is the part of the code that is run in the .m file.

-(void)startCamera {

```
videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionBack];

videoCamera.outputImageOrientation = [[UIDevice currentDevice] orientation];

[videoCamera addTarget:videoWindow];

 //videoWindow.fillMode = kGPUImageFillModeStretch;


NSString *pathToMovie = [NSHomeDirectory() stringByAppendingPathComponent:@"Documents/Movie.m4v"];
unlink([pathToMovie UTF8String]); // If a file already exists, AVAssetWriter won't let you record new frames, so delete the old movie
self.moviePath = [NSURL fileURLWithPath:pathToMovie];


movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:self.moviePath size:CGSizeMake(480.0, 640.0)];

[videoCamera addTarget:movieWriter];
[videoCamera startCameraCapture];

videoCamera.audioEncodingTarget = movieWriter;
[movieWriter startRecording];
```

}

Am I missing something? I know there used to be a rotation filter but I think that was taken out. 

I have a UIView the height and width of the IPhone, my goal would be to mimic the display and output of the in-built camera.

Thanks

Oliver

**Comment by tugberkgunver** [comment]
Hi please help me. UIInterfaceOrientationLandscapeRight my video but save and output is always Vertical.

//
//  CameraViewController.m
//  AkcarayGreenScreen
//
//  Created by Burçin Azaklı on 02/03/15.
//  Copyright (c) 2015 Artechin Production. All rights reserved.
//

#import "Video.h"
#import "VideoPlay.h"
#import <AssetsLibrary/ALAssetsLibrary.h>

@interface Video ()

@end

@implementation Video
- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
  {
  self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
  if (self) {
  }
  return self;
  }
- (id)initWithImagePath:(NSString *)imagePath
  {
  if ((self = [super init])) {
  
  ```
  self.imagePath = imagePath;
  ```
  
  }
  
  return self;
  }
- (void)didReceiveMemoryWarning
  {
  [super didReceiveMemoryWarning];
  }
- (IBAction)goBackToPreviousScreen:(UIButton *)sender
  {
  [self.navigationController popViewControllerAnimated:YES];
  }

#pragma mark - View lifecycle
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  //videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionBack];
  //    videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionFront];
  //    videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset1280x720 cameraPosition:AVCaptureDevicePositionBack];
  
  GPUImagePicture *inputImage = [[GPUImagePicture alloc] initWithImage:[UIImage imageNamed:self.imagePath]];
  
  ```
  videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset1920x1080 cameraPosition:AVCaptureDevicePositionBack];
  ```
  
  videoCamera.outputImageOrientation = UIInterfaceOrientationLandscapeRight;
  
  videoCamera.horizontallyMirrorFrontFacingCamera = NO;
  videoCamera.horizontallyMirrorRearFacingCamera = NO;
  
  filter = [[GPUImageChromaKeyBlendFilter alloc] init];
  [(GPUImageChromaKeyBlendFilter *)filter setColorToReplaceRed:0.0 green:1.0 blue:0.0];
  
  //    filter = [[GPUImageTiltShiftFilter alloc] init];
  //    [(GPUImageTiltShiftFilter *)filter setTopFocusLevel:0.65];
  //    [(GPUImageTiltShiftFilter *)filter setBottomFocusLevel:0.85];
  //    [(GPUImageTiltShiftFilter *)filter setBlurSize:1.5];
  //    [(GPUImageTiltShiftFilter *)filter setFocusFallOffRate:0.2];
  
  //    filter = [[GPUImageSketchFilter alloc] init];
  //    filter = [[GPUImageColorInvertFilter alloc] init];
  //    filter = [[GPUImageSmoothToonFilter alloc] init];
  //    GPUImageRotationFilter *rotationFilter = [[GPUImageRotationFilter alloc] initWithRotation:kGPUImageRotateRightFlipVertical];
  
  [videoCamera addTarget:filter];
  filterView = (GPUImageView *)self.view;
  
  self.sourcePicture = inputImage;
  [self.sourcePicture processImage];
  [self.sourcePicture addTarget:filter];
  
  [filter addTarget:filterView];
  
  ///////// GPUImageView *filterView = (GPUImageView *)self.view;
  //    filterView.fillMode = kGPUImageFillModeStretch;
  //    filterView.fillMode = kGPUImageFillModePreserveAspectRatioAndFill;
  
  // Record a movie for 10 s and store it in /Documents, visible via iTunes file sharing
  NSString _prefixString = @"HisarHatirasi";
  NSDate *time = [NSDate date];
  NSDateFormatter_ df = [NSDateFormatter new];
  [df setDateFormat:@"ddMMyyyyhhmmss"];
  NSString *timeString = [df stringFromDate:time];
  timeString = [timeString stringByReplacingOccurrencesOfString:@":" withString:@""];
  NSString *filename = [NSString stringWithFormat:@"Documents/%@%@.m4v", prefixString, timeString];
  
  NSString *pathToMovie = [NSHomeDirectory() stringByAppendingPathComponent:filename];
  unlink([pathToMovie UTF8String]); // If a file already exists, AVAssetWriter won't let you record new frames, so delete the old movie
  NSURL *movieURL = [NSURL fileURLWithPath:pathToMovie];
  movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(1080.0, 1920.0)];
  movieWriter.encodingLiveVideo = YES;
  //    movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(640.0, 480.0)];
  //    movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(720.0, 1280.0)];
  //    movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(1080.0, 1920.0)];
  [filter addTarget:movieWriter];
  [filter addTarget:filterView];
  
  [videoCamera startCameraCapture];
  
  // set portrait orientation
  
  double delayToStartRecording = 5.0;
  
  // UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Video Başlangıç" message:@"5 saniye içinde video çekimi başlayacaktır.Videonuz kaydedildi uyarısına kadar çekime devam ediniz."
                                                // delegate:self cancelButtonTitle:@"Tamam" otherButtonTitles:nil];
  //[alert show];
  dispatch_time_t startTime = dispatch_time(DISPATCH_TIME_NOW, delayToStartRecording \* NSEC_PER_SEC);
  dispatch_after(startTime, dispatch_get_main_queue(), ^(void){
      NSLog(@"Start recording");
      videoCamera.audioEncodingTarget = movieWriter;
      [movieWriter startRecording];
  
  ```
  //        NSError *error = nil;
  //        if (![videoCamera.inputCamera lockForConfiguration:&error])
  //        {
  //            NSLog(@"Error locking for configuration: %@", error);
  //        }
  //        [videoCamera.inputCamera setTorchMode:AVCaptureTorchModeOn];
  //        [videoCamera.inputCamera unlockForConfiguration];
  
  double delayInSeconds = 10.0;
  dispatch_time_t stopTime = dispatch_time(DISPATCH_TIME_NOW, delayInSeconds * NSEC_PER_SEC);
  dispatch_after(stopTime, dispatch_get_main_queue(), ^(void){
  
      [filter removeTarget:movieWriter];
      videoCamera.audioEncodingTarget = nil;
      [movieWriter finishRecording];
      NSLog(@"Movie completed");
  
  
  
  
  
      ALAssetsLibrary *library = [[ALAssetsLibrary alloc] init];
      if ([library videoAtPathIsCompatibleWithSavedPhotosAlbum:movieURL])
      {
          [library writeVideoAtPathToSavedPhotosAlbum:movieURL completionBlock:^(NSURL *assetURL, NSError *error)
  
           {
               dispatch_async(dispatch_get_main_queue(), ^{
  
                   if (error) {
                       UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Error" message:@"Video Saving Failed"
                                                                      delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil];
                       [alert show];
                   } else {
                       UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Video Kaydedildi." message:@"Videonuz kaydedilmiştir."
                                                                      delegate:self cancelButtonTitle:@"Tamam" otherButtonTitles:nil];
                       [alert show];
  
                   }
                   VideoPlay *resultViewController = [[VideoPlay alloc] initWithMovieURL:movieURL ];
                   [self.navigationController pushViewController:resultViewController animated:YES];
               });
           }];
      }
  
  
  
  
  
      //            [videoCamera.inputCamera lockForConfiguration:nil];
      //            [videoCamera.inputCamera setTorchMode:AVCaptureTorchModeOff];
      //            [videoCamera.inputCamera unlockForConfiguration];
  });
  ```
  
  });
  }
- (void)viewDidUnload
  {
  [super viewDidUnload];
  }
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation
  {
  // Map UIDeviceOrientation to UIInterfaceOrientation.
  UIInterfaceOrientation orient = UIInterfaceOrientationPortrait;
  switch ([[UIDevice currentDevice] orientation])
  {
      case UIDeviceOrientationLandscapeLeft:
          orient = UIInterfaceOrientationLandscapeLeft;
          break;
  
  ```
  case UIDeviceOrientationLandscapeRight:
      orient = UIInterfaceOrientationLandscapeRight;
      break;
  
  case UIDeviceOrientationPortrait:
      orient = UIInterfaceOrientationPortrait;
      break;
  
  case UIDeviceOrientationPortraitUpsideDown:
      orient = UIInterfaceOrientationPortraitUpsideDown;
      break;
  
  case UIDeviceOrientationFaceUp:
  case UIDeviceOrientationFaceDown:
  case UIDeviceOrientationUnknown:
      // When in doubt, stay the same.
      orient = fromInterfaceOrientation; // sen burayı ne yaptım demiştin bana :D
      break;
  ```
  
  }
  videoCamera.outputImageOrientation = orient;

}
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
  {
  return YES; // Support all orientations.
  }
- (IBAction)updateSliderValue:(id)sender
  {
  [(GPUImageSepiaFilter *)filter setIntensity:[(UISlider *)sender value]];
  }

@end
