### ISSUE TITLE
Gradient Map Filter

### ISSUE THREAD

**Issue by hengw** [BradLarson/GPUImage#1275]
I am trying to implement a gradient map filter as according to:
http://www.photoshopessentials.com/photo-effects/gradient-map/

The closest filter that I found is by using the falseColorFilter. 

```
GPUImageFalseColorFilter *falseColorFilter = [[GPUImageFalseColorFilter alloc] init];
falseColorFilter.firstColor = (GPUVector4){0.0f, 0.0f, 0.0f, 1.0f}; //black
falseColorFilter.secondColor = (GPUVector4){1.0f, 1.0f, 1.0f, 1.0f}; //white

GPUImageMultiplyBlendFilter* blendFilter = [[GPUImageMultiplyBlendFilter alloc] init];

[self.picture addTarget:blendFilter];
[self.picture addTarget:falseColorFilter];
[falseColorFilter addTarget:blendFilter];

[levelsFilter addTarget:self.preview];
[self.picture processImage];
```

This works ok. However, the false color filter only allows selection of 2 colors at the extreme. Can I set the midtone to black as well? Or in a more general sense, can I add more colors to the midtones?

Thanks.

**Comment by evelynloo** [comment]
I am trying to implement a gradient map filter, radial gradient filter and a filter group(GPUImageToneCurveFilter, vignette filter) to my image. I try to use this code 

GPUImageFalseColorFilter *falseColorFilter = [[GPUImageFalseColorFilter alloc] init];
falseColorFilter.firstColor = (GPUVector4){0.0f, 0.0f, 0.0f, 1.0f}; //black
falseColorFilter.secondColor = (GPUVector4){1.0f, 1.0f, 1.0f, 1.0f}; //white

GPUImageMultiplyBlendFilter* blendFilter = [[GPUImageMultiplyBlendFilter alloc] init];

[self.picture addTarget:blendFilter];
[self.picture addTarget:falseColorFilter];
[falseColorFilter addTarget:blendFilter];

[levelsFilter addTarget:self.preview];
[self.picture processImage];

and filter group filter to apply on my image, but seems that the gradient doesn't take effect.

Can any one tell me how to use the GPUImageFalseColorFilter and GPUImageMultiplyBlendFilter with filter group work together? Thank you.
