### ISSUE TITLE
Code Help: Drawing on frames.

### ISSUE THREAD

**Issue by flagman** [BradLarson/GPUImage#1289]
I want to draw fps counter on frames thus, it will appear not only in GPUImageView, but also in saved movie. 
Honestly, I will be very happy if I could add at least red triangle to resulting video :)

I've tinkered with GPUImageCrosshairGenerator class, but could not figure out how to work with it. Here is my attempt:

```
- (void)showCrossHairs:(id)sender
{
        GLfloat arr[] = {0.5f, 0.5f};
        [_generator renderCrosshairsFromArray:arr count:1 frameTime:kCMTimeZero];
}
```

I call this method using NSTimer, and it seems that there is two separate frames swapping very fast.
Then I looked at GPUImageMask filter, but it seems that it should have two inputs. Should I write own generator and add it as second input?

I don't want you to write code for me, but could you at least point direction, what classes to use or subclass? 

Cheers

**Comment by taojinliang** [comment]
how to use Core Graphics to draw the UI controls into an OpenGL ES texture？on Mac,how to repleace renderInContext method？
