### ISSUE TITLE
vibrance effect 

### ISSUE THREAD

**Issue by savana10** [BradLarson/GPUImage#1322]
How to get vibrance effect with the help of  GPUImage Framework

**Comment by shi-yan** [comment]
a vibrance shader:

http://forum.doom9.org/showthread.php?t=157634&page=18

http://forums.guru3d.com/showpost.php?p=4404811&postcount=830

https://github.com/terrasque/sweetfxui/blob/master/SweetFX/SweetFX/Shaders/Vibrance.h

**Comment by brandonscript** [comment]
Just sayin' https://github.com/BradLarson/GPUImage/blob/master/framework/Source/GPUImageVibranceFilter.h

😉

**Comment by BradLarson** [comment]
As pointed out above, I forgot that this had been merged into the framework a while ago.

**Comment by ChathuriSenanayake** [comment]
I get a "Use of unresolved identifier" when trying to add the GPUImageVibranceFilter... I have aded GPUImage Library (as per discussed) into my swift project. 

So far tried "GPUImageWhiteBalanceFilter", "GPUImageExposureFilter" and "GPUImageHighlightShadowFilter" which works fine. 

Although the GPUImageVibranceFilter.h file is in the framework/Source folder, its not their in my project folder, after dragging the GPUImage.xcodeproj into my project.
  
Any ideas? 

Thanks and excited to use this library!!
