### ISSUE TITLE
GPUImageTransformFilter into GPUImageChromaKeyBlendFilter black when transformed 2d partially out of frame

### ISSUE THREAD

**Issue by aaronpeterson** [BradLarson/GPUImage#1341]
I modified the transform of a chroma keyed input by simply offsetting it like so:

``` Objective-c
[self.chromaKeyTransformFilter setAffineTransform:CGAffineTransformMakeTranslation(0.0, 0.5)];
```

In this example I expected the top half of the background input source to be visible but instead it's rendered black.  I'm assuming this is because those pixels, rather than  being colorToReplace, simply don't exist.  It seems that where there is no input pixels on the chroma key layer (I think this inputImageTexture) the result is a black pixel.

I want to add an option to render these pixels alpha 0 but I want to make sure I'm on the right track in just modifying the GPUImageChromaKeyBlendFilter shader and that I'm not encountering a more significant problem.

**Comment by KetulThakor** [comment]
> My apologies. That is all it took. Thanks again for all your help!

@aaronpeterson  can you please provide chromaKeyTransformFilter changes you done? i am stuck in same situation. i think your solution may help me with it for apply chroma and transformation together.
