### ISSUE TITLE
GPUImageCropFilter with a resize.

### ISSUE THREAD

**Issue by beeradmoore** [BradLarson/GPUImage#1350]
Hey, 
Having this issue at the moment, I am wanting to crop an image to a square and then resize it down.
I am using a Xamarin.iOS binding project (still uses the GPUImage .a library so results should be the same in Obj-C I would assume).

``` csharp
// Make my input image.
GPUImagePicture inputImageSource = new GPUImagePicture(image, true);
inputImageSource.ForceProcessingAtSize(new SizeF(620, 620));

// Create the crop filter
GPUImageCropFilter cropFilter = new GPUImageCropFilter();
cropFilter.ForceProcessingAtSize(new SizeF(620, 620));

//GPUImageSepiaFilter sepiaFilter = new GPUImageSepiaFilter();

// Get the size that we want to crop by, is the 'width' of the image, centered.
if (image.Size.Width > image.Size.Height)
{
    float cropSize = image.Size.Height / image.Size.Width;
    float cropStart = (1f - cropSize) * 0.5f;
    cropFilter.CropRegion = new RectangleF(cropStart, 0, cropSize, 1);
}
else
{
    float cropSize = image.Size.Width / image.Size.Height;
    float cropStart = (1f - cropSize) * 0.5f;
    cropFilter.CropRegion = new RectangleF(0, cropStart, 1, cropSize);
}

inputImageSource.AddTarget(cropFilter);
//cropFilter.AddTarget(sepiaFilter);

inputImageSource.ProcessImage();

_mainImageView.Image = cropFilter.ImageFromCurrentlyProcessedOutputWithOrientation(UIImageOrientation.Right);
//_mainImageView.Image = sepiaFilter.ImageFromCurrentlyProcessedOutputWithOrientation(UIImageOrientation.Right);
```

So from an image directly from a camera it will be 1080x1920. The cropRect will then be the area of a square, centered in the image.

The output image is now 1080x1080, but I had told it to force the image size down to 620x620.

What is odd with this is though, if I use the sepiaFilter after the cropFilter I will get the output image to be 620x620.

I have tried to do a GPUImageTransformFilter instead of the sepia filter as just like a passover and transform it by an Identity matrix, but it returns the same size as the original.

Is there something I am missing here or forgetting to do?

**Comment by develop24** [comment]
Hi,
I working in ios apps.I have created the AVCaptureSession for taking photos and videos, now I like to add the filters to my live image using GPUImage framework, the problem I faced is my camera and GPUImageStill camera gets append else If i'm not using the GPUImagestillcamera the filter is not working.I'm new bee to this framework.please help me.
