### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException NSInternalInconsistencyException Passed image must not be empty - it should be at least 1px tall and wide

### ISSUE THREAD

**Issue by kissfro** [BradLarson/GPUImage#1362]
In some of my crash logs to Crashlytics I get:

Fatal Exception: NSInternalInconsistencyException NSInternalInconsistencyException
Passed image must not be empty - it should be at least 1px tall and wide

and it happens on this line:

-[GPUImagePicture initWithImage:smoothlyScaleOutput:] 

This is after a user either selects a photo from the photo library or take a picture with the camera and I try to convert it to a GPUImagePicture. Are people really trying to pass an image that's 1 px tall and wide (which is hard for me to believe) or is it possible something else is causing this?

**Comment by a2zZuhaib** [comment]
I am applying filter inside the VideoCompstion Request block on every frame..

the line has failed to Assert: sepiaFilter.image(byFilteringImage: image)

Below is code.: 
let vidComp = AVMutableVideoComposition(asset: playerItem!.asset,
                                                applyingCIFiltersWithHandler: {
                                                    request in
                                                    var image = UIImage(ciImage: request.sourceImage.clampingToExtent())
                                                    // Modify Image (image) Here...
                                                    let sepiaFilter = GPUImageSepiaFilter()
                                                    let image_filtered = sepiaFilter.image(byFilteringImage: image).ciImage
                                                    
                                                    request.finish(with: image_filtered!, context:context)
