### ISSUE TITLE
Steps to add libGPUImage.a is incorrect or may be outdated

### ISSUE THREAD

**Issue by rajaraodv** [BradLarson/GPUImage#1420]
Disclaimer: Am a newbie.  I spent a lot of time trying to figure out "drag libGPUImage.a from framework's product folder".. thingy to work. But there is no such file!! It's actually in a folder called "build". Also there are 3 different versions. So the steps should be.. 
Select <workspace> 
Targets (select target w/ your project name) 
Select Build Settings 
 Open section "Link Binary with Libraries" 

go to GPUImage xcode project > "build" folder and then select Release-iphonesimulator or debug-iphonesimulator" file and drag it to "Link Binary with Libraries"

**Comment by Ledrec** [comment]
BradLarson im having  a problem... it seems like i cannot add your framework to my Xcode project, when i add it to target dependencies and i link binary with libraries... and add the correct search path i still find the cannot find GPUImage.h...
