### ISSUE TITLE
App crashed with message "terminated due to memory error"

### ISSUE THREAD

**Issue by annathomasQB** [BradLarson/GPUImage#1460]
Hi,

i am using GPUImageStillCamera to capture an image, with GPUImageGammaFilter as filter. After taking a photo, if I try taking a photo again and again, in the same view, the app crashes with the above message. I see in the log that I'm receiving memory warning.

Here is my code where i initialize the stillCamera

```
if (!stillCamera) {
        stillCamera = [[GPUImageStillCamera alloc] initWithSessionPreset:AVCaptureSessionPresetInputPriority cameraPosition:AVCaptureDevicePositionBack];
        stillCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
        [stillCamera setCaptureSessionPreset:AVCaptureSessionPresetInputPriority];
    }
    runOnMainQueueWithoutDeadlocking(^{
        filter = [[GPUImageGammaFilter alloc] init];
        [filter addTarget:self.imageView];
        if ([stillCamera.targets containsObject:filter]) {
            [stillCamera removeTarget:filter];
        }
        [stillCamera addTarget:filter];
        [stillCamera startCameraCapture];
    });
```

To take a photo again, i have a button on my view which takes me to photo capturing view. (in essence, the button calls the above method again)

Can you please help me determine what might be the issue?.. 
I am getting the crash definitely - on the thrid photo click.

Let me also add that after taking the photo, i am creating an array of filtered images using GPUImageView. 
Don't know which of this code is contributing to this crash.. :-/ 

Please help.

**Comment by madhurigondi** [comment]
> Thanks for the input Brad.. i've worked on it and now its working better :) Thanks

I am facing the same issue. can you explain me how you resolved this issue.

**Comment by annathomasQB** [comment]
Hi @madhurigondi : its been a long time and I'll try digging up my code for this particular project - but if I remember it correctly, I think I took Brad's suggestion of filtering reduced images - meaning i first reduced the size of the image that needs to be filtered, so the filtered image size was also less compared to my previous attempts.

**Comment by yatindma** [comment]
what does resizing means reduce 

does it mean
func resizeImage(image: UIImage, targetSize: CGSize) -> UIImage {
        let size = image.size
        
        let widthRatio  = targetSize.width  / size.width
        let heightRatio = targetSize.height / size.height
        
        // Figure out what our orientation is, and use that to form the rectangle
        var newSize: CGSize
        if(widthRatio > heightRatio) {
            newSize = CGSize(width: size.width * heightRatio, height: size.height * heightRatio)
        } else {
            newSize = CGSize(width: size.width * widthRatio,  height: size.height * widthRatio)
        }
        
        // This is the rect that we've calculated out and this is what is actually used below
        let rect = CGRect(x: 0, y: 0, width: newSize.width, height: newSize.height)
        
        // Actually do the resizing to the rect using the ImageContext stuff
        UIGraphicsBeginImageContextWithOptions(newSize, false, 1.0)
        image.draw(in: rect)
        let newImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        
        return newImage!
    }

**Comment by sagarkoyani** [comment]
I am trying to add green screen effect on the video for that i am using gpuimagechromakey Filter. It is crashing after 2-3 seconds and give message from debugger 
**Message from debugger: Terminated due to memory issue.**
