### ISSUE TITLE
UIImage from CMSampleBufferRef help!

### ISSUE THREAD

**Issue by ric2z** [BradLarson/GPUImage#1468]
I'm trying to extract frame from a GPUImageVideoCamera's willOutputSampleBuffer:sampleBuffer. However, I either get a crash, or the resulting image is very distorted. 

Some background info:
- I'm running this on an iPhone 5 running iOS 7.1

This is the code I'm using for processing each frame:

``` Objective-C
- (void)processColorImageFromSampleBuffer:(CMSampleBufferRef)sampleBuffer {

    @autoreleasepool {
        CVImageBufferRef imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer);

        /*Lock the image buffer*/
        CVPixelBufferLockBaseAddress(imageBuffer,0);

        /*Get information about the image*/
        uint8_t *baseAddress = (uint8_t *)CVPixelBufferGetBaseAddress(imageBuffer);
//        size_t bytesPerRow = CVPixelBufferGetBytesPerRow(imageBuffer);
        size_t width = CVPixelBufferGetWidth(imageBuffer);
        size_t height = CVPixelBufferGetHeight(imageBuffer);

        /*Create a CGImageRef from the CVImageBufferRef*/
        CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
        CGContextRef newContext = CGBitmapContextCreate(baseAddress, width, height, 8, 4 * width, colorSpace, kCGBitmapByteOrder32Little | kCGImageAlphaPremultipliedFirst);
        CGImageRef newImage = CGBitmapContextCreateImage(newContext);

        /*We release some components*/
        CGContextRelease(newContext);
        CGColorSpaceRelease(colorSpace);

        UIImage *image = [UIImage imageWithCGImage:newImage scale:1.0 orientation:UIImageOrientationUp];

        /*We relase the CGImageRef*/
        CGImageRelease(newImage);

        if (image) {
            framesTaken++;
            [self imageCaptured: image];
        }

        /*We unlock the  image buffer*/
        CVPixelBufferUnlockBaseAddress(imageBuffer,0);
    }
}
```

Any help will be very appreciated!

**Comment by tettoffensive** [comment]
@BradLarson did you ever fix the bug with GPUImageRawDataOutput? I have a project which isn't currently using GPUImage, but I need a faster way to generate the thumbnails for videos (for an interface where users can trim videos). Might this be a good way to do something like that?

**Comment by wanderingstan** [comment]
Note for future people that find this thread: If you still want to pay the "horribly expense" cost of creating a  UIImage for each frame, this SO answer was useful to me:  
http://stackoverflow.com/questions/13201084/how-to-convert-a-kcvpixelformattype-420ypcbcr8biplanarfullrange-buffer-to-uiimag

EDIT: Changed to better answer. The older grayscale-only solution is here: http://stackoverflow.com/a/30120289/59913
