### ISSUE TITLE
ios Green Screen App

### ISSUE THREAD

**Issue by brookswood** [BradLarson/GPUImage#1489]
I have been working with the GPUImage framework. Specifically the Chromakey filter. I am trying to overlay a pre-recorded video that contains a Green Screen (Alpha Channel) on top of the live camera preview.

Once the app opens and the video is selected I am able the to see the live camera preview with the selected video. What happens next is the video with the green screen and the camera preview freeze. Below is my snip of code that I am using to accomplish this.

Should I put the camera preview and the chromakey filter in a seperate thread?

moviePlayer = [[GPUImageMovie alloc] initWithURL:[info objectForKey: UIImagePickerControllerMediaURL]]; moviePlayer.playAtActualSpeed = YES;

```
filter = [[GPUImageChromaKeyFilter alloc] init];
[(GPUImageChromaKeyFilter *)filter setColorToReplaceRed:0.0 green:1.0 blue:0.0];
[(GPUImageChromaKeyFilter *)filter setThresholdSensitivity:0.4f];

GPUImageView *filterView = (GPUImageView *)self.playerView;

videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionBack];;
videoCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
videoCamera.runBenchmark = YES;
[videoCamera startCameraCapture];
[videoCamera addTarget:filter];

[moviePlayer addTarget:filter];

GPUImageAlphaBlendFilter *blendFilter = [[GPUImageAlphaBlendFilter alloc] init];
blendFilter.mix = 1.0;
[videoCamera addTarget:blendFilter];
[filter addTarget:blendFilter];

[blendFilter addTarget:filterView];

[moviePlayer startProcessing];
```

**Comment by passion1989** [comment]
I want to remove green screen on live video 
could you please help me?

I used chromakey filter but not remove green screen
what's wrong?
