### ISSUE TITLE
Very High CPU Utilization w/ GPUImageUIElement

### ISSUE THREAD

**Issue by smitter1** [BradLarson/GPUImage#1506]
Using GPUImageUIElement to render an overlay on sports videos.  Works GREAT ... except we are seeing some very high CPU utilization (up to 50% or more), and this is causing the Frame Rate to drop over time.  The lost Frame Rate (>30FPS) renders the videos unusable.  Ack!

The issue can be replicated for the most part simply by running the Filter Showcase > UI Element example.  While using you will see the CPU hover around 40% utilization, which is more than enough to cause an iPhone 5s to become hot and consume copious amounts of battery.  See screenshot here:

https://www.evernote.com/shard/s15/sh/90908435-4cd5-468f-b36e-2fbc8d4cabe0/c22a452dbe094fa94ed62b1f2eafbbec

I haven't been able to repro the drop in Frame Rate while using just the UI Element example, but the CPU utilization seems to be the primary cause.

Does anyone have some suggestions on how to address this issue?  Modifications that might lower the CPU utilization down to a reasonable level (even sub-30 would be an improvement)?  We have tried a number of work-arounds to no effect.  Also the issue seems to get worse the longer you are using the filter (ie long videos the CPU climbs and the FPS becomes unstable).  However the memory seems pretty constant.

Thanks for any help!

**Comment by muddlegeist** [comment]
I seem to now be in the same situation that @warpling was two years ago. 

After devoting the last few days to playing with layering CIFilter and GPUImage on top of an animating SKScene in hopes of realizing a visual effect crucial to a game concept I'm playing with.  I had assumed that applying a filter to an animating view would be equivalent to processing video; but, now that I've seen the above conversation and the input of @BradLarson in a couple of other discussions, I'm thinking this isn't going to be possible - unless something has changed in the last two years that I haven't yet been turned on to.  (UIBlurEffect would be a good lead if it could be customized.)

Is there currently no means in iOS to apply filters to an animating view (or SKScene) without dropping the frame rate to almost zero and pegging the CPU?  I now understand why it"s happening with CIFilter and GPUImage.  Is there currently no working alternative?

I'm hoping for a generalized filter solution, not just blur; as I'm hoping to apply a chain of filters.

**Comment by BradLarson** [comment]
@muddlegeist - Can you have the SKScene render to a texture in the same way that a Scene Kit scene can (with SCNRenderer)? If so, that avoids the path through Core Graphics that rendering the view in a GPUImageUIElement takes. If you can render to a texture, it can all stay on the GPU and be smooth.
