### ISSUE TITLE
Getting a crash on -newCGImageFromFramebufferContents

### ISSUE THREAD

**Issue by josh-berlin** [BradLarson/GPUImage#1537]
Name: SIGSEGV

Reason: SEGV_ACCERR

GPUImage Version: 0.1.4

The GPUImageFramebuffer class might be accessing deallocated memory on this line:
[self activateFramebuffer];

I am using the GPUMonochromeFilter:
GPUImageMonochromeFilter *monochromeFilter = [GPUImageMonochromeFilter new];
monochromeFilter.color = (GPUVector4){0.5, 0.5, 0.5, 1};
UIImage *filteredImage = [self.monochromeFilter imageByFilteringImage:image];

Stack trace:
0   CoreFoundation  0x2de54afc CFRetain + 8
1   MyApp   0x0026edd3 __56-[GPUImageFramebuffer newCGImageFromFramebufferContents]_block_invoke
2   libdispatch.dylib   0x38ba4d3f _dispatch_client_callout + 23
3   libdispatch.dylib   0x38ba956f _dispatch_barrier_sync_f_slow + 231
4   MyApp   0x0027dacd runSynchronouslyOnVideoProcessingQueue
5   MyApp   0x0026ecdb -[GPUImageFramebuffer newCGImageFromFramebufferContents]
6   MyApp   0x0026a803 -[GPUImageFilter newCGImageFromCurrentlyProcessedOutput]
7   MyApp   0x0027e597 -[GPUImageOutput newCGImageByFilteringCGImage:]
8   MyApp   0x0027e6c9 -[GPUImageOutput imageByFilteringImage:]

Any ideas on how to fix this?

**Comment by AbhijeetCopper** [comment]
Did not fixed !
It happens in every part of code 
Very Frustrating

Never Use this library for Filters

**Comment by BradLarson** [comment]
@AbhijeetCopper - You could, you know, try to find the cause and fix it. I've only given you all the code for free after years of work.
