### ISSUE TITLE
Blending GPUImageMovie with filtered GPUImagePicture: framebuffer overrelease error

### ISSUE THREAD

**Issue by EastDesire** [BradLarson/GPUImage#1551]
Hi Brad and all,

I'm experiencing an issue when trying to overlay a GPUImagePicture with a GPUImageMovie.

Everything works fine until I add a filter to the GPUImagePicture, in which case I'm getting error _Tried to overrelease a framebuffer, did you forget to call -useNextFrameForImageCapture before using -imageFromCurrentFramebuffer?_

I'm struggling with this for days. Tried to disable reference counting _[[blurFilter framebufferForOutput] disableReferenceCounting]_, but no success.
_[blurFilter useNextFrameForImageCapture]_ doesn't seem to help either.
I'm not sure if this is a regular bug or if I just forgot to set some flag.

Any suggestion is much appreciated.
Thanks.

**Filters layout**

```
             GPUImageView
                   |
      GPUImageHardLightBlendFilter
       |               |        |
       |               |  GPUImageGaussianBlurFilter
       |               |        |
       |              (A)      (B)
       |               |        |
 GPUImageMovie       GPUImagePicture
```

Scenario (A) works
Scenario (B) doesn't work, fails with error: _Tried to overrelease a framebuffer ..._

**Code snippet**

``` Objective-C
myView = [[GPUImageView alloc] initWithFrame:[UIScreen mainScreen].bounds];
[self.view addSubview:myView];

NSURL *movieURL = [[NSBundle mainBundle] URLForResource:@"overlay_movie" withExtension:@"mp4"];
UIImage *backgroundImage = [UIImage imageNamed:@"background_picture.jpg"];

blendFilter = [[GPUImageHardLightBlendFilter alloc] init];
[blendFilter addTarget:myView];

blurFilter = [[GPUImageGaussianBlurFilter alloc] init];
[blurFilter setBlurRadiusInPixels:10.0];
[blurFilter addTarget:blendFilter];

backgroundPicture = [[GPUImagePicture alloc] initWithImage:backgroundImage];
//[backgroundPicture addTarget:blendFilter]; // Scenario (A) works
[backgroundPicture addTarget:blurFilter];    // Scenario (B) doesn't work

overlayMovie = [[GPUImageMovie alloc] initWithURL:movieURL];
[overlayMovie addTarget:blendFilter];

[backgroundPicture processImage];
[overlayMovie startProcessing];
```

**Error output**
2014-04-30 18:03:05.601 PictureAndMovieCompositionTest[11954:3507] **\* Assertion failure in -[GPUImageFramebuffer unlock], /Users/jan/Desktop/PictureAndMovieCompositionTest/GPUImage-master/framework/Source/GPUImageFramebuffer.m:268
2014-04-30 18:03:05.605 PictureAndMovieCompositionTest[11954:3507] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Tried to overrelease a framebuffer, did you forget to call -useNextFrameForImageCapture before using -imageFromCurrentFramebuffer?'

**Comment by puelocesar** [comment]
just reporting that odvarko solution works perfectly here, in different scenario but with similar problem

**Comment by gonghao** [comment]
the same as @puelocesar said :+1:

**Comment by ripegooseberry** [comment]
This solution works well, but I don't understand this @EastDesire 's line:
(*) this path is just to distribute the pulse, but the GPUImageNormalBlendFilter will output only GPUImagePicture

Is there something special I need to do to make GPUImageNormalBlendFilter ignore the video input? (my GPUImagePicture has transparency). Right now I get the GPUImageMovie(*) path completely obscuring the other GPUImageMovie.

my setup:
         GPUImageView
               |
 GPUImageNormalBlendFilter
       |                 |
       |    GPUImageTransformFilter (shrink to 0.5 size)
       |                 |
       |     GPUImageNormalBlendFilter
       |       |(*)                               |     
     GPUImageMovie          GPUImagePicture

I see the GPUImageMovie that went trough right-hand-side route too :(
any ideas? @gonghao @puelocesar @BradLarson ? 

![img_9881](https://cloud.githubusercontent.com/assets/4032567/13853569/2be89fa0-ec5f-11e5-890f-dc79b2af766a.jpg)

**Comment by scharli** [comment]
This approach works for me

` imageBocaMask = [UIImage imageNamed:@"mask720.png"];
    pictureBocaMask = [[GPUImagePicture alloc] initWithImage:imageBocaMask smoothlyScaleOutput:YES];

    GPUImageOpacityFilter *opacityBocaFilter = [[GPUImageOpacityFilter alloc] init];
    opacityBocaFilter.opacity = 0.0;

    GPUImageNormalBlendFilter *preMaskBocaFilter = [[GPUImageNormalBlendFilter alloc] init];

    [videoCamera addTarget:opacityBocaFilter];
    [opacityBocaFilter addTarget:preMaskBocaFilter];
    [pictureBocaMask addTarget:preMaskBocaFilter];`

Basically i mix video input with 0.0 alpha with the GPUImagePicture and i used the result for other processes

**Comment by iPhonig** [comment]
I've been experiencing this error as well, I tried adding a NormalBlend filter in however my output just became grey rather than displaying the actual video. My code is below. If anyone has any ideas that would be great. Thanks!
`
_videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset1280x720 cameraPosition:AVCaptureDevicePositionFront];
_filter = [[GPUImageFilter alloc] init];
    
    [_videoCamera addTarget:_filter];
_blendFilter = [[GPUImageAlphaBlendFilter alloc] init];
    _blendFilter.mix = 1.0;
    
    
    _animatedImageView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 100, 100)];
    [_contentView addSubview:_animatedImageView];
    [_contentView addSubview:[self watermark]];
    _uiElementInput = [[GPUImageUIElement alloc] initWithView:_contentView];
    
    [_filter addTarget:_blendFilter];
    
    [_uiElementInput addTarget:_blendFilter];
    
    [_blendFilter addTarget:_filteredVideoView];
`

**Comment by Phelthas** [comment]
EastDesire's workaround works fine for me, and I'd come up with another workaround:
```
        movieInput = GPUImageMovie(url: videoURL)
        pictureInput = GPUImagePicture(image: image0)
        pictureInput?.processImage()
        
        let transformFilter = GPUImageTransformFilter()
        transformFilter.affineTransform = CGAffineTransform(rotationAngle: 0.5)
        pictureInput?.addTarget(transformFilter)
        
        let progressFilter = GPUImageFilter()
        movieInput?.addTarget(progressFilter)
        progressFilter.frameProcessingCompletionBlock = { [unowned self] input, time in
            self.pictureInput?.processImage()
        }
        
        let blendFilter = GPUImageAlphaBlendFilter()
        blendFilter.mix = 1
        progressFilter.addTarget(blendFilter)
        transformFilter.addTarget(blendFilter)
        blendFilter.addTarget(displayView)
        
        movieInput?.startProcessing()
```
just need to call `self.pictureInput?.processImage()` in movieInput Callback, note that GPUImageMovie did not implement the frameProcessingCompletionBlock callback, so we need another GPUImageFilter here.
