### ISSUE TITLE
GPUImage get different result on real device

### ISSUE THREAD

**Issue by tiepvuvan** [BradLarson/GPUImage#1581]
I use GPUImageLookupFilter for image processing

It's seem to be okay with Simulator, but when i run my application on real device, i got different result of image

Here is two image

Simulator
http://i.stack.imgur.com/cLhMI.jpg

Real device
http://i.stack.imgur.com/s2cBC.png

Could you tell me how to fix this?

**Comment by idealhack** [comment]
Hi, I’m also encountering this problem. I’m using GPUImage `0.1.6`.

The original image:

![orgin](https://cloud.githubusercontent.com/assets/408385/5987663/f8fb1e0e-a972-11e4-90cc-8064141b65ed.JPG)

It’s OK on iPhone 5s or later devices:

![iphone6](https://cloud.githubusercontent.com/assets/408385/5987666/0f342288-a973-11e4-9502-f52b9cf324d4.JPG)

But on earlier devices it produces:

![iphone5](https://cloud.githubusercontent.com/assets/408385/5987669/1f1f826e-a973-11e4-83d7-32ad6e93d7c1.JPG)

The lookup texture I use:

![texture_lookup](https://cloud.githubusercontent.com/assets/408385/5987671/31f0ee28-a973-11e4-87c0-301669c3e626.jpg)
