### ISSUE TITLE
Creating a HSL instrument like in Lightroom 5

### ISSUE THREAD

**Issue by pegurov** [BradLarson/GPUImage#1657]
Hey, I need to be able to change Hue Saturation and Luminance for different tones, but GPUImage seems to only be able to change them for all the tones at the same time. Could you please help me with this?

![screen shot 2014-07-05 at 16 30 16](https://cloud.githubusercontent.com/assets/2697487/3486537/8561df0a-0440-11e4-9c4f-523c5011aab0.png)

**Comment by GraemeHarrison** [comment]
I know this is an old issue, but was anyone able to figure out how to make a filter like what Pavel is describing?
