### ISSUE TITLE
Motion detection in GPUImageView without GPUImageVideoCamera

### ISSUE THREAD

**Issue by thecritic** [BradLarson/GPUImage#1679]
Hey Brad, 

First of all I want to thank you so much for creating such a great library and your contribution to the StackOverflow community. 
I would appreciate it, if you could help me with a small issue I've encountered. I have tested the GPUImageMotionDetector filter in your sample project and it worked fine, but I would like to also use it on a GPUImageView instance where no video camera is involved. I have a GPUImageView, which gets fed images from a video stream, and I have added it as a target for the GPUImageMotionDetector, but the motionDetectionBlock is never called. Here is some code: 

```
motionDetectionFilter = [[GPUImageMotionDetector alloc] init];

// the videoImageView's frames change, I would love to detect this change
GPUImageView *filterView = (GPUImageView *)self.videoImageView;
[motionDetectionFilter addTarget:filterView];

//motion detection block 
motionDetectionFilter.motionDetectionBlock = 
self.motionDetectionBlock = ^(CGPoint motionCentroid, CGFloat motionIntensity, CMTime frameTime){

        if(motionCentroid.x > 0 && motionCentroid.y > 0){

            dispatch_async(dispatch_get_main_queue(), ^{

                NSLog(@"motion detected");

            });

        }
    };
```

The filter probably never gets notified by the change. What should I do to change that ? 

All the best,

**Comment by MohamedThabib** [comment]
Hey BradLarson,

I played with your Motion detection sample code. It is Awesome. I need your assistance on motion detection  sample. If more than one object is there in the preview, it only detects only one at a time. I hope you have calculate the pixel change between 2 frames and showing the rect based on pixel change (correct me if I am wrong). Is it possible that I can detect multiple objects simultaneously?  If yes could you please give me a hint on which module I should focus to make it work.

Keep Up The Great Work!
