### ISSUE TITLE
One or more attached shaders not successfully compiled

### ISSUE THREAD

**Issue by prabhattiwari0** [BradLarson/GPUImage#1696]
// i used fragment shader named RGB with following code..

precision mediump float;

varying vec2 vUv;
uniform sampler2D tInput;
uniform vec2 distance;
uniform vec2 resolution;

void main() {

vec2 value = distance *(.5 *resolution.xy - gl_FragCoord.xy)/resolution.xy;

```
vec4 c1 = texture2D( tInput, vUv - value / resolution.x );
vec4 c2 = texture2D( tInput, vUv );
vec4 c3 = texture2D( tInput, vUv + value / resolution.y );

gl_FragColor = vec4( c1.r, c2.g, c3.b, c1.a + c2.a + c3.b );
```

}

it gets crash gives error

Shader compile log:
ERROR: 0:75: Attempt to redeclare 'distance' as a variable
ERROR: 0:80: Attempt to use 'distance' as a variable
ERROR: 0:82: Use of undeclared identifier 'value'
ERROR: 0:84: Use of undeclared identifier 'value'
ERROR: 0:86: Use of undeclared identifier 'c1'
ERROR: 0:86: Use of undeclared identifier 'c3'
ERROR: 0:86: Use of undeclared identifier 'c1'
ERROR: 0:86: Use of undeclared identifier 'c3'
1. Failed to compile fragment shader
2. One or more attached shaders not successfully compiled
   3.Fragment shader compile log: (null)
3. Vertex shader compile log: (null)
4.  **\* Assertion failure in -[GPUImageFilter initWithVertexShaderFromString:fragmentShaderFromString:],
5. NSInternalInconsistencyException', reason: 'Filter shader link failed'

as i copying resources build phase in my project, not the compiling sources build phase then too it gives this error...

as i used this fragment shader code it works very fine for mirror case
varying highp vec2 textureCoordinate;
uniform sampler2D inputImageTexture;

void main()
{
    mediump vec2 p = textureCoordinate;
    if (p.y > 0.5) {
        p.y = 1.0 - p.y;
    }

```
lowp vec4 outputColor = texture2D (inputImageTexture, p);
gl_FragColor = outputColor;
```

}

when i use variying it gives constant white color... y so happening .

**Comment by kadawkalet** [comment]
I am running into a similar issue.

This is my entire code in my java project but it's not compiled with errors:

'defaultShader.glsl'

One or more attached shaders not successfully compiled

import static org.lwjgl.opengl.GL20.*;

public class LevelEditorScene extends Scene {

    private String vertexShaderSrc = "#version 120 core\n" +
            "\n" +
            "layout (location=0) in vec3 aPos;\n" +
            "layout (location=1) in vec4 aColor;\n" +
            "\n" +
            "out vec4 fColor;\n" +
            "\n" +
            "void main() {\n" +
            "    fColor = aColor;\n" +
            "    gl_Position = vec4(aPos, 1.0);\n" +
            "}";

    private String fragmentShaderSrc = "#version 120 core\n" +
            "\n" +
            "in vec4 fColor;\n" +
            "\n" +
            "out vec4 color;\n" +
            "\n" +
            "void main() {\n" +
            "    color = fColor;\n" +
            "}";

    private int vertexID, fragmentID, shaderProgram;

    public LevelEditorScene() {

    }

    @Override
    public void init() {
        // First load and compile the vertex shader
        vertexID = glCreateShader(GL_VERTEX_SHADER);

        // Pass the shader source to the GPU
        glShaderSource(vertexID, vertexShaderSrc);
        glCompileShader(vertexID);

        // Check for errors in compilation
        int success = glGetShaderi(vertexID, GL_COMPILE_STATUS);
        if (success == GL_FALSE) {
            int len = glGetShaderi(vertexID, GL_COMPILE_STATUS);
            System.out.println("ERROR: 'defaultShader.glsl'\n\tVertex Shader compilation failed.");
            System.out.println(glGetShaderInfoLog(vertexID, len));
            assert false: "";
        }

        // First load and compile the vertex shader
        fragmentID = glCreateShader(GL_FRAGMENT_SHADER);

        // Pass the shader source to the GPU
        glShaderSource(fragmentID, fragmentShaderSrc);
        glCompileShader(fragmentID);

        // Check for errors in compilation
        success = glGetShaderi(fragmentID, GL_COMPILE_STATUS);
        if (success == GL_FALSE) {
            int len = glGetShaderi(fragmentID, GL_COMPILE_STATUS);
            System.out.println("ERROR: 'defaultShader.glsl'\n\tFragment Shader compilation failed.");
            System.out.println(glGetShaderInfoLog(fragmentID, len));
            assert false: "";
        }

        // Link shader and check for errors
        shaderProgram = glCreateProgram();
        glAttachShader(shaderProgram, vertexID);
        glAttachShader(shaderProgram, fragmentID);
        glLinkProgram(shaderProgram);

        // Check for linking errors
        success = glGetProgrami(shaderProgram, GL_LINK_STATUS);
        if (success == GL_FALSE) {
            int len = glGetProgrami(shaderProgram, GL_INFO_LOG_LENGTH);
            System.out.println("ERROR: 'defaultShader.glsl'\n\tLinking Shader compilation failed.");
            System.out.println(glGetProgramInfoLog(shaderProgram, len));
            assert false: "";
        }

    }

    @Override
    public void update(float dt) {

    }
}

this is the code from my default.glsl file:

#type vertex
#version 120 core

layout (location=0) in vec3 aPos;
layout (location=1) in vec4 aColor;

out vec4 fColor;

void main() {
    fColor = aColor;
    gl_Position = vec4(aPos, 1.0);
}

#type fragment
#version 120 core

in vec4 fColor;

out vec4 color;

void main() {
    color = fColor;
}

My IDE is intellij, running on M1 Mac

**Comment by FreedomKing** [comment]
您好，您的邮件我已经收到，我会尽快阅读，谢谢你的来信。
