### ISSUE TITLE
Still getting Library not loaded in xcode 6b5

### ISSUE THREAD

**Issue by mmroden** [BradLarson/GPUImage#1720]
Hi Brad,

I'm getting the following error:

```
dyld: Library not loaded: @rpath/GPUImage.framework/GPUImage
 Referenced from: /private/var/mobile/Containers/Bundle/Application/<app stuff>
Reason: image not found
```

I've followed all the instructions in your guide; that is, I've added the GPUImage.framework to both the Target Dependencies and the Link Binary with Libraries sections, as well as adding a Copy Files section to copy the GPUImage framework.  I've tried:
1. Deleting the project and reloading from git, in case there was some project pollution.  I did this for both GPUImage and my project.
2. Trying to match code signing, in case that's an issue
3. Tried to put the file into 'shared frameworks' instead of frameworks
4. Moving the deployment target for my project to 8.0
5. Moving the deployment target for both my project and GPUImage to 8.0
6. Changing everything to point to libGPUImage.a instead of GPUImageFramework
7. Having both libGPUImage and GPUImageFramework included through all three steps
8. Adding a bunch of static paths based on the error messages to the copy message.

I've been screwing with this all day.  Any thoughts on what else I could try here?

**Comment by williamhqs** [comment]
@mmroden Can you point how to make it? Thanks!

**Comment by ParasJoshiMulti** [comment]
@mmroden Thank you mate. The Embed Libraries solution is working for me. Thanx again :).

**Comment by harjottrantor** [comment]
@mmroden Thanks. The Embed Libraries solution is working for me.
