### ISSUE TITLE
GPUImage won't compile for iOS 7 when using Swift

### ISSUE THREAD

**Issue by dennda** [BradLarson/GPUImage#1766]
Hi Brad –

Since we can't use .frameworks on iOS 7 anymore as of the Xcode 6 GM, I tried creating a new Swift project and including GPUImage statically. There's two ways one can go about that:
- Using the build.sh script to create a static library distribution, including the static library .a file (and linking against it) and the headers in one's project, or
- Including the project from source, setting the static library as a target dependency, linking against it.

(In either case, you have to also set up a bridging header that imports the GPUImage.h header.)

I tried it both ways (and am  [attaching a sample project](http://the-space-station.com/~dennda/tmp/GPUImageSwift7.zip) for the first case, since that's probably what people would rather do). Neither way works, failing with different errors.

The first (compiled with the iOS 8 GM SDK) fails with

```
No such module 'GPUImage'
```

The second fails with

```
Could not build Objective-C module 'GPUImage'
```

Any ideas as to what we could do here?

**Comment by chetansrm** [comment]
I am facing the same problem
