### ISSUE TITLE
GPUImageVideoCamera: Compiler error when building for iOS 8

### ISSUE THREAD

**Issue by virtualrapha** [BradLarson/GPUImage#1791]
Hey, when building for iOS 8 the GPUImageVideoCamera class gets a couple of compiler errors `Enumeration value 'UIInterfaceOrientationUnknown' not handled in switch`. Can someone please fix this issue? I'm not that experienced with GitHub/pull requests yet...

**Comment by amitm02** [comment]
i have the same issue on the new code
