### ISSUE TITLE
Lanczos filter: is it a simplification of actual algorithm?

### ISSUE THREAD

**Issue by rsebbe** [BradLarson/GPUImage#1800]
When looking at GPUimage's Lanczos resampling filter:

https://github.com/BradLarson/GPUImage/blob/master/framework/Source/GPUImageLanczosResamplingFilter.m

I don't see the correspondance with the algorithm described here:

http://en.wikipedia.org/wiki/Lanczos_resampling

In particular, the original image samples should be weighted by a function that depends on distance between destination sample and original sample distance. I don't see that distance being used in the shader. Am I overlooking something, or is is a simplification of original algorithm?

Could you please comment on this? Thank you.

**Comment by raytrap** [comment]
Just saying, that I agree with @rsebbe that this is not a Lanczos filter. The algorithm uses (or misuses) weights from Lanczos curve. But it's acting as sort of nearest neighbor sampler used on arbitrarily blurred source image.
