### ISSUE TITLE
Problem With GPUImageLookupFilter - Broken Black Images

### ISSUE THREAD

**Issue by OlyRice** [BradLarson/GPUImage#1812]
I am using a recent version of GPUImage but I have noticed that when I now use the GPUImageLookupFilter it starts to product random broken images. Sometimes the images will appear correct and other times they will appear broken. The following is how I go about creating the edited image.

```
GPUImagePicture *lookupImageSource = [[GPUImagePicture alloc] initWithImage:[UIImage imageNamed:@"BigApple1.png"]];

GPUImageLookupFilter * filterLookup = [[GPUImageLookupFilter alloc] init];

[stillImageSource addTarget:filterLookup];
[lookupImageSource addTarget:filterLookup];

[stillImageSource processImage];
[lookupImageSource processImage];

[filterLookup useNextFrameForImageCapture];

finishedImage = [filterLookup imageFromCurrentFramebufferWithOrientation:UIImageOrientationUp];
```

Example

![zybmh](https://cloud.githubusercontent.com/assets/347289/4660780/c6680002-551b-11e4-8111-7f1729d3b3fd.png)

Original Image

![gffsi](https://cloud.githubusercontent.com/assets/347289/4660789/d3e71f10-551b-11e4-83e4-5b85b87a78ce.png)

As mentioned in earlier versions this seemed to work fine. In the image example you can see the filter applied to the image and then the broken thumbnails. Sometimes I can get both broken thumbs and a broken main image.

I have IOS 8, I am not sure if this same issue is also occurring in IOS 7.

Any ideas what is happening to cause this?

**Comment by sashagood** [comment]
Hello. Did you solve this problem? I have similar behaviour.
