### ISSUE TITLE
Shel Script Invocation Error

### ISSUE THREAD

**Issue by oliverwolfson** [BradLarson/GPUImage#182]
Trying to load the project in Xcode 4.3.1

I get a Shell Script Invocation Error.  A path to Script-BC552B3A1558C6FC001F3FFA.sh and "line 5: /usr/local/bin/appledoc: No such file or directory"

In the Linked Frameworks and Libraries section in the Summary, the libGPUImage.a file is red (I assume unfound). 

Not sure how to fix this.

**Comment by AlexShevchenko199112** [comment]
Hello
In using GPUImage framework inxcode, Shell script invocation error happens.so in line 5 appledoc file is not found.How to repaire it

**Comment by BradLarson** [comment]
@AlexShevchenko199112 As stated above, don't build the documentation target. Build the framework target.

**Comment by AlexShevchenko199112** [comment]
Thank you for your consideration.
