### ISSUE TITLE
Can use the bezierpath with GPUImageGaussianFilter?

### ISSUE THREAD

**Issue by Jiang-Song** [BradLarson/GPUImage#1827]
Hello,
I'm beginner of GPUImage. Can you help me?
I would like to apply the GPUImageGaussianFilter to some region of image.
I mean some region is UIBezierPath.
Best Regards.

**Comment by sathiya1926** [comment]
Hi,

I want toselect the portion of image using uibezierpath and apply color on the selected area.

Did you get the solution?
Please help me...
