### ISSUE TITLE
qrcode app

### ISSUE THREAD

**Issue by lngmra** [BradLarson/GPUImage#1833]
Dear Mr. Larson,

I'm a self-taught in programming in iOS... but anyway I have developed an app to read qrcode using the library ZXingObjC and the app is ok! Now I want to integrate the filters in live mode using the GPUImage (in a way that I can scan a filtered qrcode). I haveve imported the GPUImage in the project and I tryed to link the two libraries but without success. My problem is that I don't know how to link the gpuimage object with a CAlayer object. Could you help me?

**Comment by anhmuonnoi** [comment]
@lngmra I am also experiencing the same problem as yours, can you share the solution to this problem
