### ISSUE TITLE
No '?' Needed Line 33 Of FilterListViewController.swift

### ISSUE THREAD

**Issue by AnthonyUccello** [BradLarson/GPUImage#1855]
Xcode 6.1 changed some of the logic with how you access optionals.

As a result 

cell.textLabel?.text = filterInList.listName 

should just  be       

cell.textLabel.text = filterInList.listName

From their 6.1 patch notes:

"The API changes replace T! with either T? or T depending on whether or not the value can be null, respectively. "

**Comment by BradLarson** [comment]
I'll leave it as it is to maintain some backwards compiler compatibility. Compiles fine under 6.1.
