### ISSUE TITLE
Video with green edge

### ISSUE THREAD

**Issue by SPDEX** [BradLarson/GPUImage#1864]
I added a vignette effect to a file and the output has a green edge like in this video:
http://tinypic.com/r/hwlf83/8

Could be because I scaled down the frame from 1920 × 1080 to 700 × 394?
Any idea?

Thanks

**Comment by vatsal1992** [comment]
i had the same issue. i tried this example http://stackoverflow.com/a/39525227/4131763 and succeeded .

**Comment by SPDEX** [comment]
Yes, making width and height even or divisible by 4 should work
