### ISSUE TITLE
Tiebreaker code from non-maximum suppression filter looks wrong

### ISSUE THREAD

**Issue by mabuchner** [BradLarson/GPUImage#1871]
The following lines from GPUImageNonMaximumSuppressionFilter.m look wrong:

```
lowp float multiplier = 1.0 - step(centerColor.r, topColor);
multiplier = multiplier * 1.0 - step(centerColor.r, topLeftColor);
multiplier = multiplier * 1.0 - step(centerColor.r, leftColor);
multiplier = multiplier * 1.0 - step(centerColor.r, bottomLeftColor);
```

Multiplying by 1 and then subtracting might produce a result which is negative.
I think, correct is this:

```
lowp float multiplier = 1.0 - step(centerColor.r, topColor);
multiplier *= 1.0 - step(centerColor.r, topLeftColor);
multiplier *= 1.0 - step(centerColor.r, leftColor);
multiplier *= 1.0 - step(centerColor.r, bottomLeftColor);
```

**Comment by nishant-dani** [comment]
Am curious about this code. We are using multiplier to see how the center stacks up against the left and the top colors.  But for the right and bottom colors we use a step w.r.t. maxValue.  Why not use multiplier for all directions?  Or alternatively maxValue for all directions. Are not both approaches equivalent? It appears that I am missing something very obvious.
