### ISSUE TITLE
Ellipse Detection (Edge Grouping) Feasibility

### ISSUE THREAD

**Issue by maxcan** [BradLarson/GPUImage#1884]
@BradLarson , I'm pretty fresh to gpu programming, do you think that the algorithm discussed here http://enstar-robotcup-2012.googlecode.com/git-history/d2b3c01a7d9b8bad5f75d2e360c5d6318c61568a/CDDetector/ellipse-detection.pdf : could viably be implemented on a gpu?  If you think its feasible, I'm happy to give it a shot, especially if you have some tips on getting started. If, like Hough Circles, see #601, its not, I'll just do it on the CPU and use GPUImage for preprocessing.

Either way, awesome work.

**Comment by BradLarson** [comment]
I honestly don't know. I unfortunately don't have the time to fully review that paper, but I can't tell if what they describe is parallelizable enough to have run on a vertex or fragment shader. The Hough transform line detector implementation I use is based on one that was explicitly written to be a parallel operation and to rely on GPU capabilities.

If something similar could be done in parallel coordinate space for ellipses, perhaps it could be built off of what I have here so far.
