### ISSUE TITLE
GPUImageToneCruveFilter not consistent, returns black image after several image capture

### ISSUE THREAD

**Issue by johnlomboy** [BradLarson/GPUImage#1896]
I have the details posted on stackoverflow, though I am using android-GPUImage, does this exist in IOS version too? please help.

http://stackoverflow.com/questions/28121970/gpuimagetonecurvefilter-returns-black-image-after-several-camera-capture

**Comment by BradLarson** [comment]
I don't know anything about that attempt at an Android port of this project, so I can't answer your question.
