### ISSUE TITLE
Histogram?

### ISSUE THREAD

**Issue by richardsongraph** [BradLarson/GPUImage#1897]
Is there a way to make the histogram more usable? This isn't a common histogram with it being vertical. It doesn't make sense to a photographer. Most of my app users are photographers and users of photoshop. This histogram doesn't look like those histograms. When exposure is increased the graph should shift to the right. Now it just goes up... Thanks!

**Comment by BradLarson** [comment]
Sure. Simply create a variant of GPUImageHistogramGenerator where you edit the kGPUImageHistogramGeneratorVertexShaderString and make the last line

     height = 1.0 - inputTextureCoordinate.x;

instead of 

     height = 1.0 - inputTextureCoordinate.y;

That will now base the calculations on the X coordinate.

**Comment by BradLarson** [comment]
As I stated, you'll need to create a variant of GPUImageHistogramGenerator (what generates the visual representation of the histogram) and edit it to alter the vertex shader at the line I point out above. Take the source to that that class and either edit it directly, or create a new class using its slightly modified code.

**Comment by richardsongraph** [comment]
I clearly have no idea what that means...

**Comment by BradLarson** [comment]
You have the source code to the framework. Take the source code for this class and either modify it as I have described above, or create a new class based on it, using its source code with that modification.

**Comment by richardsongraph** [comment]
I figured out what to do to make this change. I just had to Navigate to the framework to find the file you mentioned and change it. However, I make just that change and got a crazy result. So then I make the change in main to make it look like this:

textureCoordinate = vec2(0.5, inputTextureCoordinate.y);
     //textureCoordinate = vec2(inputTextureCoordinate.y, 0.5);
     //height = 1.0 - inputTextureCoordinate.y;
     height = 1.0 - inputTextureCoordinate.x;

Now I get a really crazy result. And adjusting the exposure doesn't make the map shift like expected.

![ios simulator screen shot feb 2 2015 5 43 26 pm](https://cloud.githubusercontent.com/assets/7084433/6010711/02e39d1a-ab03-11e4-8f83-f8c598cf4083.png)

**Comment by BradLarson** [comment]
I guess I don't understand what's crazy about that. You're getting a horizontal histogram as you wanted.

Is the histogram part of the chain after you apply your filters, or before you apply your filters? It will only pick up properties of whatever stage in the chain you have it targeted off of.

**Comment by richardsongraph** [comment]
It doesn't look like a histogram that a camera or photoshop would use. So 99% of the people who would use the histogram generator can't read the output so it is pointless. It should look like this:

![adobephotoshopcs2-histogram-small](https://cloud.githubusercontent.com/assets/7084433/6011632/2def0482-ab0c-11e4-94ec-0c4af75d9250.gif)

When you adjust exposure in photoshop to add exposure that who graph will slide to the right. Once it reaches the far right it will begin to spike on the right side.

**Comment by goniz20200** [comment]
Brad,

You mention:
"..extract the raw values from the GPUImageHistogramFilter (provided as encoded RGB values at the center of a 256-wide texture in the output) and draw your own Core Graphics graph."

Could you please mention where to look in 'GPUImageHistogramFilter' to extract needed information to feed it through to a Core Graphics graph?

I am also trying to make a "smooth mountain" looking graph with the GPUImage histogram.
