### ISSUE TITLE
what about merge it now？

### ISSUE THREAD

**Issue by DrustZ** [BradLarson/GPUImage#1899]
I mean , the "pause" and "resume" recording function moviewrtier.
It's too useful.

**Comment by BradLarson** [comment]
Are you referring to pull request #1126 ? If so, I can't merge that cleanly and haven't fully evaluated everything it touches.

**Comment by DrustZ** [comment]
I see. 
It does confilict with something now.
Still hoping you can add this function.

**Comment by tspangler** [comment]
Hey @BradLarson, have you been able to evaluate #1126? I'm using @evfemist's ancient fork and would love to see this feature in master.

I understand you're busy and that this isn't your life - I just wanted to show that there's demand for this feature. :+1:

**Comment by BradLarson** [comment]
@tspangler - If you could clean that up so it was able to be merged, I could look at it. Right now, I don't have the time to dig through the merge conflicts between when that was created and the current codebase.
