### ISSUE TITLE
No sound recorded using GPUImageMovie with ALAsset

### ISSUE THREAD

**Issue by zabumba69** [BradLarson/GPUImage#1901]
Hi, I'm using GPUImageChromaKeyBlendFilter with background movie and when I use GPUImageMovie with local file movie by URL I can record movie perfectly with microphone sound but when I use GPUImageMovie with a movie in camera roll (ALAsset) I can't record a video with sound, the output video does a have sound.

I have looked a post with similar problem, but I not found.

I appreciate any help!

**Comment by zabumba69** [comment]
If I export the file to /Documents or /Temp for example continue recording without sound, but if I add the MOV file to my project in xcode it record with sound correctly.

I would love to allow the user to use the camera roll file. Any idea? Has anyone experienced this?

Thanks!

**Comment by zabumba69** [comment]
This is not a bug, I was doing wrong here.

Sorry!

**Comment by AJBeltran3** [comment]
@zabumba69 how did you fix this? I am having the same issue. But i don't see the way to do it. 

I am assuming i have something wrong in my code as well.. 

Thanks.
