### ISSUE TITLE
GPUImage display if alpha blended images failing on simulator

### ISSUE THREAD

**Issue by ender3** [BradLarson/GPUImage#1902]
This is not so much a bug report as a request for help.

My app takes three images, blurs them, and then alpha blends them together. It works wonderfully, GPUImage is a fantastic library.

However, when another developer runs the code on his simulator, the image appears blown out. The problem is definitely most apparent on light colors and areas of white. **This is only on the simulator**. My simulator displays the images fine... most of the time.(See below)

I have managed to replicate this on a separate machine, it is definitely not unique to the other developers' machine.

**15" retina MBP** - seems to display wrong 100% of the time.
**15" 2011 MBP** - seems to display wrong 100% of the time.
**Retina 27" iMac** - seems to display correctly, EXCEPT in one case. If I clean **everything**, delete Derived Data, etc. and then run the GPUImage version of the app, it displays wrong. However, if I revert to a CoreImage based version of the app I had written previously, run it (displays fine) and **THEN** go back to the GPUImage version and run it, it displays great. (This was the way my normal development flow worked, so I never saw the problem until the other developer brought it up).
**Any supported physical iOS (7 or 8) device** - works great, 100% of the time.

Has anyone seen anything similar to this? I know the simulator is **VERY** far from perfect, but it's disconcerting that it displays SOME of the time, and I want to make sure this is not masking some bug that may bite me when the app is in wider distribution on devices.

Thanks.

![ios_simulator_screen_shot_jan_28__2015__9_25_37_am](https://cloud.githubusercontent.com/assets/14858/5940496/dcdae7d0-a6d0-11e4-954e-72ef1f980c18.png)
![screenshot_1_28_15__9_20_am](https://cloud.githubusercontent.com/assets/14858/5940500/e1c4de72-a6d0-11e4-9344-c5be9bfaa8cb.png)

**Comment by BradLarson** [comment]
The Simulator emulates OpenGL ES shaders in software, and doesn't always get the precision, etc. exactly the same as actual hardware. It's also incredibly slow compared to current hardware, even on top-of-the-line Macs. 

To be honest, I rarely test any of this in the Simulator because of the lack of a camera, its broken handling of movies, and the above.

**Comment by ender3** [comment]
Thanks Brad, you really have no idea how much better that makes me feel. We will simply stop testing on the simulator at all. Thank you.
