### ISSUE TITLE
GPUImageLookupFilter produces different results on iPhones

### ISSUE THREAD

**Issue by idealhack** [BradLarson/GPUImage#1906]
Hi, I’m using `GPUImageLookupFilter` on GPUImage `0.1.6` and encountering this problem.

The original image:

![orgin](https://cloud.githubusercontent.com/assets/408385/5987663/f8fb1e0e-a972-11e4-90cc-8064141b65ed.JPG)

It’s OK on iPhone 5s or later devices:

![iphone6](https://cloud.githubusercontent.com/assets/408385/5987666/0f342288-a973-11e4-9502-f52b9cf324d4.JPG)

But on earlier devices it produces:

![iphone5](https://cloud.githubusercontent.com/assets/408385/5987669/1f1f826e-a973-11e4-83d7-32ad6e93d7c1.JPG)

The lookup texture I use:

![texture_lookup](https://cloud.githubusercontent.com/assets/408385/5987671/31f0ee28-a973-11e4-87c0-301669c3e626.jpg)

**Comment by sashagood** [comment]
Hi! Did you solve problem?
