### ISSUE TITLE
Can GPUImage draw texture by triangles?

### ISSUE THREAD

**Issue by tclzwill** [BradLarson/GPUImage#1908]
Hi, Brad.

I just started to study GPUImage and now I want to write a custom filter which I cannot find similar example.
I got a texture picture and a set of texture triangle vertex. For each frame I calculate corresponded target triangle vertex by CPU and want to map the texture from texture triangles to target triangles. How should I write and call the shader file?

**Comment by BradLarson** [comment]
By default, the filters use a standard four vertex, two triangle rendering scheme. For something more complex, you'll need to override the -renderToTextureWithVertices: method in your custom GPUImageFilter subclass and provide your own vertices into that (patterned after what's in the GPUImageFilter class as an example).

Classes like the GPUImageCrosshairGenerator override this to draw custom geometry, so you could look at those for how you might do this. It'll take a little work.
