### ISSUE TITLE
Greyscale live camera feed with overlaid animated static (currently just an image) resulting in only greyscale

### ISSUE THREAD

**Issue by UncleAcid** [BradLarson/GPUImage#1914]
As the title says, I'm trying to display the live camera feed as greyscale with animated static overlaid. I'm using the examples to help me out but I'm stuck on combining an overlay filter with the greyscale filter. 

This is where I'm currently at; (overlay.jpg is the image I am using to test thinking the blend will be more obvious with it instead of the subtle static I really need). This code results in just greyscale video, the blend filter doesn't seem to be doing anything at all. I'm also not sure about the animated overlay part, is it even possible ?

```swift
videoCamera = GPUImageVideoCamera(sessionPreset: AVCaptureSessionPreset352x288, cameraPosition: .Back)

videoView = GPUImageView(frame: CGRect(x: 0, y: 0, width: 352, height: 288))
view.addSubview(videoView!)

greyscaleFilter = GPUImageGrayscaleFilter()
videoCamera?.addTarget(greyscaleFilter)
greyscaleFilter?.addTarget(videoView)

blendFilter = GPUImageOverlayBlendFilter()
videoCamera?.addTarget(blendFilter)
inputImage = ImageCache.loadImage(named: "overlay.jpg")
blendImage? = GPUImagePicture(image: inputImage)
blendImage?.addTarget(blendFilter)
blendImage?.processImage()
blendFilter?.addTarget(videoView)

videoCamera?.startCameraCapture()
```

**Comment by BradLarson** [comment]
You've targeted both your greyscaleFilter and your blendFilter at the videoView. You need to instead target the greyscaleFilter at your blendFilter and only have the blendFilter target your videoView.

**Comment by UncleAcid** [comment]
Hi Brad, thanks for the extremely quick response. I made that change, but it now doesn't seem to do anything; i just see the camera feed. Do you see what's wrong ?

```swift
videoCamera = GPUImageVideoCamera(sessionPreset: AVCaptureSessionPreset640x480, cameraPosition: .Back)

videoView = GPUImageView(frame: CGRect(x: 0, y: 0, width: 640, height: 480))
view.addSubview(videoView!)

blendFilter = GPUImageOverlayBlendFilter()
videoCamera?.addTarget(blendFilter)
blendFilter?.addTarget(videoView)

inputImage = ImageCache.loadImage(named: "bg_gamecomplete_tree.jpg")
blendImage? = GPUImagePicture(image: inputImage)
blendImage?.addTarget(blendFilter)
blendImage?.processImage()

greyscaleFilter = GPUImageGrayscaleFilter()
videoCamera?.addTarget(greyscaleFilter)
greyscaleFilter?.addTarget(blendFilter)

videoCamera?.startCameraCapture()
```

**Comment by BradLarson** [comment]
You've now targeted the camera directly at your blend, along with your image and your grayscale filter. Remove that and just target your grayscale filter at your blend. You can draw out the target chain here, if that might help it make more sense what needs to be targeted to what.

**Comment by UncleAcid** [comment]
I'm sorry, I'm not getting it ... 

I removed videoCamera?.addTarget(blendFilter) and now see nothing. I tried laying it all out and came up with Camera targets Greyscale which targets the Blend  which targets the Video; isn't that what I'm doing ? 

Unmistakably a Friday afternoon ... thanks for helping so quickly.

**Comment by BradLarson** [comment]
```swift
videoCamera = GPUImageVideoCamera(sessionPreset: AVCaptureSessionPreset352x288, cameraPosition: .Back)

videoView = GPUImageView(frame: CGRect(x: 0, y: 0, width: 352, height: 288))
view.addSubview(videoView!)

greyscaleFilter = GPUImageGrayscaleFilter()
videoCamera?.addTarget(greyscaleFilter)

blendFilter = GPUImageOverlayBlendFilter()
greyscaleFilter.addTarget(blendFilter)

inputImage = ImageCache.loadImage(named: "overlay.jpg")
blendImage? = GPUImagePicture(image: inputImage)
blendImage?.addTarget(blendFilter)
blendImage?.processImage()

blendFilter?.addTarget(videoView)
videoCamera?.startCameraCapture()
```

**Comment by UncleAcid** [comment]
Ohhh. Ok, I see how the targeting stuff is supposed to work now. Thank you.

However I still see nothing ... Hmm. By nothing I mean the camera feed isn't even shown anymore.

**Comment by BradLarson** [comment]
Make sure your image isn't opaque and is indeed being loaded properly (try directing it to a GPUImageView by itself). If it's opaque, an overlay blend will cause it to overwrite anything in the first input (or at least I think that's how it's supposed to work).

**Comment by UncleAcid** [comment]
Isn't any jpg opaque ? Also I tried adding the image to a UIImageView and adding it to the view and it shows fine.

**Comment by UncleAcid** [comment]
Finally back to this and I got it working, not exactly sure why it wasn't before, but; I changed a few of the types to not be optional, and therefore had to initialize them in init(coder aDecoder: NSCoder) method of my ViewController, after doing that it works great. Thanks for all the help Brad.

Updated code below.
```swift
var videoCamera: GPUImageVideoCamera
var videoView: GPUImageView
var greyscaleFilter: GPUImageGrayscaleFilter
var blendFilter: GPUImageOverlayBlendFilter
var blendImage: GPUImagePicture?
var inputImage: UIImage?

required init(coder aDecoder: NSCoder) {
    videoCamera = GPUImageVideoCamera(sessionPreset: AVCaptureSessionPreset640x480, cameraPosition: .Back)
    videoView = GPUImageView(frame: CGRect(x: 0, y: 0, width: 640, height: 480))
    
    blendFilter = GPUImageOverlayBlendFilter()
    greyscaleFilter = GPUImageGrayscaleFilter()
    
    super.init(coder: aDecoder)
}

override func viewDidLoad() {
    view.addSubview(videoView)
    
    videoCamera.addTarget(greyscaleFilter)
    
    greyscaleFilter.addTarget(blendFilter)
    
    let inputImage = ImageCache.loadImage(named: "overlay.jpg")
    self.blendImage = GPUImagePicture(image: inputImage)
    self.blendImage?.addTarget(blendFilter)
    self.blendImage?.processImage()
    blendFilter.addTarget(videoView)
    
    videoCamera.startCameraCapture()
    
    super.viewDidLoad()
}

```
