### ISSUE TITLE
How can I recording video without GPUImageMovie and GPUImageVideoCamera??

### ISSUE THREAD

**Issue by demoros79** [BradLarson/GPUImage#1916]
I Just want to recording GPUImagePicture for few seconds
But I don't know how?
please give me a hint :)
```
GPUImageView preview = [[GPUImageView alloc] initWithFrame:CGRectMake(0, 0, 320, 240)];
[self.view addSubview:preview];

GPUImageMovieWriter *movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:... size:...];

GPUImagePicture *picture = [[GPUImagePicture alloc] initWithURL:...];
[picture addTarget:preview];
[picture addTarget:movieWriter];
[movieWriter startRecording];

[picture processImage];
```

**Comment by BradLarson** [comment]
I don't think you can, because GPUImagePicture by itself does not provide proper timestamps. I'm not sure what good that would do, anyway, since all you'd be encoding would be a movie with the same picture over and over.

**Comment by demoros79** [comment]
Thanks Brad,
I made some code .. and It's working .. I think..


//GPUImagePicture+MovieClip.h
@interface GPUImagePicture(MovieClip)
- (instancetype) initWithURL:(NSURL *) url duration:(CMTime) duration;
@end

//GPUImagePicture+MovieClip.m
#import "GPUImagePicture+MovieClip.h"
CMTime _current;
CMTime _duration;

@implementation GPUImagePicture(MovieClip)
- (instancetype) initWithURL:(NSURL *) url duration:(CMTime) duration {
    self = [self initWithURL:url];
    if(self){
        _current=kCMTimeZero;
        _duration=duration;
    }
    return self;
}

- (void) processImage {
    while (CMTimeGetSeconds(_current)<CMTimeGetSeconds(_duration)) {
        runSynchronouslyOnVideoProcessingQueue(^{
            for (id<GPUImageInput> currentTarget in targets) {
                NSInteger indexOfObject = [targets indexOfObject:currentTarget];
                NSInteger targetTextureIndex = [[targetTextureIndices objectAtIndex:indexOfObject] integerValue];
                [currentTarget setInputSize:pixelSizeOfImage atIndex:targetTextureIndex];
                [currentTarget setInputFramebuffer:outputFramebuffer atIndex:targetTextureIndex];
                [currentTarget newFrameReadyAtTime:_current atIndex:targetTextureIndex];
            }
        });
        _current = CMTimeAdd(_current, CMTimeMakeWithSeconds(40/1000.0f, 600));
    }
    
    runSynchronouslyOnVideoProcessingQueue(^{
        [self endProgress];
    });
}

- (void) endProgress {
    for (id<GPUImageInput> currentTarget in targets)
        [currentTarget endProcessing];
}
@end
