### ISSUE TITLE
Reflecting sphere effect?

### ISSUE THREAD

**Issue by cannyboy** [BradLarson/GPUImage#1919]
What's the best combination of effects to accomplish this reflecting sphere effect ? The hand-drawn style as well as the 'fisheye'? 
http://en.wikipedia.org/wiki/Hand_with_Reflecting_Sphere

![Escher Reflecting Sphere](http://upload.wikimedia.org/wikipedia/en/6/66/Hand_with_Reflecting_Sphere.jpg)

**Comment by BradLarson** [comment]
Given that this was drawn by hand, why should there be a filter that can do this?

You could implement some kind of edge detection, thresholding, etc. for the black and white, and a sphere distortion for the sphere, but this is all a drawing.
