### ISSUE TITLE
Apply Filter in Still Camera

### ISSUE THREAD

**Issue by mahesh-agrawal** [BradLarson/GPUImage#1940]
This is not an issue. Am requesting for help. I need to apply 2 filters with eye detection in still camera.
i want to apply bulge filter on eyes when capturing photo with gpuimage still camera. Don't know how to achieve this. am using gpuimage filters to capture image with still camera and applying filters to it. Its working awesome with one or more then one filter. Am using filter pipeline for applying multiple filters in still camera. Please guide me or give me some links that can help me.

**Comment by BradLarson** [comment]
I'm not sure what you want. If you simply want to apply two bulge distortion filters, you can do that in two chained filters with different center coordinates for either filter.

**Comment by mahesh-agrawal** [comment]
am successfully applying filters with different coordinates but i want to apply filter on eye point. i want to display the filter on the "eye point"  while capturing in still camera. user see his/her picture in camera with filter applied. is there any option to do eye detection and apply filter with gpuimage.

**Comment by BradLarson** [comment]
There is no capability within the framework for eye detection. You could build one, if you wanted to spend the effort to do so.

You can also determine some facial coordinates using Core Image independently, and apply that to the image processing. From there, it's just a matter of applying the appropriate distortion on the image.
