### ISSUE TITLE
GPUImage Uploaded and makes white holes

### ISSUE THREAD

**Issue by johnny51925** [BradLarson/GPUImage#1952]
Hi ,

Do anyone know why the image I uploaded to my server with contain "white holes"?

![_sdki1mbxq2byxh4qnsuo](https://cloud.githubusercontent.com/assets/8379957/7000957/6d5d923e-dc6a-11e4-8c92-726cf683d659.jpg)

**Comment by BradLarson** [comment]
This appears to be the same issue as #1823, so I'll close this as a duplicate of that.
