### ISSUE TITLE
Recieved memory warning When applying filter on multiple images (UITableview)

### ISSUE THREAD

**Issue by sovoia** [BradLarson/GPUImage#1953]
Hi all , 

I am using uitableview cells , there are 9 cells in a screen . i am applying filters on iamges added in uitablevire cell . But when it starts memory jheaps jumps to 450+ while adding filters and app is crashing after throwing a memory warning.

i uses [[GPUImageContext sharedFramebufferCache] purgeAllUnassignedFramebuffers]; but no success.

following is code for bluring my images

 GPUImagePicture *stillImageSource = [[GPUImagePicture alloc] initWithImage:[UIImage imageWithData:self.imageData]];
    
    GPUImageGaussianBlurFilter *blurFilter = [[GPUImageGaussianBlurFilter alloc] init];
    blurFilter.blurRadiusInPixels = 40.0f;
    blurFilter.blurPasses = 0;
    blurFilter.texelSpacingMultiplier=4;
    [stillImageSource addTarget:blurFilter];
    
    [blurFilter useNextFrameForImageCapture];
    [stillImageSource processImage];
    
    if (self.isCancelled){
        self.imageData=nil;
        stillImageSource=nil;
        blurFilter=nil;
    }else{
        if ([self.delegate respondsToSelector:@selector(imageDownloaderDidFinishImage:blurrImage:)]) {
            [self.delegate imageDownloaderDidFinishImage:[UIImage imageWithData:self.imageData]  blurrImage:[blurFilter imageFromCurrentFramebuffer]];
            self.imageData=nil;
            [stillImageSource removeAllTargets];
            stillImageSource=nil;
            blurFilter=nil;
        }
    }

Any help would be appriciated .

**Comment by MrBendel** [comment]
The memory management issue likely has nothing to do with GPUImage but rather how you're implementing it in a reusable cell architecture (table view)

Where in the lifecycle of a cell are you calling the code above?

**Comment by sovoia** [comment]
Thanks for reply.

I was calling this in cell for row at index path. so if there were 10
images simultaneously processing app received memory warning . I solved
this via implementing local paging . 3 images at one time processed and
remains in queue. And completion of one i push next in to the queue.

**Comment by sovoia** [comment]
Thanks for reply.
