### ISSUE TITLE
Large Image (6318 × 3168) producing  -[GPUImageFramebuffer generateFramebuffer] Error at CVOpenGLESTextureCacheCreateTextureFromImage -6683

### ISSUE THREAD

**Issue by criosist** [BradLarson/GPUImage#1955]
Hi, been working with GPUImage for a while now and most things work perfectly out the box, thank you.

Working through some fabric bugs and found one that a lot of people have been encountering but most I found, cant reproduce it.

So i tried and found i can reproduce it 100% of the time via using an image of large size in this case (6318 × 3168).

I can get a filtered image through a different means than I am using but the result is always 4096x2053.

Here is my current method for producing a UIImage final result.

    -(UIImage *)imageFromCurrentFilterForFilter:(PreparedFilter *)filter forImage:(UIImage *)image{
    
    GPUImageFilter *lastFilter;
    
    GPUImageFilterGroup *group = [[GPUImageFilterGroup alloc]init];
    
    CGSize size = ((ImageUpload *)self.mediaUpload).filteredImage.size;
    
    GPUImageBrightnessFilter *bright = [[GPUImageBrightnessFilter alloc]init];
    [bright forceProcessingAtSize:size];
    bright.brightness = self.brightness.brightness;
    
    GPUImageContrastFilter *con = [[GPUImageContrastFilter alloc]init];
    [con forceProcessingAtSize:size];
    con.contrast = self.contrast.contrast;
    
    GPUImageSaturationFilter *sat = [[GPUImageSaturationFilter alloc]init];
    [sat forceProcessingAtSize:size];
    sat.saturation = self.saturation.saturation;
    
    [group addFilter:bright];
    [bright addTarget:sat];
    [group addFilter:sat];
    [sat addTarget:con];
    [group addFilter:con];
    
    for(int i = 0; i < filter.filters.count ; i++){
        GPUImageFilter *newFilter = [filter.filters objectAtIndex:i];
        
        if(!lastFilter){
            lastFilter = newFilter;
            [con addTarget:lastFilter];
            [group addFilter:lastFilter];
            continue;
        }
        
        [lastFilter addTarget:newFilter];
        
        [group addFilter:newFilter];
        
        if(newFilter == filter.filters.lastObject){
            lastFilter = newFilter;
        }
    }
    
    [group setInitialFilters:@[bright]];
    [group setTerminalFilter:lastFilter];
    
    return [group imageByFilteringImage:image];
    }

Thanks for any information.

I can provide the image if need be :D

EDIT:

After removing "forceProcessingAtSize:size" from the method on all filters it no longer crashes but produces the smaller  4096x2053 every time ?

**Comment by BradLarson** [comment]
That's probably due to the size of the image. The modern iOS devices have GPUs that can only handle textures at a max dimension of 4096x4096. Anything larger than that cannot be processed by the framework.

In a few places, I check for this and resize the image so that it fits on a texture, but that will lose image quality. I don't check in others, so this can sometimes lead to crashes when you try to create images larger than this.

Until some kind of tiling mechanism is implemented, the framework is limited to only being able to process images smaller than the maximum GPU texture size.
