### ISSUE TITLE
GPUImageHighPassFilter for image

### ISSUE THREAD

**Issue by Odobush1** [BradLarson/GPUImage#1958]
Hi, Brad
Thank you for the work you`ve done, it saves a lot of time for many people!
I need to recreate Photoshop HighPassFilter for image. Unfortunately your GPUImageHighPassFilter is only for video. Could you help me
It is start image (inverted and overlay blended)
![1](https://cloud.githubusercontent.com/assets/8805058/7178009/2d8b4512-e434-11e4-8c6d-fae8225efdcd.jpg)
And this result I expect to receive

![2](https://cloud.githubusercontent.com/assets/8805058/7178039/685cbb1c-e434-11e4-8882-4ba8f0885f2f.jpg)

Thanks in advance!

**Comment by BradLarson** [comment]
There currently is no such filter in the framework. Perhaps you could use a blur and a custom fragment shader to pull out the elements above the blurred background. Not quite sure how Photoshop does it.
