### ISSUE TITLE
warning: no umbrella header found for target 'GPUImageFramework', module map will not be generated

### ISSUE THREAD

**Issue by williamhqs** [BradLarson/GPUImage#1963]
Hi, GPUImage works well on my device, but when i want to build/Run on simulator, i got the error:
>error: unable to read module map contents from 'Source/iOS/Framework/module.modulemap': Error Domain=NSCocoaErrorDomain Code=260 "The file “module.modulemap” couldn’t be opened because there is no such file." UserInfo=0x7f8938e38920 {NSFilePath=/Users/william/A/muguang-ios/Source/iOS/Framework/module.modulemap, NSUnderlyingError=0x7f8922f15df0 "The operation couldn’t be completed. No such file or directory"}
warning: no umbrella header found for target 'GPUImageFramework', module map will not be generated

So where is "module.modulemap" ? thanks!
As below:
![screen shot 2015-04-19 at 2 09 31 pm](https://cloud.githubusercontent.com/assets/354829/7218375/e3f00ad4-e69d-11e4-8bda-4fcbbcb0ed33.png)

**Comment by williamhqs** [comment]
Fixed it, find *module.modulemap* in my own path.

**Comment by siegfriedpammer** [comment]
I am having the same problem. Where would I find the module.modulemap?

**Comment by ibrahimkteish** [comment]
@williamhqs how did you fix it ?

**Comment by williamhqs** [comment]
Sorry guys, it's a long time i can't remember where it is, but i would suggest on "Copy bundle resources" and "Complie Sources" if you can't find it on bundle path.

**Comment by rosensts** [comment]
I had the same issue. I think it had to do with not adding the framework into the project properly. I just removed the framework and redid the whole installation. Worked like a charm :)
