### ISSUE TITLE
how to  write custom filer

### ISSUE THREAD

**Issue by anil03** [BradLarson/GPUImage#1965]
Thanks for help.
i want to use Custom filter in GPUImage.
what is file format of it and how do i create file to write shader code init.
i have RGB value of filter.
for example : 
RGB : output 84 input 76
Red : 135 108
green :112 124
blue : 115 130

Please suggest me way write and use it

**Comment by BradLarson** [comment]
Explaining how to write a custom fragment shader is the scope of a chapter in a book, so I won't be able to do that here. Take some time and read through the 100+ shaders that come within the framework to see how they operate, and to use as a basis for modification.
