### ISSUE TITLE
how to apply filters on run time when video file is playing

### ISSUE THREAD

**Issue by anil03** [BradLarson/GPUImage#1966]
I want to apply a multiple filer on video file on run time to check which filter is looking good.
than i want to select that filter and export with selected filter.

**Comment by BradLarson** [comment]
No clue what you're asking here.

**Comment by anil03** [comment]
in simple way, I have video file i am using GPUImage view to show video file. and it playing.
i have scroll view and in scroll view there are 5 buttons.
on each button there are defferent filters. when i clicked button one than filer one should apply on video file. and when i select second button than filter second apply. so on.

 there is on done button when i clicked on that than i should use Moviewriter class to export movie filw with applied filter.

So i am unable to test the filers on button click.
how do i acheive such kind of senario. like instagram do on Photo i want to do on video file

**Comment by alex-chan** [comment]
It's just a normal usage.   GPUImageMovie --->GPUImageFilter--->GPUImageView. just change the filter as you like will get what you want.
