### ISSUE TITLE
how to use filter on video file like instagram

### ISSUE THREAD

**Issue by anil03** [BradLarson/GPUImage#1967]
in simple way, I have video file i am using GPUImage view to show video file. and it playing.
i have scroll view and in scroll view there are 5 buttons.
on each button there are defferent filters. when i clicked button one than filer one should apply on video file. and when i select second button than filter second apply. so on.

there is on done button when i clicked on that than i should use Moviewriter class to export movie filw with applied filter.

So i am unable to test the filers on button click.
how do i acheive such kind of senario. like instagram do on Photo i want to do on video file

**Comment by BradLarson** [comment]
Please stop spamming issues for this.

To change filters on a live video, all you need to do is to remove the old filter as a target for your movie source, then remove the GPUImageView preview as a target from your old filter. Add the new filter as a target of your movie and target it to your GPUImageView.

When done, if you need to apply a specific filter to your movie for re-recording, simply add that filter as a target of your movie and run the movie through to a writer for its entire duration.
