### ISSUE TITLE
Add GPUImageAlphaBlendFilter and GPUImageColorBlendFilter to GPUImageStillCamera... why is this so hard?!

### ISSUE THREAD

**Issue by holgersindbaek** [BradLarson/GPUImage#1970]
I'm trying to add an overlay image with the blend filters GPUImageAlphaBlendFilter and GPUImageColorBlendFilter, and I cannot for the life of me get it to work.

This is how my code looks now (Rubymotion):

      # Initialize camera
      @camera = GPUImageStillCamera.alloc.initWithSessionPreset(AVCaptureSessionPresetPhoto, cameraPosition: AVCaptureDevicePositionBack)
      @camera.outputImageOrientation = UIInterfaceOrientationPortrait

      # Blend alpha filter
      @filter = GPUImageAlphaBlendFilter.new
      @filter.mix = 0.5

      # Blend color filter
      color_filter = GPUImageColorBlendFilter.new
      @filter.addTarget(color_filter)

      # Add filters to image
      overlay_image = GPUImagePicture.alloc.initWithImage("fades-right".uiimage, smoothlyScaleOutput: true)
      overlay_image.addTarget(@filter)
      overlay_image.addTarget(color_filter)
      overlay_image.processImage

      # Add filter to camera
      @camera.addTarget(@filter)
      @camera.startCameraCapture
      @filter.addTarget(camera_view)

The alpha blend filter is working, but the color blend filter is not working at all. Any hints to what I'm doing wrong here?

**Comment by BradLarson** [comment]
@filter.addTarget(camera_view)

should be 

    @color_filter.addTarget(camera_view)

You're not directing the output from the color blend to the screen, only the alpha blend.

**Comment by holgersindbaek** [comment]
@BradLarson Beautiful. It seems to be working. Thanks a lot.

A side question... I've tried to use the the gaussians blur effect and it works nicely. I need the blur only to blur in a specific shape (which is not square or round). Is that possible?

**Comment by BradLarson** [comment]
You can use the GPUImageGaussianSelectiveBlurFilter as a template, but that filter basically does a Gaussian blur and then uses a custom fragment shader to indicate which pixels to blur or not. It wouldn't take much effort to copy that and modify to specific shapes.

**Comment by holgersindbaek** [comment]
@BradLarson Thanks for the answer. I'll look into it. 

Last question... I'm using 6 different images that I need to use as the overlay and I'm doing it using this function that I set before adding the filter to the view:

    def set_filter_image(index)
      overlay_image = GPUImagePicture.alloc.initWithImage(fades_image(index), smoothlyScaleOutput: true)
      overlay_image.addTarget(@filter, atTextureLocation: 1)
      overlay_image.addTarget(@color_filter, atTextureLocation: 2)
      overlay_image.processImage
    end

It's kind of slow though. It takes around 1 second for the overlays to be applied and that's a bit slow for how what I'm doing. How would you do this? Is there any way to set the 6 different overlays on the filter to start with and change between them?

**Comment by holgersindbaek** [comment]
@BradLarson Any suggestions on this?

**Comment by BradLarson** [comment]
If you're not going to be too pressed on memory, I'd allocate the GPUImagePictures once (which does the slow upload from Core Graphics to OpenGL textures), keep them around, and then swap them in and out of place in your filter chain as needed. You'd call processImage every time they would be added or removed from the chain, but that only triggers a re-processing from the point of the texture on, so it's all on the GPU. That's way faster than re-uploading the entire image.

**Comment by holgersindbaek** [comment]
@BradLarson That sounds like a good idea. And how would you "swap them around?

If I initiates all the images like this:

    overlay_image_one = GPUImagePicture.alloc.initWithImage("fades-one".uiimage, smoothlyScaleOutput: true)
    overlay_image_two = GPUImagePicture.alloc.initWithImage("fades-two".uiimage, smoothlyScaleOutput: true)
    overlay_image_three = GPUImagePicture.alloc.initWithImage("fades-three".uiimage, smoothlyScaleOutput: true)

How would I swap those 1 pictures around?

**Comment by BradLarson** [comment]
To remove picture from the chain, remove all its targets. To add a picture into the chain, add the appropriate targets to it. Once you've added it into the chain, use processImage to propagate the texture down the pipeline.

**Comment by holgersindbaek** [comment]
@BradLarson I still don't fully understand how you would do that. Can you give an example?!

**Comment by tikamsingh** [comment]
Hello @BradLarson , 
Need your suggestion in following points.

1> I am using GPUImageChromaBlendFilter its working on only red ,green and blue color, But I want to use filter any color, Like Gray ,RGB (0.75, 0.75,0.75) or any different RGB value but it not working properly.

Its showing whole background image.

Please suggest how i can convert to support any rgb color filter.

2>I set portrait in Video Camera and same screen when i pick image from gallery for setting background image it is not coming on portrait form. How i can handle it.

3> video capture image always saved in left orientation.

4> It will be better if you provide life cycle of this filter process.(ChromaBlendFilter)

Please suggest.
