### ISSUE TITLE
Any luck with Logitech C920

### ISSUE THREAD

**Issue by Phando** [BradLarson/GPUImage#1971]
Hey All,
I am working on a new project and trying to use a HD Pro Webcam C920 with the simple video filter example. When ever I try to use that camera (or any other external camera) the screen is blank. Does the code below look correct? The only difference between my code and the example is the final argument to initWithSessionPreset where I am passing device instead of nil.

```
for ( device in [AVCaptureDevice devices] ) {
         if( [device.localizedName isEqualToString:@"HD Pro Webcam C920"] )
        {
            break;
        }
    }
    videoCamera = [[GPUImageAVCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraDevice:device];
```

Thanks in advance,
Joe

**Comment by BradLarson** [comment]
So I actually have a Logitech C920 here as part of a test rig (it's what I tested the GPUImageAVCamera code against), and I can get it to connect just fine in the FilterShowcase sample. I used the following code as a modification of the SLSFilterShowcaseWindowController in the windowDidLoad method:

```
    AVCaptureDevice *cameraToUse = nil;
    for (AVCaptureDevice *connectedDevice in [GPUImageAVCamera connectedCameraDevices])
    {
        NSLog(@"Device: %@, UUID: %@", connectedDevice, [connectedDevice uniqueID]);
        NSLog(@"Device: %@, name: %@", connectedDevice, [connectedDevice localizedName]);
        
        if ([connectedDevice.localizedName isEqualToString:@"HD Pro Webcam C920"])
        {
            NSLog(@"Device found");
            cameraToUse = connectedDevice;
        }
    }
    
//    inputCamera = [[GPUImageAVCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 deviceUniqueID:@"0x1d111000046d082d"];
    inputCamera = [[GPUImageAVCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraDevice:cameraToUse];
```

and that seemed to do the trick. The camera connected and started displaying just fine with that. I also did it with the device ID, to make sure that connected properly too.

**Comment by Phando** [comment]
Like a charm!Bring on the new project.
Thank you Brad!
