### ISSUE TITLE
Chaining multiple filters together

### ISSUE THREAD

**Issue by rashidasgari** [BradLarson/GPUImage#1975]
I am trying to chain 3 different filters (brightness,contrast and saturation) together. Actually the goal is to have three UISliders that change these three values and apply them on an image. My code does not seem to work though.

I use this code for all the UISlider Actions:

- (IBAction)brightnessSlider:(UISlider *)sender {
    
    brightnessValue = sender.value;
    
    UIImage *inputImage = [UIImage imageNamed:@"2.jpg"];
    
    GPUImagePicture *stillImageSource = [[GPUImagePicture alloc] initWithImage:inputImage];
    
    [brightnessFilter setBrightness:brightnessValue];
    [contrastFilter setContrast:contrastValue];
    [saturationFilter setSaturation:saturationValue];
    
    [brightnessFilter addTarget:contrastFilter];
    [contrastFilter addTarget:saturationFilter];
    [stillImageSource addTarget:brightnessFilter];
    [brightnessFilter useNextFrameForImageCapture];
    [stillImageSource processImage];
    
    UIImage *currentFilteredVideoFrame = [stillImageSource imageFromCurrentFramebuffer];
    
    brightnessOutput = currentFilteredVideoFrame;
    imageView.image = currentFilteredVideoFrame;
}

**Comment by Phando** [comment]
Depending on how you set up your filter chain, you should not need to reset your image or pull a frame from it. 

Filter setup:
```
UIImage *inputImage = [UIImage imageNamed:@"WID-small.jpg"];
    
sourcePicture = [[GPUImagePicture alloc] initWithImage:inputImage smoothlyScaleOutput:YES];
f1 = [[GPUImageBrightnessFilter alloc] init];
f2 = [[GPUImageContrastFilter alloc] init];
f3 = [[GPUImageSaturationFilter alloc] init];

GPUImageView *imageView = (GPUImageView *)self.view;
[sourcePicture addTarget:f1];
[f1 addTarget:f2];
[f2 addTarget:f3];
[f3 addTarget:imageView];

[sourcePicture processImage];
```

Then in your slider handlers you should only need to update the properties on your existing filter chain. Then call processImage to propagate the change. The code below has all the filter properties though two are commented out.

```
CGFloat value = [(UISlider *)sender value];
[(GPUImageBrightnessFilter*)f1 setBrightness:value];
//[(GPUImageContrastFilter*)f2 setContrast:value];
//[(GPUImageSaturationFilter*)f3 setSaturation:value];
    
[sourcePicture processImage];
```

**Comment by rashidasgari** [comment]
@Phando thanks for the reply but i still did not get anything from the above code so i decided to use filter groups but still no progress.

brightnessValue = sender.value;
    UIImage *inputImage = [UIImage imageNamed:@"2.jpg"];
    
    GPUImagePicture *sourcePicture = [[GPUImagePicture alloc] initWithImage:inputImage smoothlyScaleOutput:YES];
    GPUImageFilterGroup *groupFilter = [[GPUImageFilterGroup alloc]init];

    GPUImageBrightnessFilter *brightnessFilter = [[GPUImageBrightnessFilter alloc] init];
    [brightnessFilter setBrightness:brightnessValue
     ];
    
    GPUImageContrastFilter *contrastFilter = [[GPUImageContrastFilter alloc] init];
    [contrastFilter setContrast:contrastValue];
    
    GPUImageSaturationFilter *saturationFilter = [[GPUImageSaturationFilter alloc] init];
    [saturationFilter setSaturation:saturationValue];
    
    [brightnessFilter addTarget: contrastFilter];
    [contrastFilter addTarget: saturationFilter];
    
    [groupFilter addTarget:brightnessFilter];
    [groupFilter addTarget:contrastFilter];
    [groupFilter addTarget:saturationFilter];
    
    [groupFilter setInitialFilters:[NSArray arrayWithObjects:brightnessFilter, nil]];
    [groupFilter setTerminalFilter:saturationFilter];
    
    [sourcePicture addTarget:groupFilter];
    
    [sourcePicture processImage];
    
    UIImage *outputImage1 = [groupFilter imageFromCurrentFramebuffer];

    imageView.image = outputImage1;

**Comment by rashidasgari** [comment]
Ok i figured it out, the above code is correct i was only missing [groupFilter useNextFrameForImageCapture];
