### ISSUE TITLE
iOS GPUImage and Multithreading

### ISSUE THREAD

**Issue by goniz20200** [BradLarson/GPUImage#1988]
I've been using just AVFoundation all this time.

I have been following Apple's sample code projects and they always do multithreading on their 'camera app sample code' projects.

In AVFoundation, they have a new thread ('sessionQueue') processing all the AvFoundation session tasks. They note that this is to keep the camera feed clean and to avoid interruptions from the main UI tasks.

dispatch_queue_t sessionQueue = dispatch_queue_create("session queue", DISPATCH_QUEUE_SERIAL);

This has been working great for me all this time and I do understand why they did this approach.

However, I recently adopted Brad Larson's GPUImage Api, and he does not specify any multithreading in his documentation.

Should I just not worry about and dispatching?

**Comment by BradLarson** [comment]
If you look at how things are architected internally, I use a serial dispatch queue to handle the video upload and processing functions and then a separate dispatch queue for the AV-Foundation-based movie writer output. This should handle threading for you, and you won't need to manage manual dispatches yourself.
