### ISSUE TITLE
GPUImageLookupFilter Crashing on Video

### ISSUE THREAD

**Issue by uzmanup** [BradLarson/GPUImage#1989]
i am using GPUImageLookupFilter to apply custom filter on video but after giving memory warning it crashed..
please let me know is it possible to apply customer filter using GPUImageLookupFilter or any better solution i have filter files in png's as well in psd's
regards

**Comment by BradLarson** [comment]
You haven't described how you set up this filter, the size of video you were processing, how you handled the video, or anything else that could possibly be used to diagnose this issue, so I'm closing this.
