### ISSUE TITLE
How to blend two images.

### ISSUE THREAD

**Issue by bestman0809** [BradLarson/GPUImage#199]
Hi.

I am going to use GPUImageOverlayBlendFilter for two images.

UIImage *inputImage1, inputImage2;

How to apply blend filter for this two images?

Looking forward to hearing from you.

Thanks.

**Comment by Bola5** [comment]
@BradLarson  I need to blend the first two frames coming from video capture and the resulted frame blended with the third and so on ( in live video ) ... 

Please Any Help ....
