### ISSUE TITLE
Brightest Point Strategy

### ISSUE THREAD

**Issue by Phando** [BradLarson/GPUImage#1990]
Hey All,
I am building a large version of Duckhunt and am using GPUImage with an IR camera to pick up where IR lasers are shooting the screen. I am unsure what strategy I should take for finding the laser dots. I know they will be brightest points in the image. 

Does this sound right?
contrast - make the white whiter and black blacker
average or range - determine the brightest and darkest pixels.
expand - normalize the pixel values between 0-1 based on the average/range output
image output - Somehow get the locations of the brightest pixels.

Any direction would be awesome,
Joe

**Comment by Phando** [comment]
I am looking for blob detection, not the brightest point.

**Comment by BradLarson** [comment]
I don't have anything in there for individual blob detection. The color object tracking example that ships with the framework is based on simple thresholding around a color, then doing a whole-scene weighting to determine the centroid of that color in the entire scene. It will take something a little more advanced to pull out multiple objects.
