### ISSUE TITLE
GPUImageChromaKeyFilter working in simulator but not on tablet

### ISSUE THREAD

**Issue by idsinc** [BradLarson/GPUImage#1999]
When I process the green screen image in the simulator it works perfectly, but when I do it on the iPad you can still see the green... it's transparent but not fully transparent...

Is there a setting for the replacement alpha value missing?

**Comment by idsinc** [comment]
I have it working, but why does it display it as a green screen that is slightly transparent.. but when you save it or reprocess it it shows up transparent

**Comment by jerday** [comment]
How did you resolve this? Experiencing the same thing.

**Comment by idsinc** [comment]
if you saved the picture out you would see it processed fine. It just does not display correct on the screen something to do with GPUImage internal UImage ... What I did is covert the UImage to a NSData block and then back to a UImage and it displays correct.

**Comment by jerday** [comment]
Ah! Used UIImagePNGRepresentation and it's sweet now. Thanks!
