### ISSUE TITLE
!carsh,  at GPUImageOutput.m:63

### ISSUE THREAD

**Issue by yishuiliunian** [BradLarson/GPUImage#2002]
i add a GPUImageMovieWriter to the camera， it carsh when startRecording

![screenshot](https://cloud.githubusercontent.com/assets/846525/7718943/fcd2a8d0-feea-11e4-9e4e-b0bb9e1f34ad.png)

**Comment by BradLarson** [comment]
With that little detail, I'm afraid I can't help you. You're going to need to provide sample code and a better indication of where this is crashing.

**Comment by aiyub007** [comment]
Same problem I have Also while writing movie Submitted an issue #2295
Input saved mov Video and get Output as Filtered mov file

https://github.com/BradLarson/GPUImage/issues/2295
