### ISSUE TITLE
glueValidateProgram Current framebuffer is invalid

### ISSUE THREAD

**Issue by willSapgreen** [BradLarson/GPUImage#2004]
Hello,

I am integrating GPUImage with RoysWriter, which is the Apple official sample code.
( https://developer.apple.com/library/ios/samplecode/RosyWriter/Introduction/Intro.html )

What I am trying to do is displaying the result from GPUImage on RosyWriterPreviewView,
but when I call GPUImagePicture::initWithImage, 
I got "Current framebuffer is invalid" from glueValidateProgram in RosyWriterPreviewView and gets stuck on the last image from the camera.
If I comment out GPUImagePicture::initWithImage, the error is gone and RosyWriterPreviewView shows the image from the camera continuously.

I guess GPUImagePicture::initWithImage takes the controllability of Frame Buffer and never let it go. Is there any approach to take Frame Buffer back?

Please let me know if any problem and thank you for precious time on my question.

**Comment by BradLarson** [comment]
GPUImage can do everything RosyWriter does, so I see no need to have to integrate it with that project.

If you do wish to have the two work together, you'll need a GPUImageTextureInput or GPUImageTextureOutput (depending on which way you go), and will need to pass a texture between the two processing sides. RosyWriter and GPUImage will also need to have their OpenGL context within the same share group.

The cube example within GPUImage shows how to do this with an arbitrary OpenGL context.
