### ISSUE TITLE
How to use GPUImageFASTCornerDetectionFilter?

### ISSUE THREAD

**Issue by yipsilon** [BradLarson/GPUImage#2024]
In sources, I find the GPUImageFASTCornerDetectionFilter.m file.
How to use it for corner detection?

**Comment by BradLarson** [comment]
You can't, at least not yet. It's just a stub I mistakenly committed once. I haven't finished it.

You're welcome to help me out with that. I just need to get the preloaded textures configured to do the bitfield-based lookups based on the Bresenham circle samples.
