### ISSUE TITLE
cant able to detect (nofication) when frame change in video camera also drow circle on moving object in frame

### ISSUE THREAD

**Issue by nitinumaretiya** [BradLarson/GPUImage#2029]
i am new at GPUImage , i cant able to understand this. in my application i can start video camera but can't able to draw rectangle on moving object in frame or not getting notify when change happen in current frame . i need full code for this please anyone can help  me. https://www.youtube.com/watch?v=BRrddjF_smw&feature=player_embedded @BradLarson

**Comment by BradLarson** [comment]
Sorry, but what you're asking is no simple task. No one is going to be able to hand you "full code for this".

The motion detector in the framework is a very crude one, relying on frame-to-frame pixel changes. You can see how I draw a box around the approximate centroid of these pixels in the FilterShowcase.

**Comment by nitinumaretiya** [comment]
sasasas
