### ISSUE TITLE
Just getting white screen iOS 8.3

### ISSUE THREAD

**Issue by Tagalong** [BradLarson/GPUImage#2033]
Added code as described in "Filtering Live Video" but changed filter to Sepia and added GPUImageView as subview of main view. All I get is white screen. What gives?

Also, if you turn off camera access while app is running, app crashes on connected device. Is this normal behavior in release version?

**Comment by BradLarson** [comment]
I can't tell you more without seeing your code, but I'm guessing that you're not providing a strong reference to your GPUImageVideoCamera object and that it's being deallocated by ARC. You need to hold on to this, or the video processing will fail once this object is deallocated.

**Comment by Tagalong** [comment]
It still isn't working. I copied code directly from examples - white screen or crash from loading filters. Running 8.4 on 5S.
