### ISSUE TITLE
GPUImageMovieWriter audioEncodingTarget frame drops

### ISSUE THREAD

**Issue by MrBendel** [BradLarson/GPUImage#2036]
This isn't really an issue with GPUImage so sorry if this is the wrong forum but I was curious if anyone had any experience with reducing the main thread hit from using the audioEncodingTarget. Whenever I start recording with the audioEncodingTarget set, there's always a black frame at the very beginning. If I don't set the audioEncodingTarget there's no black frame.

I thought it might be something the audio category switching but that doesn't seem to help. Any input would be greatly appreciated!

**Comment by MrBendel** [comment]
Looks like its a proponent of `addAudioInputsAndOutputs` in `GPUImageVideoCamera`

**Comment by MrBendel** [comment]
So it looks like if I add the audio targets once in the initial configuration setup, it works fine. Adding and removing them on the fly is causing the frame drops. I think I'll just set up a different initialization category for switching between on the fly audio setup / teardown and one initial audio setup / teardown.

**Comment by mingyue1991** [comment]
in my case, if i don't call addAudioInputsAndOutputs at init , when i start record, the preview will be black for a second , but if i call it, preview don't get black, then there's a black frame at the beginning of the output movie. comfused...how to resove
