### ISSUE TITLE
That's possible translate GPUImage from objective-c to swift?

### ISSUE THREAD

**Issue by nohackcc** [BradLarson/GPUImage#2043]
That's possible translate GPUImage from objective-c to swift?Have Time Plan or orhters?

**Comment by BradLarson** [comment]
GPUImage works perfectly fine within a Swift application. See the Swift example applications for how this works. It doesn't need to be completely rewritten in Swift.

I won't even contemplate rewriting it in Swift until people no longer need to deploy to iOS 7 or lower, or below OS X 10.9. That will be a while.
