### ISSUE TITLE
GPUImageView.m crash

### ISSUE THREAD

**Issue by jhergott** [BradLarson/GPUImage#2045]
Every time I open my application from Xcode and go to the camera in my application I get a (lldb) with no error message and the following line is highlighted.
```
[[[GPUImageContext sharedImageProcessingContext] context] renderbufferStorage:GL_RENDERBUFFER fromDrawable:(CAEAGLLayer*)self.layer];
```
(line 167 in GPUImageView.m)

The app does not crash if I open the app straight from my phone.  

Also, what is really weird is that it is only happening to two of my devices (both iPhone 6's) and ran fine without the error on two different devices (iPhone 6 and iPhone 5s).

Any thoughts? Thanks

**Comment by BradLarson** [comment]
This is a known issue with iOS 8.3: https://github.com/BradLarson/GPUImage/issues/2022#issuecomment-118943746 and appears to be restricted to just that iOS version and specific devices.
