### ISSUE TITLE
Update cocoapods trunk

### ISSUE THREAD

**Issue by DimaVartanian** [BradLarson/GPUImage#2047]
The current available release on cocoapods is 0.1.6 which is almost a year old. Any chance an update could be pushed to the trunk?

From my understanding you should just be able to run:

`pod trunk push GPUImage.podspec`

**Comment by BradLarson** [comment]
There is a 0.1.7 tag: https://github.com/BradLarson/GPUImage/tree/0.1.7 that I added to update this. Someone else maintains the CocoaPods stuff, and I don't know how any of that works. You'd have to check with them to determine what needs to be updated on the CocoaPods end. I haven't ever used CocoaPods before, to be honest.

**Comment by DimaVartanian** [comment]
The command I posted above should do it. Could you give that a shot? (doing it in the project repro on your machine)

**Comment by DimaVartanian** [comment]
Hi Brad, I was able to get ahold of Ernesto and had him add me to the cocoapods repo and was able to update the trunk to 0.1.7 so all is good now. For the future all you will need to do is update the podspec and tag the release as you have been doing and I can keep it updated for you in the trunk. If/when you decide you want to be added to the cocoapods repo you just need to register with the trunk by [following these instructions](https://guides.cocoapods.org/making/getting-setup-with-trunk) and then I can add you as another owner on it. No rush on that though since I will keep it updated for you whenever possible. Thanks a ton for this great project!
