### ISSUE TITLE
GPUImageSaturationFilter delivering different results in different devices

### ISSUE THREAD

**Issue by joselufo** [BradLarson/GPUImage#2051]
We've been using the "GPUImageSaturationFilter" and we've figured out it delivers different results from one device to another. So far we've seen differences between an iPhone 5 and iPhone6/6+ devices, also tested with iPod touch but the result is ok.

I've attached the images for the filter showcase project samples of your library.

![img_5873](https://cloud.githubusercontent.com/assets/3983619/8725683/eae3978e-2bd5-11e5-85f9-a337c8529a96.JPG)

We would like to know what's going on, if it's a known bug or if there's any solution we could use for fixing it.

Thanks!

**Comment by BradLarson** [comment]
That's odd. I hadn't seen that before, even on different devices.

Try this: go into the GPUImageSaturationFilter.m file and find the fragment shader for the saturation operation at the top of the file. Change everywhere it says "lowp" to "mediump" and rebuild the project and sample applications. See if this still occurs.

It might be related to limited precision of the color calculations (done as a performance optimization), and the rounding might be handled differently on different GPUs.

**Comment by joselufo** [comment]
@BradLarson Thanks a lot for the quick response. 

I will check it and let you know.
