### ISSUE TITLE
Issue about blurring the video and add watermark

### ISSUE THREAD

**Issue by carusd** [BradLarson/GPUImage#2054]
I currently use GPUImage to add watermark.And I want to blur the video first and add a text as a watermark.But it turns out blurring the text too.
the filter chain is like this:

movie----gaussian filter----alpha blend filter----movie writer
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  |
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; GPUImageUIElement

the view in the GPUImageUIElement was blurred, too.

the code is like this:

you can see the detail and code in here:

http://stackoverflow.com/questions/31492417/how-can-i-get-a-gpuimageuielement-over-a-blur-video-without-blurring-the-element

I don't know if I use it wrong, please help, thx in advance

**Comment by BradLarson** [comment]
I've explained on SO, but you're placing your blur after your blend, so of course it will blur the blended image.
