### ISSUE TITLE
How to specify filter size for GPUImageMedianFilter and GPUImageGaussianBlurFilter

### ISSUE THREAD

**Issue by vondiplo** [BradLarson/GPUImage#206]
I would like to specify the filter size (radius) of the GPUImageMedianFilter and GPUImageGaussianBlurFilter.

Does that demand specifying GPU commends? Or can it be done through the GPUImage wrapper? If so, how can I do that?

Thanks

**Comment by kartickvad** [comment]
If I may, I'd like to second the request for different sizes of median filters like 5x5 or 5x3.
