### ISSUE TITLE
Face Detection

### ISSUE THREAD

**Issue by pjebs** [BradLarson/GPUImage#2066]
You wrote on the this library doesn't include Face Detection.

It is quite easy to implement using OpenCV for iOS:

http://docs.opencv.org/doc/tutorials/ios/table_of_content_ios/table_of_content_ios.html

**Comment by BradLarson** [comment]
There's nothing stopping you from using OpenCV or Core Image for this. I just haven't implemented a GPU-accelerated facial detection process in the framework myself.
