### ISSUE TITLE
Why can't I add GPUImage as a subproject?

### ISSUE THREAD

**Issue by martinjbaker** [BradLarson/GPUImage#2072]
I'm using Xcode 6.4 and dragging the GPUImageMac.xcodeproj file into my main project as suggested. But it just appears as a single file - no details underneath about the number of targets or SDK version. Therefore I can't add it as a target dependency.

What am I missing?

**Comment by BradLarson** [comment]
Make sure you don't have more than one Xcode project open that is using this framework. If more than one project uses the same sub-project, the other projects will show this as being a single file and won't build it properly. You have to close those other projects and reopen the one you want to work on.

It's a limitation with Xcode and sub-projects.

**Comment by martinjbaker** [comment]
Yep that was it. Can that be added to the readme for future users?

**Comment by JackeryShh** [comment]
hi,I have the same problem , I couldn't add GPUImage as a subproject. Though iI using this framwork;
