### ISSUE TITLE
I've got a local video file, how can I add a filter effect rather than generate a new video file？

### ISSUE THREAD

**Issue by qushuai520** [BradLarson/GPUImage#2082]
I've got a local video file, how can I add a filter effect rather than generate a new video file. I want to see this video filter effects in real time,not GPUImageMovieWriter, what should I do? Thank you.

**Comment by BradLarson** [comment]
You can simply use a GPUImageMovie source and play it back through filters to a GPUImageView. By enabling actual speed playback, you will get the movie playing back at a normal speed.
