### ISSUE TITLE
QR Scanning and AVCaptureInput

### ISSUE THREAD

**Issue by rsweeten** [BradLarson/GPUImage#2089]
Hi Brad,

This is a question, not really an issue per se, coming from a non-programmer.. bear with me.

I've written an iOS app that scans QR codes using the newish AVCaptureMetadataOutput as an output of AVCaptureSession. I see that GPUVideoCamera utilizes AVCaptureSession (accessible as a property, (thank you)) and adds AVCaptureDeviceInput as an input, however I want to add GPUImageView (filtered video with higher contrast, etc) as an input to CaptureSession to optimize scanning QR codes that may have less than ideal contrast. 

Knowing that AVCaptureSession is expecting an AVCaptureInput, and not a GPUImageView, Is there a way to do this?

For context, these are what we're scanning:
http://dataspacetime.com/qr/

Best, 
Ray

**Comment by BradLarson** [comment]
Unfortunately, no, I don't think so. People have asked about this before, but I believe that the QR reading pulls directly from the AV Foundation internals, and so we can't inject our own processed frames into that. 

This may have changed, if any of this has been updated recently, but the last time I looked we couldn't feed processed frames into the barcode recognition process.

**Comment by rsweeten** [comment]
ah.. oh well.. thanks anyway.. this is a really great project! congrats

**Comment by joohae-kim** [comment]
Left a comment for someone who come to here
Vision framework for iOS 11.3+ can be used to solve the problem.

https://developer.apple.com/documentation/vision

The framework allow CGImage to detect, thus we can try detect from RenderView::newTextureAvailable

Thank you Brad for your grate work!
