### ISSUE TITLE
Use GPUImageLuminosity on UIImage

### ISSUE THREAD

**Issue by AaronBratcher** [BradLarson/GPUImage#2091]
I'm trying to get the luminosity of a UIImage. How do I set a completionBlock? It seems my imageFilter doesn't have the setLuminosityProcessingFinishedBlock method.

// check luminosity is high enough
let picture = GPUImagePicture(image: image)
let imageFilter = GPUImageLuminosity()
picture.addTarget(imageFilter)

**Comment by BradLarson** [comment]
You set a luminosity completion block in Swift using something like the following:

    luminosityOperation.luminosityProcessingFinishedBlock = {(luminosity, time) in
        // Do your work here
    } 

Do that before you add this as a target of your image and you should be fine.

**Comment by tattle** [comment]
I tried to above block with luck in getting the luminosity in filter class: GPUImageLuminosity in swift...
