### ISSUE TITLE
get contours from Sobel Edge detection filter

### ISSUE THREAD

**Issue by codeOfRobin** [BradLarson/GPUImage#2094]
The OpenCV framework returns the contours edges from Canny/Sobel edge detection, after which contour areas can be calculated. Any way we can do this on GPUImage?

**Comment by BradLarson** [comment]
Not at present. This isn't an operation that's easily replicated on the GPU, so your best bet might be to feed the output from GPUImage's Canny or Sobel edge detection into a contour determination operation outside of the framework.
