### ISSUE TITLE
Could not record the video in samples/iOS/SimpleVideoFilter 

### ISSUE THREAD

**Issue by chenkaiwei** [BradLarson/GPUImage#2097]
Hello
    I've tried to run the sample 'SimpleVideoFilter ', all the steps is successful,the console could print "Start recording" and "Movie completed". But after that I can not find the video file in my album.
     I have not find any issues about this.  Am I got the incorrect expectation about this function?

thank you

**Comment by BradLarson** [comment]
It records the video within the application's Documents directory. I believe that iTunes file sharing is enabled for this application, so you can find this file within iTunes in the file sharing portion of the application listing for this device. Alternatively, I believe you can get at these files via Xcode.

**Comment by chenkaiwei** [comment]
Thank you Larson. I have found these files follow your guide. By the way, Is there any way to save the video to the album?
