### ISSUE TITLE
Is it possible to record video with red face detection frame?

### ISSUE THREAD

**Issue by Svetusova** [BradLarson/GPUImage#2110]
I need to record video with mustache image on the face. I'm trying to record video with face detection red frame at least. I'm using GPUImageMovieWriter for the recording video and GPUImageVideoCameraDelegate with willOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer to detect faces. How to "connect" them together? Or maybe you know another solution.

Thank you in advance.

**Comment by BradLarson** [comment]
Sure. See the FilterShowcase example application for how to set up a delegate callback for facial recognition in parallel with video processing.

**Comment by Svetusova** [comment]
I've seen it before asking the question. I need recording video with facial recognition and then see red frame on the screen when I play this recording video. 
I've added recording video like in your example SimpleVideoFilter while facial recognition but I don't see red frame after saving this video and then playing it. 
Can you help how to add red frame to recording video session?

**Comment by MSvet** [comment]
If somebody is already interested how to record video with image on it I've found this project that helped me:
https://github.com/malczak/VideoCaptureOverlay

They use GPUImage.

**Comment by muneikh** [comment]
Thanks @BradLarson for such a great Library. I have seen the your sample for face recognition with video processing callback and it helps. However, I am clueless as how can I integrate recording with while the overlay is drawn on the camera preview. It would be great, if you give some pointers to the solution. Thanks in advance. :)

**Comment by Netwolf** [comment]
Im trying to record the face area filtered too.
