### ISSUE TITLE
How to output video with filter applied?

### ISSUE THREAD

**Issue by oliviadangelo** [BradLarson/GPUImage#2112]
I'm trying to output video with a filter. So far the filter shows up on my local camera view but doesn't appear in the video received by my other device.

Here is where I initialize the filter: 
- (void)initializeGPUCamera {
    _videoCamera = [[GPUImageVideoCamera alloc]
                    initWithSessionPreset:AVCaptureSessionPreset640x480
                    cameraPosition:AVCaptureDevicePositionFront];
    _videoCamera.delegate = self;
    _videoCamera.frameRate = MAX_FRAME_RATE;
    _filter = [[GPUImagePixellateFilter alloc] init];
...
    [self startGPUCameraView];
}

- (void)startGPUCameraView {
    [_videoCamera addTarget:_filter];
  
    _imageViewSmall.fillMode = kGPUImageFillModePreserveAspectRatioAndFill;
    _imageViewLarge.fillMode = kGPUImageFillModePreserveAspectRatioAndFill;
    
    [_filter addTarget:_imageViewSmall];
    [_filter addTarget:_imageViewLarge];
  
    [_videoCamera startCameraCapture];
}

- (void)willOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer {
  // ??? how to get sampleBuffer with filter applied
  // ... do something with sampleBuffer...
}

**Comment by BradLarson** [comment]
If you want to get the results of the filter and record them as a movie, use a GPUImageMovieWriter. If you want them as raw data frames use a GPUImageRawDataOutput. The sample buffers you're getting in that delegate callback are those direct from the camera, and will not be filtered. The filter operations occur on the GPU within the framework.
