### ISSUE TITLE
Replacing AVCaptureVideoPreviewLayer

### ISSUE THREAD

**Issue by markNZed** [BradLarson/GPUImage#212]
Hi Brad. The interest in GPUImage is really growing and you are probably inundated with requests for help. Congrats on the success of GPUImage !

The integration of GPUImage went smoothly and we have video running. Your example code made that easy, thanks.

I would like to "drop in" GPUImage to replace the the current video preview layer in a camera app.

prior to GPUImage we grabbed the preview layer with :

AVCaptureVideoPreviewLayer *newCaptureVideoPreviewLayer = [[AVCaptureVideoPreviewLayer alloc] initWithSession:[[self captureManager] session]];

In captureManager, session is an AVCaptureSession (as per AVCam demo from Apple)

We can't have the AVCaptureSession and GPUImageVideoCamera running at the same time. I guess because they both try to access the same resource.

Any advice on the best way to proceed would be much appreciated. It would be too big a job to replace AVCaptureSession completely in the app. Ideally we could hook GPUImageVideoCamera into the AVCaptureVideoPreviewLayer. Is this something that would make sense for the library ?

**Comment by spoti** [comment]
Hi Brad! If I have an AVCaptureSession running how can I add the GPUImageView as the target?

**Comment by saikiranoptisol** [comment]
@BradLarson  can you please answer above question if already we have AVCaptureSession then how we need to add target for GPUImageView, for this i think we need allocation. As i was new to this i was a bit confused how to give allocation of gpuImageView on top of avCaptureSession
