### ISSUE TITLE
Github Releases

### ISSUE THREAD

**Issue by carlossless** [BradLarson/GPUImage#2123]
Thank you for adding carthage support to your wonderful library. Would you consider also adding a binary release for the framework to your GitHub Releases?

**Comment by BradLarson** [comment]
Given the optimizations, etc. that are performed at build time, I don't think providing a binary release of the library makes much sense. I've never needed it for anything I've built, and you have all the source code.

**Comment by carlossless** [comment]
It does speed up dependency retrieval as it doesn't have to rebuild the framework each time on a new environment. However due to Swifts unstable ABI there are some big drawbacks. Nonetheless thank you for considering it.
