### ISSUE TITLE
Can GPU do a faster face detection like GPUImage

### ISSUE THREAD

**Issue by erickingxu** [BradLarson/GPUImage#2129]
Hi,Brad
Thanks for your amazing work !
I read your GPUImage codes about face detection ,which were coded by iOS core image framework.
So I had a question about face detection work? Can I using GPU do similar work for this ?
And give some advice for me ,thanks.

**Comment by BradLarson** [comment]
Possibly, but I've not done any work on this myself. You'd have to do something like finding Haar-like features for facial detection, or one of the other mechanisms for doing this. I've seen some descriptions of GPU-accelerated algorithms for this, but haven't implemented any myself.

It will take a bit of work, and some research, but it can be done. If you get it to work, let me know.
