### ISSUE TITLE
The GPUImage framework requires OpenGL support to work

### ISSUE THREAD

**Issue by mpogra** [BradLarson/GPUImage#2147]
Hello Larson,

I am getting "Unable to create an OpenGL context. The GPUImage framework requires OpenGL support to work" on some of OS X system. Receiving crashes from users sometime and I am not able to figure out cause. I think may be user's graphics card does not support or it's a older system (not sure either). I thought to check if openGL is supported in user's system then only apply the GPU and below is the code i have used to get OpenGL support on system.
```
+ (BOOL) checkIFOpenGLIsSupported {
    NSOpenGLPixelFormatAttribute pixelFormatAttributes[] = {
        NSOpenGLPFADoubleBuffer,
        NSOpenGLPFAAccelerated, 0,
        0
    };
    
    NSOpenGLPixelFormat *pixelFormat = [[NSOpenGLPixelFormat alloc] initWithAttributes:pixelFormatAttributes];
    if (pixelFormat == nil)
    {
        NSLog(@"Error: No appropriate pixel format found");
    }
    // TODO: Take into account the sharegroup
    NSOpenGLContext *context = [[NSOpenGLContext alloc] initWithFormat:pixelFormat shareContext:nil];
    if (context == nil)
        return false;
     else
        return true;
}
```
Please help how can i fix this crash.

Regards,
MP.

**Comment by BradLarson** [comment]
The entire framework is built on OpenGL, so without it the framework is useless. Every Mac that should be able to run this framework should support all OpenGL features used by it. This sounds like some kind of a bug either in the OS or at a driver level. Maybe something's interfering with the OpenGL driver in certain cases.

**Comment by mpogra** [comment]
Thanks Larson for the feedback. This is what I think as well, as far as I know all Mac supports OpenGL so must be a bug in OS or driver level. Thanks.
