### ISSUE TITLE
Why not replacing __unsafe_unretained with __weak?

### ISSUE THREAD

**Issue by tomisacat** [BradLarson/GPUImage#2151]
I use **GPUImageMovie** with other GPUImage classes to filter my video file, It came into crash when I cancel previous filtering and start a new one filtering, I read **GPUImageMovie** source files and find the use of **__unsafe_unretained** make the crash happen
````objc
 __unsafe_unretained GPUImageMovie *weakSelf = self;
````
(https://github.com/BradLarson/GPUImage/blob/master/framework%2FSource%2FGPUImageMovie.m#L264).

And I noticed the use of **__unsafe_unretained** everywhere in GPUImage, I don't know why not use __weak instead?

**Comment by tarikfayad** [comment]
I could be wrong, but I think it's beacuse the library supports deployment to iOS 4. **__weak** only became availible starting in iOS5.

**Comment by BradLarson** [comment]
Yeah, it's to allow backwards compatibility with iOS 4.0 and Snow Leopard. I'm thinking of bumping up the bottom requirements and replacing this across the framework.

**Comment by tomisacat** [comment]
@BradLarson Great decision!
