### ISSUE TITLE
ImageIO Memory-Leak in GPUImagePicture's -initWithCGImage:smoothlyScaleOutput: ?

### ISSUE THREAD

**Issue by UweMeier** [BradLarson/GPUImage#2154]
Hi,

first of: thank you for creating such a humongous framework.

I stumbled across a memory-leak in your GPUImagePicture.m. This doesn't pose much of a problem, if you're just using GPUImagePicture rarely. But since I'm working with GIF's, I have to create rather many GPUImagePictures and this leak leads to low memory warnings and crashes.

This line
```
CGContextDrawImage(imageContext, CGRectMake(0.0, 0.0, pixelSizeToUseForTexture.width, pixelSizeToUseForTexture.height), newImageSource);
```
in 
```
- (id)initWithCGImage:(CGImageRef)newImageSource smoothlyScaleOutput:(BOOL)smoothlyScaleOutput;
```

Causes the leak. At least, that's where I backtraced it to with Instruments.

The strange thing is though, that it does not occur all the time.

**Comment by UweMeier** [comment]
Ok,
found out, that this is - more or less - intended behaviour.
I forced the framework to hold too many GPUImagePictures in its buffer, causing the high memory consumption.

**Comment by ChenZeBin** [comment]
I hava a same problem，excuse me，how did you solve it
