### ISSUE TITLE
How to get result in YUV format?

### ISSUE THREAD

**Issue by takecian** [BradLarson/GPUImage#2158]
Hi, I'd like to get video with YUV format after processing video.
Currently the format of CVPixelBuffer in GPUImageWriter:newFrameReadyAtTime is BGRA.
Is possible to add a custom filter which convert YUV from BGRA in filter chain?

Regards,
takecian.

**Comment by takecian** [comment]
resolved, close

**Comment by larrytin** [comment]
How do you do it?

**Comment by erickingxu** [comment]
@takecian ,you should tell your solution before you closed it.
And a method for @larrytin ,you can located a memory for loading lum and chm texture2d from gnu.
thx, enjoy it.

**Comment by takecian** [comment]
@erickingxu , @larrytin  I gave up creating custom filter, as i'm new to OpenGL, it was difficult.
I got YUV from BGRA using libyuv in GPUImageMovieWriter.
I think it is not good solution from point of performance perspective.

**Comment by takecian** [comment]
@larrytin it might help, https://github.com/takecian/gpuimagetokbox/blob/master/gpuimagetokbox/VideoGenerator.m

**Comment by erickingxu** [comment]
@takecian ,maybe it is one method with libyuv, but it doesn't fast and good enough when it works on a high frame rate.   Some method could be useful with Opengles3.0 in Multiple render target to restore y,uv (yuv420)planar respectly. But in 2.0, it may be complex .
So, anyone can provide some advice or information for this , and I will focus on it.

**Comment by graynoel** [comment]
Hi @erickingxu, is there any updates on this topic?

**Comment by xdf103** [comment]
@erickingxu is there any example for using OpenGL ES 3.0 multiple render target to output yuv?
