### ISSUE TITLE
Recording Video with AVCaptureSessionPresetPhoto is mute

### ISSUE THREAD

**Issue by stapleup** [BradLarson/GPUImage#2163]
Hi there, I am working on a mobile application where I need to record square video, I have read about several libraries but GPUImage appears to be the best option to do so, I was playing with the SimpleVideoFilter sample when I noticed that the camera preview it shows is much zoomed as compared to Instagram and Vine, I tried almost all the presets but it would still show it as zoomed, the only way to fix the zoom appears to be if I set the preset to AVCaptureSessionPresetPhoto, that fixed the zoom issue but now when I record video it has no audio, the code is same as the sample, with only preset changed.

Any help in resolving this issue would be appreciated.

**Comment by BradLarson** [comment]
Don't use the photo preset for recording video. The video feed in that preset only provides a preview of the camera feed. Use one of the video presets instead, if you want to capture video with audio.

**Comment by stapleup** [comment]
Hi Brad, thanks for your reply, but can you please guide me regarding the zoom issue I mentioned, It would really help me and others having such problem.

**Comment by BradLarson** [comment]
What do you mean by "zoomed"? The sample application fits the feed from the video camera to the size of the preview view, preserving aspect ratio. If you want to carve out a square portion of that, you can use a crop filter to extract a portion of the video, which may achieve the look you want.

The framework doesn't really dictate what comes in, that's all from AV Foundation and the various camera options you can set there via the exposed camera input.

**Comment by stapleup** [comment]
Hi Brad, please look at the attached image, the one taken by Instagram has wider viewing angle, while the one from GPUImage has smaller, I am not saying that it is a bug in library (the view on native camera app is also zoomed), I am just trying to understand what Instagram  is doing here.
![photo 1](https://cloud.githubusercontent.com/assets/778245/11980683/7e8f04c6-a9be-11e5-826b-b63cf6656fba.PNG) ![photo 2](https://cloud.githubusercontent.com/assets/778245/11980696/8db96900-a9be-11e5-90d6-690004bac018.PNG)

**Comment by masroorelahi** [comment]
Hi I am facing the same issue please give your feedback on that

**Comment by mingyue1991** [comment]
Hi I am facing the same issue,headache, any good solution

**Comment by masroorelahi** [comment]
Hi mingyue !
When we are capturing video using this preset then video is muted because this preset is only for capturing photos due to which it will not use your audio session. Below is the documentation for the required preset provided by Apple

Clients may set an AVCaptureSession instance's sessionPreset to AVCaptureSessionPresetPhoto for full resolution photo quality output.

**Comment by mingyue1991** [comment]
@masroorelahi  thank ! i find out that then, and revoked that to `AVCaptureSessionPresetHigh`, because `AVCaptureSessionPresetPhoto ` can get larger zone when preview is square. but now, we will merge camera and video , as a result , we can't use sessionPressetPhoto now.
