### ISSUE TITLE
Based GPUImage, custom particle filter, using VBO (Vertex Buffer Object) to pass parameters, but get invalid parameters Shader

### ISSUE THREAD

**Issue by jiewuxiaozi2009** [BradLarson/GPUImage#2164]
Here is the filter code：

[GPUImageParticlerFilter.zip](https://github.com/BradLarson/GPUImage/files/75453/GPUImageParticlerFilter.zip)

The main problem: the particle position error.VBO passed to the "Vertex Shader" parameters "aTheta" error.In GPUImage can "[filters Program attributeIndex: @" aTheta "];" add "attribute" it?In the above code using "[filter Program attributeIndex: @" aTheta "]" add "attribute" seems to have no effect.

Custom filters reference “http://www.raywenderlich.com/37600/opengl-es-particle-system-tutorial-part-1”

**Comment by erickingxu** [comment]
Hi @jiewuxiaozi2009 , how to resolve this problem? 
I try using VBO in GPUImage but it seems not work.
Please give some advice.
Thanks from EK

**Comment by StromanStroman** [comment]
You did not add the attribute
