### ISSUE TITLE
My App crach and log the error below this question...

### ISSUE THREAD

**Issue by EZElkins** [BradLarson/GPUImage#2172]
Assertion failure in -[GPUImageFramebuffer unlock]
NSAssert(framebufferReferenceCount > 0, @"Tried to overrelease a framebuffer, did you forget to call -useNextFrameForImageCapture before using -imageFromCurrentFramebuffer?");

How can I resolve it?

**Comment by nkwsqyyzx** [comment]
@BradLarson ,why close this issue without any explain? Is there any related question should i have a look?
