### ISSUE TITLE
Change brightness, contrast and saturation using sliders

### ISSUE THREAD

**Issue by cacdzya** [BradLarson/GPUImage#2184]
Hi. I'm trying to change brightness, contrast and saturation together to implement using sliders; the code works for me in some images, but in other my app crashes. I hope you can help me. Here I leave my code:

- (IBAction)sliderValueChangedBrillo:(id)sender {
    
    GPUImagePicture *stillImageSource = [[GPUImagePicture alloc] initWithImage:copiaViewImagen.image];
    
    GPUImageBrightnessFilter *filtroBrillo = [[GPUImageBrightnessFilter alloc] init];
    GPUImageContrastFilter *filtroContraste = [[GPUImageContrastFilter alloc] init];
    GPUImageSaturationFilter *filtroSaturacion = [[GPUImageSaturationFilter alloc] init];
    
    [filtroBrillo setBrightness:_slider_brillo.value];
    [filtroContraste setContrast:_slider_contraste.value];
    [filtroSaturacion setSaturation:_slider_saturacion.value];
    
    [filtroBrillo forceProcessingAtSize:copiaViewImagen.image.size];
    [filtroContraste forceProcessingAtSize:copiaViewImagen.image.size];
    [filtroSaturacion forceProcessingAtSize:copiaViewImagen.image.size];
    
    [stillImageSource addTarget:filtroBrillo];
    [filtroBrillo addTarget:filtroContraste];
    [filtroContraste addTarget:filtroSaturacion];
    
    [filtroSaturacion useNextFrameForImageCapture];
    
    [stillImageSource processImage];

    UIImage *nearestNeighborImage = [filtroSaturacion imageFromCurrentFramebufferWithOrientation:viewImagenSeleccionada.image.imageOrientation];
    
    viewImagenSeleccionada.image = nearestNeighborImage;
    
    _boton_restaurar_foto.userInteractionEnabled = YES;
}

- (IBAction)sliderValueChangedContraste:(id)sender {
    
    GPUImagePicture *stillImageSource = [[GPUImagePicture alloc] initWithImage:copiaViewImagen.image];
    
    GPUImageBrightnessFilter *filtroBrillo = [[GPUImageBrightnessFilter alloc] init];
    GPUImageContrastFilter *filtroContraste = [[GPUImageContrastFilter alloc] init];
    GPUImageSaturationFilter *filtroSaturacion = [[GPUImageSaturationFilter alloc] init];
    
    [filtroBrillo setBrightness:_slider_brillo.value];
    [filtroContraste setContrast:_slider_contraste.value];
    [filtroSaturacion setSaturation:_slider_saturacion.value];
    
    [filtroBrillo forceProcessingAtSize:copiaViewImagen.image.size];
    [filtroContraste forceProcessingAtSize:copiaViewImagen.image.size];
    [filtroSaturacion forceProcessingAtSize:copiaViewImagen.image.size];
    
    [stillImageSource addTarget:filtroBrillo];
    [filtroBrillo addTarget:filtroContraste];
    [filtroContraste addTarget:filtroSaturacion];
    
    [filtroSaturacion useNextFrameForImageCapture];
    
    [stillImageSource processImage];
    
    UIImage *nearestNeighborImage = [filtroSaturacion imageFromCurrentFramebufferWithOrientation:viewImagenSeleccionada.image.imageOrientation];
    
    viewImagenSeleccionada.image = nearestNeighborImage;
    
    _boton_restaurar_foto.userInteractionEnabled = YES;
}

- (IBAction)sliderValueChangedSaturacion:(id)sender {
    
    GPUImagePicture *stillImageSource = [[GPUImagePicture alloc] initWithImage:copiaViewImagen.image];
    
    GPUImageBrightnessFilter *filtroBrillo = [[GPUImageBrightnessFilter alloc] init];
    GPUImageContrastFilter *filtroContraste = [[GPUImageContrastFilter alloc] init];
    GPUImageSaturationFilter *filtroSaturacion = [[GPUImageSaturationFilter alloc] init];
    
    [filtroBrillo setBrightness:_slider_brillo.value];
    [filtroContraste setContrast:_slider_contraste.value];
    [filtroSaturacion setSaturation:_slider_saturacion.value];
    
    [filtroBrillo forceProcessingAtSize:copiaViewImagen.image.size];
    [filtroContraste forceProcessingAtSize:copiaViewImagen.image.size];
    [filtroSaturacion forceProcessingAtSize:copiaViewImagen.image.size];
    
    [stillImageSource addTarget:filtroBrillo];
    [filtroBrillo addTarget:filtroContraste];
    [filtroContraste addTarget:filtroSaturacion];
    
    [filtroSaturacion useNextFrameForImageCapture];
    
    [stillImageSource processImage];
    
    UIImage *nearestNeighborImage = [filtroSaturacion imageFromCurrentFramebufferWithOrientation:viewImagenSeleccionada.image.imageOrientation];
    
    viewImagenSeleccionada.image = nearestNeighborImage;
    
    _boton_restaurar_foto.userInteractionEnabled = YES;
}

**Comment by BradLarson** [comment]
You really don't want to recreate your image every time you move a slider. Create it once, attach it to the filters, and have it output to a GPUImageView, not a UIImageView. On movement of the sliders, trigger a refresh of the pipeline starting at the source image.

You're probably running into memory-related issues by rapidly creating and destroying a ton of images here, and that's a horribly slow process. Creating an image once and updating the pipeline on the fly will give you hugely improved performance and reduced memory usage.

**Comment by cacdzya** [comment]
How can I do this step: On movement of the sliders, trigger a refresh of the pipeline starting at the source image. I am very new in GPUImage and I am learning how to implement in my project. When I applied this part of the code: 

[filtroSaturacion useNextFrameForImageCapture];
[stillImageSource processImage];

The app crash. Thanks four your help :).
