### ISSUE TITLE
GPUImage can using OpenGL OES for speed up texture produceing?

### ISSUE THREAD

**Issue by erickingxu** [BradLarson/GPUImage#2194]
Hi @BradLarson ,

I know android support OpenGL extension for using OES function to produce texture and export OpenGL data much faster.
So Apple OpenGL es can support it ?
Thanks from EK.

**Comment by BradLarson** [comment]
I'm not sure what you're asking. There isn't anything called an "OES function". There are -OES extensions appended to certain OpenGL ES functions and constants, but those are standard functions.

The framework already uses texture caches for fast uploading of incoming camera frames, as well as capture for movies, raw data, and still images on the way out.
