### ISSUE TITLE
VideoFilter from Device Video

### ISSUE THREAD

**Issue by pothirajp** [BradLarson/GPUImage#2196]
Hi Mr.Brad Larson , i want to integrate the video filter in my Application Using GPUimage, Can you give some suggestion how to to use. (Already Recorded video)

**Comment by AirLong** [comment]
CGImageRef img = [pipeline newCGImageFromCurrentFilteredFrame];
            if(img)
            {
//                UIImageWriteToSavedPhotosAlbum(img, self,nil, nil);
                NSLog(@"YES");
            }
            
            [self.imageCamera capturePhotoAsImageProcessedUpToFilter:self.filtersGroup withCompletionHandler:^(UIImage *processedImage, NSError *error) {
                if (processedImage)
                {
                    UIImageWriteToSavedPhotosAlbum(processedImage, nil, nil, nil);
                    NSLog(@"image = %@",processedImage);
                }
            }];

img is null,processedImage is null,why is that? what can I do? please tell me what to do, thank you very very very much!
