### ISSUE TITLE
capturePhotoAsJPEGProcessedUpToFilter and capturePhotoAsImageProcessedUpToFilter crash with Memory warning Only on iPhone 6+

### ISSUE THREAD

**Issue by cmavromoustakos** [BradLarson/GPUImage#2198]
Hello we have an app which is trying to take a square photo and using this for the capture code:

    override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)
        
        stillCamera.outputImageOrientation = .Portrait
        stillCamera.addTarget(filter)
        filter.addTarget(cameraView)
        stillCamera.startCameraCapture()
    }
    
    override func viewDidDisappear(animated: Bool) {
        filter.removeAllTargets()
        stillCamera.stopCameraCapture()
        stillCamera.removeAllTargets()
    }

    func didPressShutterButton(sender: UIButton) {
        sender.enabled = false
        filter.forceProcessingAtSizeRespectingAspectRatio(CGSizeMake(600, 600))
        
        stillCamera.capturePhotoAsImageProcessedUpToFilter(filter) { (capturedImage, error) -> Void in
            print("cap size: \(capturedImage.size)")
            guard let _ = capturedImage else {
                return
            }
            self.transitionOut()
            self.delegate?.didTakeMomentPhoto(capturedImage)
        }
    }

What we are seeing is that the application is receiving a memory warning and crashing right after the call to stillCamera.capturePhotoAsImageProcessedUpToFilter sometimes after the first time but it can take up to X times to crash in most cases. 

We thought it might have been a memory leak  associated with our self.delegate?.didTakeMomentPhoto(capturedImage) so we commented out all of the code inside the block and still saw the same behavior. 

We have tested with all phones (iPhone 5 and newer) but this only seems to happen on the 6+.

To make the matter worse we are not seeing anything in the logs Xcode or device, and instruments does not seem to be reporting any substantial memory leaks.

**Comment by 0x6368** [comment]
I have the exact same issue on my iPhone 6 Plus. Did you find a way to resolve this issue, @cmavromoustakos?
