### ISSUE TITLE
How to concat two image 

### ISSUE THREAD

**Issue by fayhot** [BradLarson/GPUImage#2209]
All the blend filters are used to deal with the images compose one by one. 

Is there any way to compose two image side by side ?

I'd like to do something like snapchat, which can swipe through filters.

**Comment by sinbadflyce** [comment]
Hi all,

I’m using GPUImageView to apply the filters to play video, but there is no animation when I change the aspect ratio video. Example:

gpuImageView.fillMode = kGPUImageFillModePreserveAspectRatio;

I’d like GPUImageView works same AVPlayerLayer. Example:

avPlayerLayer.videoGravity = AVLayerVideoGravityResizeAspect

I get stuck about solution to make this work, any help from you?

**Comment by fayhot** [comment]
I did it with a trick.
