### ISSUE TITLE
How to apply three color on GPUImage

### ISSUE THREAD

**Issue by sathiya1926** [BradLarson/GPUImage#2215]
Hi,

I want to apply three color on top of black and white texture and blend it on base image.

One base coat color, two top coat color. 

Can anyone help me how to achieve this?

Regards
sathiya

**Comment by BradLarson** [comment]
I have no idea what you're asking here.

**Comment by sathiya1926** [comment]
I want to apply three  color on one image.  Like in GPUImageFalseColorFilter we are applied two color firstColor and secondColor . Is there any to add thirdColor as well.
