### ISSUE TITLE
Very low quality when forceProcessingAtSize

### ISSUE THREAD

**Issue by fhdns** [BradLarson/GPUImage#2219]
Hi.

I compared the results of the resize using ImageMagic and using forcedResize:

[original image [3782 × 2592]](http://s14.postimg.org/sk48h832n/01_original.jpg)
[image after resizing by ImageMagic [437 × 300]](http://s14.postimg.org/y5qnla3rl/01_imagemagick.jpg)

but when I tried forceProcessingAtSize:

```
GPUImageFilter* filter = [[GPUImageFilter alloc] init];
[*filter forceProcessingAtSize:size];
CGImageRef output = [filter newCGImageByFilteringCGImage:inputImage];
```
result is very bad:

[image after resizing by GPUImage [437 × 300]](http://s14.postimg.org/42c4tc0i9/01_gpu.png)

How to fix it?

**Comment by BradLarson** [comment]
The difference between the two is that by simply forcing the resizing of the image, GPUImage will use nearest-neighbor sampling, leading to jagged edges. ImageMagic is using doing more with their downsampling.

To get better downsampling, use the Lanczos resampling filter and have that reduce the size of your image. For an example of what that means for image quality, take a look at this comparison:

http://stackoverflow.com/questions/14366672/how-can-i-improve-this-webgl-glsl-image-downsampling-shader/14368131#14368131
