### ISSUE TITLE
GPUImageRawDataOutput with Swift

### ISSUE THREAD

**Issue by Delarue** [BradLarson/GPUImage#2226]
I am trying to get the color of a cgpoint within a GPUImageView in swift. I read that we could use GPUImageRawDataOutput to achieve this. How could I go about doing this?

**Comment by BradLarson** [comment]
A GPUImageRawDataOutput will give you the raw bytes of whatever stage you attach it as a target of. Set it as a target of the stage right before your view, and set the newFrameAvailableBlock to get a callback whenever a new image is available. You can then access the rawBytesForImage to grab whatever bytes you want from the processed image.

This is used in the ColorObjectTracking example to do just what you describe.
