### ISSUE TITLE
How to add an image input to the 2nd stage (vertex and fragment) shaders of GPUImageTwoPassFilter?

### ISSUE THREAD

**Issue by magicboker** [BradLarson/GPUImage#2233]
How to add an image to the 2nd stage shaders in GPUImageGaussianBlurFilter, which is a GPUImageTwoPassTextureSamplingFilter?
I need modify the 2nd phase of separable gaussian blur formula to do some kind of algorithm adjustment.
Does anyone know how to subclass GPUImageGaussianBlurFilter to add a input image (like GPUImageTwoInputFilter) to the 2nd stage shaders?

**Comment by BradLarson** [comment]
There isn't really a way to do this right now. A two-pass filter like this is currently constructed in such a way that only the inputs to the first pass and outputs from the second pass are exposed to elements of the pipeline outside of the class.

You'll need to rework the structure of the -renderToTextureWithVertices:textureCoordinates: method to insert a texture from a second input in the second stage of the rendering. That might take a little work.
