### ISSUE TITLE
GPUImage to make text black and background white!

### ISSUE THREAD

**Issue by Vnunev** [BradLarson/GPUImage#2235]
Hello everyone,

I am building an app that takes pictures from the Camera of the iPhone and then process the image with tesseract to display the text in the textview. How can i process the image such as the text(even if its coloured) gets black and make the background white with GPUImage?

P.S. I am building the application in swift and is hard to find good recourses on swift for GPUImage.

**Comment by BradLarson** [comment]
It's common to use an adaptive threshold filter for this, where everything darker than the immediate background ends up being black. A simple threshold could also work, depending on your illumination conditions.

**Comment by Vnunev** [comment]
Thank you Brad, 

However, when i am taking picture of coloured text it ends up putting it white and the tesseract is not recognizing anything. Do you have any solution for this ?

**Comment by garnele007** [comment]
I'm using this function to process an image for tesseract. For me it is working way better than an adaptive threshold filter. The only problem I have is, it sometimes get stuck in the while loop.

`func processImage(inputImage: UIImage) -> UIImage { 
        
        var processedImage = inputImage

        let image = GPUImagePicture(image: processedImage)
        let image2 = GPUImagePicture(image: processedImage)
        
        //Img 1
        
        let grayFilter = GPUImageGrayscaleFilter()
        image.addTarget(grayFilter)
        
        let invertFilter = GPUImageColorInvertFilter()
        grayFilter.addTarget(invertFilter)
        
        let blurFilter = GPUImageGaussianBlurFilter()
        blurFilter.blurRadiusInPixels = 10
        invertFilter.addTarget(blurFilter)
        
        let opacityFilter = GPUImageOpacityFilter()
        opacityFilter.opacity = 0.93
        blurFilter.addTarget(opacityFilter)
        
        opacityFilter.useNextFrameForImageCapture()
        
        //Img 2
        
        let grayFilter2 = GPUImageGrayscaleFilter()
        image2.addTarget(grayFilter2)
        
        grayFilter2.useNextFrameForImageCapture()
        
        //Blend
        
        let dodgeBlendFilter = GPUImageColorDodgeBlendFilter()
        
        grayFilter2.addTarget(dodgeBlendFilter)
        image2.processImage()
        
        opacityFilter.addTarget(dodgeBlendFilter)
        image.processImage()
        
        dodgeBlendFilter.useNextFrameForImageCapture()
        
        //Img 3
        
        var dodgeBlendImage:UIImage? = dodgeBlendFilter.imageFromCurrentFramebufferWithOrientation(UIImageOrientation.Up)
        
        while dodgeBlendImage == nil {
Sometimes it gets stuck here
            dodgeBlendImage = dodgeBlendFilter.imageFromCurrentFramebufferWithOrientation(UIImageOrientation.Up)
        }
        
        if let dodgeImage = dodgeBlendImage {
            
            let image3 = GPUImagePicture(image: dodgeImage)
            
            let levelFilter = GPUImageLevelsFilter()
            levelFilter.setMin(90/255, gamma: 0.8, max: 215/255, minOut: 0, maxOut: 1)
            image3.addTarget(levelFilter)
            
            let medianFilter = GPUImageMedianFilter()
            levelFilter.addTarget(medianFilter)
            
            let erosionFilter = GPUImageErosionFilter()
            medianFilter.addTarget(erosionFilter)
            
            let thresholdFilter = GPUImageLuminanceThresholdFilter()
            thresholdFilter.threshold = 220/255
            erosionFilter.addTarget(thresholdFilter)
            
            thresholdFilter.useNextFrameForImageCapture()
            
            image3.processImage()
            let processedImage = thresholdFilter.imageFromCurrentFramebufferWithOrientation(UIImageOrientation.Up)
            
            return processedImage
        } else {
            NSLog("WARNING: DodgeImage image is to small","")
            return processedImage
        }
        
        
    }`

**Comment by vietnguyen09** [comment]
> I'm using this function to process an image for tesseract. For me it is working way better than an adaptive threshold filter. The only problem I have is, it sometimes get stuck in the while loop.
> 
> ```
> func processImage(inputImage: UIImage) -> UIImage { 
> 
>     var processedImage = inputImage
> 
>     let image = GPUImagePicture(image: processedImage)
>     let image2 = GPUImagePicture(image: processedImage)
> 
>     //Img 1
> 
>     let grayFilter = GPUImageGrayscaleFilter()
>     image.addTarget(grayFilter)
> 
>     let invertFilter = GPUImageColorInvertFilter()
>     grayFilter.addTarget(invertFilter)
> 
>     let blurFilter = GPUImageGaussianBlurFilter()
>     blurFilter.blurRadiusInPixels = 10
>     invertFilter.addTarget(blurFilter)
> 
>     let opacityFilter = GPUImageOpacityFilter()
>     opacityFilter.opacity = 0.93
>     blurFilter.addTarget(opacityFilter)
> 
>     opacityFilter.useNextFrameForImageCapture()
> 
>     //Img 2
> 
>     let grayFilter2 = GPUImageGrayscaleFilter()
>     image2.addTarget(grayFilter2)
> 
>     grayFilter2.useNextFrameForImageCapture()
> 
>     //Blend
> 
>     let dodgeBlendFilter = GPUImageColorDodgeBlendFilter()
> 
>     grayFilter2.addTarget(dodgeBlendFilter)
>     image2.processImage()
> 
>     opacityFilter.addTarget(dodgeBlendFilter)
>     image.processImage()
> 
>     dodgeBlendFilter.useNextFrameForImageCapture()
> 
>     //Img 3
> 
>     var dodgeBlendImage:UIImage? = dodgeBlendFilter.imageFromCurrentFramebufferWithOrientation(UIImageOrientation.Up)
> 
>     while dodgeBlendImage == nil {
>     //Sometimes it gets stuck here
>         dodgeBlendImage = dodgeBlendFilter.imageFromCurrentFramebufferWithOrientation(UIImageOrientation.Up)
>     }
> 
>     if let dodgeImage = dodgeBlendImage {
> 
>         let image3 = GPUImagePicture(image: dodgeImage)
> 
>         let levelFilter = GPUImageLevelsFilter()
>         levelFilter.setMin(90/255, gamma: 0.8, max: 215/255, minOut: 0, maxOut: 1)
>         image3.addTarget(levelFilter)
> 
>         let medianFilter = GPUImageMedianFilter()
>         levelFilter.addTarget(medianFilter)
> 
>         let erosionFilter = GPUImageErosionFilter()
>         medianFilter.addTarget(erosionFilter)
> 
>         let thresholdFilter = GPUImageLuminanceThresholdFilter()
>         thresholdFilter.threshold = 220/255
>         erosionFilter.addTarget(thresholdFilter)
> 
>         thresholdFilter.useNextFrameForImageCapture()
> 
>         image3.processImage()
>         let processedImage = thresholdFilter.imageFromCurrentFramebufferWithOrientation(UIImageOrientation.Up)
> 
>         return processedImage
>     } else {
>         NSLog("WARNING: DodgeImage image is to small","")
>         return processedImage
>     }
> 
> 
> }
> ```

Thanks for your solution, do you have any improvement?
