### ISSUE TITLE
GPUImageSolarizeFilter.h is marked as a "public" header

### ISSUE THREAD

**Issue by alexkeim** [BradLarson/GPUImage#2251]
I think this header should be private. Right?

Turns out that this, in combination with the fact that "Public headers folder path" is set to /usr/local/include, causes the build archive to archive the app as a generic archive (appears in "Other Items") rather than archiving as an iOS App.

**Comment by BradLarson** [comment]
Thanks for pointing this out. I've corrected it in the latest commit.
