### ISSUE TITLE
Use of undeclared type 'GPUImageSolarizeFilter'

### ISSUE THREAD

**Issue by terenzeyuen** [BradLarson/GPUImage#2263]
Hm, tried the examples but getting this error?
![screen shot 2016-04-20 at 21 12 10](https://cloud.githubusercontent.com/assets/2553680/14688873/a61bdc5e-073c-11e6-8f3c-961c03cea953.png)

**Comment by BradLarson** [comment]
Oops, looks like that was left out of the iOS side's main header. That's been added in the latest commit.

**Comment by terenzeyuen** [comment]
Ace. I don't know if I can ask this here but can we animate the filters for image? Like grayscale?

**Comment by BradLarson** [comment]
You could rapidly change a filter's property as it was processing frames, following an animation curve. There isn't anything built-in for that, but I've seen people using timing schemes to trigger these updates.

**Comment by terenzeyuen** [comment]
Ok thanks,

**Comment by chinapq** [comment]
����������������������?
