### ISSUE TITLE
Suggestion: rename all Filter classes from GPUImage<filter_name>Filter to GPUImageFilter<filter_name>

### ISSUE THREAD

**Issue by evfemist** [BradLarson/GPUImage#2265]
Instead of having GPUImageSepiaFilter I propose rename to GPUImageFilterSepia
GPUImagePixellatePositionFilter to GPUImageFilterPixellatePosition
...

so it will be easier to find correct filter.

**Comment by BradLarson** [comment]
I don't think this would really help, and it doesn't read right to me. It also would break all projects that target this version of the framework without providing meaningful gain.

If naming is a concern, I suggest eventually moving over to the GPUImage 2 project, where the names have been dramatically simplified.
