### ISSUE TITLE
Just find 6s don't support  GPUImageVideoCamera setFrameRate:2

### ISSUE THREAD

**Issue by Thetiso** [BradLarson/GPUImage#2270]
well   6 & 6p support rate = 2
rate = 3 works good on 6 & 6s

**Comment by BradLarson** [comment]
Not sure what I'm supposed to do about that.

**Comment by Thetiso** [comment]
I just don't know why 6s don't support rate = 2.
As in my app, i support rate = 2/5/10/15/30 for all devices; but finally find only rate = 2 crash on 6s. 
device problem?

**Comment by Thetiso** [comment]
well  6 = iphone 6, 6s = iphone 6s, 6p = iphone 6plus
