### ISSUE TITLE
How to feed buffer to GPUImageFilter and produce filtered buffer instead of use GPUImageVideoCamera

### ISSUE THREAD

**Issue by ruandao** [BradLarson/GPUImage#2271]
I am use a third framework, and it has a delegate method, which fill in `sampleBuffer`
and i need process it and return the filtered  buffer
`
- (CMSampleBufferRef)cameraSource:(PLCameraSource *)source didGetSampleBuffer:(CMSampleBufferRef)sampleBuffer;
`

so how can i use GPUImageFilter in this method instead of  direct use GPUImageVideoCamera

**Comment by BradLarson** [comment]
There currently is no way to do this in the framework, sorry.

**Comment by GeekZP** [comment]
hello ，The problem you solved?

How to user gpuimage add a filter to independent video frames？

My project video frames from a third party in the SDK，sdk gave a callback to get sampleBuffer,so i want use gpuimage add a filter to buffer ，Can realize? If you can, can help me？ thank you！

my email 1397819210@qq.com
