### ISSUE TITLE
 [self setOutputFBO]; require new replacement . 

### ISSUE THREAD

**Issue by humza-ios** [BradLarson/GPUImage#2282]
Below one is my old version code , i need to update with new Version of GPUimage Libaray : 

-(GLubyte*) rawPixels {
	[GPUImageOpenGLESContext useImageProcessingContext];  // (**Required new replacement if this  
    [self setOutputFBO]; // ( Required new replacement if this  )**
	CGSize currentFBOSize = [self sizeOfFBO];
    GLubyte *pixels;

	if ([GPUImageOpenGLESContext supportsFastTextureUpload] && preparedToCaptureImage) {
        glFlush();
        CFRetain(renderTarget); in new version it give nil  // ( Required new replacement if this  )
 // I need to retain the pixel buffer here and release in the data source callback to prevent its bytes from being prematurely deallocated during a photo write operation
        CVPixelBufferLockBaseAddress(renderTarget, 0);
        pixels = (GLubyte *)CVPixelBufferGetBaseAddress(renderTarget);
    }
	else {
		NSUInteger totalBytesForImage = (int)currentFBOSize.width * (int)currentFBOSize.height * 4;
        pixels = (GLubyte *)malloc(totalBytesForImage);
    }
	
	return pixels;
}

Can anyone give help for figure out this issue .

**Comment by BradLarson** [comment]
What exactly are you trying to do? What is the context of this code?

If you just want to grab pixel data, use a GPUImageRawDataOutput, which is what the above code looks to be copied from.

**Comment by humza-ios** [comment]
My current class is extend From GPUimageFilter(Parent class)  (previously [self setoutputFBO] ) is already in GPuimageFilter , now i need to call [self setoutputFBO] . 

I am confuse on should i use GPUuimageMovieWrite for this [moviewriterobject  setFilterFBO]? 
OR  GPUImageRawDataOutput is any function there ?

**Comment by BradLarson** [comment]
None of this needs to be overwritten within a GPUImageFilter. Look at all the filter subclasses in the framework, and you'll find that this code isn't necessary.

If you want to record a movie, just use a movie writer and don't worry about grabbing the raw pixels.

**Comment by humza-ios** [comment]
Actually i need pixels from Capture movies , i need to use these pixels in
any other view .
