### ISSUE TITLE
How to use fingers to move the GPUImageUIElement?

### ISSUE THREAD

**Issue by jirex** [BradLarson/GPUImage#2292]
I am using GPUImage to make a camera app, and I add a GPUImageUIElement to the filter, but I think the GPUImageUIElement was only rendered to the view, it wasn't become the subview of the view. I want to use fingers to move the element, but the userinteraction can't get the element, how can I move the element?

**Comment by BradLarson** [comment]
My recommendation would be to apply a transform / scale operation on it before passing it into your blend, and have the transformation track finger position.
