### ISSUE TITLE
how to get original screen coordinates of pixel when adapting histogram filter

### ISSUE THREAD

**Issue by kallipigous** [BradLarson/GPUImage#2298]
I'm trying to adapt the histogram filter so that it create a video waveform. Essentially the x of the original pixel stays the same but the Y is dictated by the luminance of the pixel. The obvious place to start was the histogram filter but it looks like the pipeline no longer has the position data (the vertex shader position seems to have the  rgb values instead and are used to calculate the luminance). In the histogram filter the x and y are dictated programatically and bear no relation to the original pixel position so presumably it's no longer needed.

Is there a way to get the screen coordinates to change only the Y but keep the original x position of the pixel.

Cheers

Toby

**Comment by BradLarson** [comment]
Given that we discussed this offline and came to a conclusion, I'll close out this particular issue.

**Comment by kallipigous** [comment]
Yes of course.

Many thanks.

.
