### ISSUE TITLE
GPUImage 如何实现加上滤镜的HDR效果

### ISSUE THREAD

**Issue by SeptJY** [BradLarson/GPUImage#2302]
by reference to Apple's demo, achieved using the GPUImage HDR effect, due to the project using a saturation of the filter, in the regulation of the saturation parameter and save the HDR images without filter effects, I should how to obtain the video frame after the combination of filters, and then do processing

**Comment by BradLarson** [comment]
I don't understand what you're asking. You obtain frames as you do after any other kind of filtering in the framework. There's nothing special about saturation adjustment.
