### ISSUE TITLE
Bug exist in GPUImageGaussianBlurFilter?

### ISSUE THREAD

**Issue by Shun87** [BradLarson/GPUImage#2305]
Hello, When I run FilterShowcase demo, I made a change to the  newFrameReadyAtTime function of GPUImageFilter class like this,   change all value in imageVertices from 1.0 to 0.5:
static const GLfloat imageVertices[] = {
        -0.5f, -0.5f,
        0.5f, -0.5f,
        -0.5f,  0.5f,
        0.5f,  0.5f,
    };
The result texture rendered on screen in gaussianBlur demo was 1/4  size of view port, I think it should be 1/2, what's wrong? Other filter  works well, for example gray scale.

**Comment by BradLarson** [comment]
You reduced the range in X and Y from -1.0 - 1.0 to -0.5 - 0.5. That halves the size in both dimensions, leading to an image that is one-quarter the size of the original image.

**Comment by Shun87** [comment]
@BradLarson Sorry, but the result x  or y is only 0.25,  not 0.5, the image is 1/16 the size of the original image. So I think there must be something wrong, you can have a try.
