### ISSUE TITLE
Will you present MetalImage?

### ISSUE THREAD

**Issue by MoozenSoft** [BradLarson/GPUImage#2313]
yeah, just a guess.

**Comment by BradLarson** [comment]
I'm not sure what you're asking. Are you asking if this will be reworked in Metal? If so, that's probably no, for the reasons described here:

https://github.com/BradLarson/GPUImage2/issues/5

**Comment by erickingxu** [comment]
@godshow ,
I think it is a good idea, and some works had been start up in github with MetalImage.
Details ,refer to https://github.com/erickingxu/MetalImage.git

**Comment by MoozenSoft** [comment]
@erickingxu Good job!
