### ISSUE TITLE
Some of Filters classes not available for android

### ISSUE THREAD

**Issue by HBPriyesh** [BradLarson/GPUImage#2325]
GPUImageUnsharpMaskFilter,GPUImageMissEtikateFilter,GPUImageAmatorkaFilter and GPUImageSoftEleganceFilter filter are available in android but available for IOS.Is it possible in android also to create same filter?

**Comment by BradLarson** [comment]
Possibly. I have nothing to do with any Android ports, so you'd have to ask the developers of those.
