### ISSUE TITLE
stillCamera startCameraCapture when no filter

### ISSUE THREAD

**Issue by ashen-23** [BradLarson/GPUImage#2326]
if I don't need filter sometime, what is the parameter 'finalFilterInChain'  in
    "public func capturePhotoAsJPEGProcessedUpToFilter(finalFilterInChain: GPUImageOutput!, withCompletionHandler block: ((NSData!, NSError!) -> Void)!)"
?

thanks a lot

**Comment by BradLarson** [comment]
I don't believe there currently is a way to capture a photo directly from a still photo camera, without any filters, in the original GPUImage. This is a design flaw that I've corrected in GPUImage 2.

You could simply use a passthrough filter, like a brightness filter set to the default value, and capture from that.
