### ISSUE TITLE
crash when it run on ipod (EXC_BAD_ACCESS )

### ISSUE THREAD

**Issue by zhanganl** [BradLarson/GPUImage#2327]
"how i  use:"

{
uint8_t\* temp_bgra = (uint8_t_)malloc(640_480*4);
GPUImageRawDataInput *rawDataInput = [[GPUImageRawDataInput alloc]        initWithBytes:rawDataBytes size:CGSizeMake(width, height) pixelFormat:GPUPixelFormatRGB];  //rawDataBytes are input frame data
    GPUImageRawDataOutput *rawDataOutput = [[GPUImageRawDataOutput alloc] initWithImageSize:CGSizeMake(width, height) resultsInBGRAFormat:YES];

```
[rawDataInput addTarget:rawDataOutput];

__unsafe_unretained GPUImageRawDataOutput * weakOutput = rawDataOutput;
[rawDataOutput setNewFrameAvailableBlock:^{
    [weakOutput lockFramebufferForReading];
    GLubyte *outputBytes = [weakOutput rawBytesForImage];
    for (int yIndex = 0; yIndex < width*height*4; yIndex++)
    {
        temp_bgra[yIndex]=outputBytes[yIndex];
    }
    [weakOutput unlockFramebufferAfterReading];
}];

[rawDataInput processData];
return temp_bgra;
```

}
# **stack:**
- thread #22: tid = 0x3b03, 0x00104aee SoftphoneDemo`___lldb_unnamed_function137$$SoftphoneDemo + 186, queue = 'com.apple.root.default-priority', stop reason = EXC_BAD_ACCESS (code=1, address=0x71dc31a4)
  - frame #0: 0x00104aee SoftphoneDemo`___lldb_unnamed_function137$$SoftphoneDemo + 186
    frame #1: 0x30409eb2 AVFoundation`__74-[AVCaptureVideoDataOutput _AVCaptureVideoDataOutput_VideoDataBecameReady]_block_invoke_0 + 258
    frame #2: 0x3930811e libdispatch.dylib`_dispatch_call_block_and_release + 10
    frame #3: 0x39316258 libdispatch.dylib`_dispatch_root_queue_drain + 260
    frame #4: 0x393163b8 libdispatch.dylib`_dispatch_worker_thread2 + 84
    frame #5: 0x3933ca10 libsystem_c.dylib`_pthread_wqthread + 360
    frame #6: 0x3933c8a4 libsystem_c.dylib`start_wqthread + 8

it run well on other device ,only on ipod has this problem.ios8.3 ipod4

**Comment by BradLarson** [comment]
This is a known bug with the OpenGL driver on iOS 8.3, as described in issue #2041 . For now, you can use this hack:

https://github.com/BradLarson/GPUImage/issues/2041#issuecomment-146909189

**Comment by zhanganl** [comment]
I have read this comment before, and corrected like that. it can run well on iphone4s and iphone 5s(they all run ios 8.3)，only have problem on ipod4(ios8.3).
