### ISSUE TITLE
Add Pixellate effect to part of image instead of making whole image pixellated.

### ISSUE THREAD

**Issue by parthjdabhi** [BradLarson/GPUImage#2329]
How to add Pixellate effect to partial effect ?
i want to add effect in given frame only.

**Comment by BradLarson** [comment]
You could run the filter, mask the portion you want to have filtered, and then blend over the original image. It's not easy, but that's the way to do this.

Or, you could switch to the GPUImage 2 framework, which supports partial image filtering natively in almost every filter.

**Comment by lawicko** [comment]
@BradLarson Could you point me to an example on how the partial image filtering can be used in GPUImage2? I looked through the sources but cannot figure it out.

**Comment by BradLarson** [comment]
@lawicko - The FilterShowcase example application has a few examples of this. The "Masked Pixellate" example does exactly what parthjdabhi describes above:

```
        let circleGenerator = CircleGenerator(size:Size(width:480, height:640))
        filter.mask = circleGenerator
        circleGenerator.renderCircleOfRadius(0.25, center:Position.center, circleColor:Color.white, backgroundColor:Color.transparent)
```

where the `mask` property is an input to every filter that lets you specify an input (image, shape generator, even another filter) to be used as a mask for the filter. Every pixel that is opaque in the mask image will render with the filter in the output, and every pixel that is transparent will use the original unfiltered pixel color.

This unfortunately doesn't work for grouped filters at present, but I'm working on a way to add this for those as well.
