### ISSUE TITLE
Remove filter from .ACV

### ISSUE THREAD

**Issue by sv9988** [BradLarson/GPUImage#2337]
Hi Brad,
I have a question about filter with .acv files.
After I filter a origin image with .acv file, may I remove this filter from filtered image(remove data of acv file from filtered image)
I want to back origin UIimage from filtered UIImage.
Thanks.

**Comment by BradLarson** [comment]
If you just want the original image, you could extract that at an earlier point in the filter pipeline. There shouldn't be a need to undo a filter from it. 

Color conversion operations aren't necessarily reversible, so you may not be able to go back to an original image by applying some kind of inverse filter. Information may have been lost in the initial filtering. Again, just extracting the original image is probably how you want to handle this.
