### ISSUE TITLE
How can i create GPUImageTwoInputFilter with shader string

### ISSUE THREAD

**Issue by masterraj91** [BradLarson/GPUImage#2338]

**Comment by BradLarson** [comment]
Simply create a subclass of GPUImageTwoInputFilter and provide your own shader code. See the many examples in the framework for how to do this.

**Comment by masterraj91** [comment]
can we create GPUImageTwoInputFilter in xamarin.ios with shader string

**Comment by BradLarson** [comment]
I'm sorry, I've never used Xamarin, so I can't answer that. This isn't an issue with the framework, though.

**Comment by masterraj91** [comment]
okay, thanks :)
