### ISSUE TITLE
GPUImageView crash on iOS 8.3(iPhone 5c)

### ISSUE THREAD

**Issue by gaojinhsu** [BradLarson/GPUImage#2350]
it works well on iOS 9+ but crashed on iOS 8,
![60ba555f-0828-429f-8a24-04e123ae73b7](https://cloud.githubusercontent.com/assets/2178687/18045882/b2f5c14c-6e07-11e6-87e4-87c125c655ca.png)
![a38298fa-4996-4047-8d17-1453007a225d](https://cloud.githubusercontent.com/assets/2178687/18045945/08364c26-6e08-11e6-84a3-12c08f2e7971.png)

**Comment by BradLarson** [comment]
This is a known bug with iOS 8.3, which apparently had a broken OpenGL ES interface. See https://github.com/BradLarson/GPUImage/issues/2022#issuecomment-118943746
