### ISSUE TITLE
LUT Problem

### ISSUE THREAD

**Issue by zhouhuirun2015** [BradLarson/GPUImage#2351]
Hi,
   I use the C++ version of GPUImage from here(Windows 8.1 NVIDIA GTX960):
[https://github.com/Dexterp37/GPUImage](url)

And even use the original LUT, the result is also like this:
![amatorkatest](https://cloud.githubusercontent.com/assets/15274287/18164116/d8f0a2fc-7070-11e6-9692-fc15abddf038.png)
![test](https://cloud.githubusercontent.com/assets/15274287/18164117/d91cd9bc-7070-11e6-9b27-bf1fd994b26e.png)

Can anybody give me some tips?

**Comment by BradLarson** [comment]
That C++ port is done by someone else, so sorry, I can't help you there.
