### ISSUE TITLE
How to convert from GPUImage to UIImage in Swift ?

### ISSUE THREAD

**Issue by hgssk** [BradLarson/GPUImage#2356]
hi,
Now I'm trying to use your awesome GPUImage in Swift.
But I cannot to get UIImage from GPUImage.
What is the best method ? 

1 )use screenshot to PNG or JPG ?
2 )convert GPUImage to UIImage ?

but I cannot get UIImage , I don't know how to convert...

**Comment by BradLarson** [comment]
Under the "Performing common tasks" section of the Readme on the main GitHub page, see the example for using `-useNextFrameForImageCapture` and `-imageFromCurrentFramebuffer` for how to do this.
