### ISSUE TITLE
Camera screen is white when try to modify data output source

### ISSUE THREAD

**Issue by Sunfocus** [BradLarson/GPUImage#2377]
//output file
movieFileOutput = [AVCaptureMovieFileOutput new];

Float64 TotalSeconds = 3;           //Total seconds
int32_t preferredTimeScale = 30;    //Frames per second
CMTime maxDuration = CMTimeMakeWithSeconds(TotalSeconds, preferredTimeScale);   //<<SET MAX DURATION
movieFileOutput.maxRecordedDuration = maxDuration;
movieFileOutput.minFreeDiskSpaceLimit = 1024 \* 1024;

//add output file
if ([videoCamera.captureSession canAddOutput:movieFileOutput]) {
    [videoCamera.captureSession addOutput:movieFileOutput];
}
When i try to add my outputSource.Camera screen is white.

**Comment by BradLarson** [comment]
That's a question about AVFoundation, not GPUImage.
