### ISSUE TITLE
pass by reference 

### ISSUE THREAD

**Issue by minamichel** [BradLarson/GPUImage#2378]
Hi Brad,
Is it possible to pass variables by reference to a shader file from Swift code.
Is that doable now or planned to be added in next versions of GPUImage?

**Comment by BradLarson** [comment]
Uniforms are variables passed into shaders, and are used all over the place. See some of the standard shaders for how those are accessed via properties.

**Comment by minamichel** [comment]
Thanks Brad for your prompt response, really appreciate it!
I'm using uniforms in our shaders, but they act as passed by value parameters. What ever alterations happen inside the shader file are not mirrored in the Swift code.
For example:
in Swift:
float x = 0.5
filter.setFloat(x, forUniformName: "threshold"); //we want x to be passed by reference

in the Shader file:
void main ()
{
    highp vec4 color   = texture2D(inputImageTexture, textureCoordinate);
    //do any operation

   threshold += 0.1

```
    gl_FragColor = color;
```

## }

in Swift, after the shader file is executed, we want the variable x to reflect the last value that the shader file had.

Is that possible?

**Comment by BradLarson** [comment]
That's not really possible, nor would there be a sensible way of doing that. Shaders are run in parallel, once per vertex for vertex shaders and once per fragment (pixel) for fragment shaders. Their execution order is arbitrary. You can't really map that back to a single value in memory on the CPU. There's a mismatch in the types of operations here.

This is why a uniform is called a "uniform": it remains constant across all vertices / fragments. Now, you might be able to extract a per-pixel value from an encoded color output in a specifically coded fragment shader (I do this in a couple places) or a per-vertex value (using OpenGL ES 3 extensions), but that's probably not what you're looking for here.

**Comment by minamichel** [comment]
Thanks for clearing that up! It’s becoming clearer now.
I’ll definitely look into OpenGL ES 3 extensions and see if there is a work
around.
Thanks again!
