### ISSUE TITLE
Why use _movieWriterContext instead of sharedImageProcessingContext?

### ISSUE THREAD

**Issue by pengbins** [BradLarson/GPUImage#2381]
Hi, @BradLarson 
May I ask why alloc a new GPUImageContext instance in GPUImageMovieWriter ?

But in other classes , they just use [[GPUImageContext sharedImageProcessingContext] context].

Xcode' Instruments reports a lot of memory leakes from GPUImageMovieWriter's _movieWriterContext.

Can you help to explain this?

**Comment by pengbins** [comment]
same issue reported here:

http://stackoverflow.com/questions/27857330/memory-leak-occurs-when-use-gpuimagemoviewriter-multiple-times

**Comment by zmzhuai** [comment]
I think a new GPUImageContext can gain a better performance. But have a memory leak. I fix the leak here #2413

**Comment by pengbins** [comment]
But with ARC  , manually release queue will cause a crash.

**Comment by zmzhuai** [comment]
@pengbins GPUImage deployment target is iOS 5.0, when deployment target lower than 6.0, the dispatch queue will not release with ARC, you need release yourself.

**Comment by pengbins** [comment]
So you try to fix a memory leak for iOS version lower than 6.0 ?

I think I spot the memory leak reports on iOS9 and  iOS 10.

**Comment by zmzhuai** [comment]
When deployment target is iOS 5.0, you need release dispatch queue even in iOS 10.

**Comment by pengbins** [comment]
I think I spot the memory leak reports on iOS9 and iOS 10, when deployment target set to iOS7.0.

**Comment by zmzhuai** [comment]
I said deployment target is not your project deployment target, GPUImage default deployment target is iOS 5.0
