### ISSUE TITLE
GPUImageVideoCamera Output in a squared view

### ISSUE THREAD

**Issue by oiledCode** [BradLarson/GPUImage#24]
Hi All,

I'm trying to use GPUImage in my app and I'm facing the following problem : I would like to have the camera output in a squared view (due to some UI constraints). There is at the moment a way to do this  using GPUImage? I have tried (using the examples as a reference) but the camera output is not scaled proportionally. 

By the way thanks for the efforts you put in this project.

**Comment by hmate9** [comment]
Here is a simpler solution:

let filteredVideoView = GPUImageView(frame: CGRect(x: 0, y: 40, width: self.frame.width, height: self.frame.width))
        filteredVideoView.fillMode = kGPUImageFillModePreserveAspectRatioAndFill

**Comment by mingyue1991** [comment]
@BradLarson  Hi, I want to get the same output pixel size, no matter the input resolution.you said we  could use -forceProcessingAtSize: or -forceProcessingAtSizeRespectingAspectRatio:then use a crop filter to pull a part of that, I think i did something wrong,then it didn't work.the output size is also the original,i did like this:
GPUImageCropFilter *defaultFilter = [[GPUImageCropFilter alloc] initWithCropRegion:CGRectMake(0, 0.125, 1, 0.75)];
    [defaultFilter forceProcessingAtSizeRespectingAspectRatio:CGSizeMake(750, 750)];
then follow other filters
  please help me how to do that correctly,thank you very much

**Comment by mingyue1991** [comment]
Hi, by doing more test,i found that 
at first,i used like this,
    GPUImageStillCamera *camera = [[GPUImageStillCamera alloc] initWithSessionPreset:AVCaptureSessionPresetPhoto cameraPosition:AVCaptureDevicePositionBack];
 camera.outputImageOrientation = UIInterfaceOrientationPortrait;
        camera.horizontallyMirrorFrontFacingCamera = YES;
    GPUImageCropFilter *cropFilter = [[GPUImageCropFilter alloc] initWithCropRegion:CGRectMake(0, 0.125, 1, 0.75)];
[cropFilter forceProcessingAtSizeRespectingAspectRatio:CGSizeMake(750, 750)];
GPUImageFilter * finalfilter = [[GPUImageFilter alloc] init];
GPUImageView *filterView = [[GPUImageView alloc] initWithFrame:CGRectMake(0.0, 0.0, self.frame.size.width, self.frame.size.height)];
 [filterView setFillMode:kGPUImageFillModePreserveAspectRatioAndFill];
[camera addTarget:cropFilter];
 [cropFilter addTarget:finalfilter];
 [finalfilter addTarget:filterView];

then, i still get the image size is original,like (2448,3228), not the supposed (750, 750),
but if i call the forceProcessingAtSizeRespectingAspectRatio: to finalFilter or the cropFIlter's next filter,i can get the right size image  (750, 750), But what if i  use crop filter only? then i can't get the right size image.do the crop filter don't support forceProcessingAtSizeRespectingAspectRatio? what should i do? thanks

**Comment by sharmli** [comment]
Hi,
I'm working in IOS.I have created the AVCaptureSession for taking pictures, now I would like to add the live filters of GPUImage framework. I couldnt add the target to my live image.please help.
