### ISSUE TITLE
Configure GPUImageToonFilter for these cartoon effetcs 

### ISSUE THREAD

**Issue by ayman-melhem** [BradLarson/GPUImage#241]
I want to get these cartoon effects by using GPUImageToonFilter from GPUImage framework for ios, but i couldn't find the correct parameter to generate these effects shown the listed links

GPUImageToon Filter: This uses Sobel edge detection to place a black border around objects, and then it quantizes the colors present in the image to give a cartoon-like quality to the image.

texelWidth: texelHeight: These parameters affect the visibility of the detected edges threshold: The sensitivity of the edge detection, with lower values being more sensitive. Ranges from 0.0 to 1.0, with 0.2 as the default quantizationLevels: The number of color levels to represent in the final image. Default is 10.0

here the images link:

https://docs.google.com/open?id=0Bxjx-OJ_OAWDa1drTS1iMmJyeWs

https://docs.google.com/open?id=0Bxjx-OJ_OAWDeHZ4eE1zWFc0Y1k

https://docs.google.com/open?id=0Bxjx-OJ_OAWDeHZ4eE1zWFc0Y1k

**Comment by chiragpipaliya** [comment]
can you show me how you got that cartoon type of effects ?
