### ISSUE TITLE
is this active?

### ISSUE THREAD

**Issue by pvinis** [BradLarson/GPUImage#2414]
is this repo active? i see many prs that are not merged and more than half a year since the last commit.
is there something newer/better that can be used? is native apple stuff good enough to replace gpuimage for a streaming/broadcasting app?

**Comment by BradLarson** [comment]
Frankly, it's good enough for my needs and I've moved on to the Swift version here: https://github.com/bradlarson/gpuimage2 so I've discontinued my work on this older version of the framework. Many of the pull requests won't merge cleanly, and everyone blames me for pull requests that break things, so I'm not going to blindly merge them in.

Even if I addressed two issues a day, it would take me over a year to deal with the volume of them here, so I'm effectively declaring bankruptcy on this and moving on.

**Comment by pvinis** [comment]
alright. thanks for your answer.
