### ISSUE TITLE
Polar Coordinates for "Tiny Earth" effect

### ISSUE THREAD

**Issue by maciekish** [BradLarson/GPUImage#2419]
Hi,
Is there any filter i could use to achieve a "Tiny Earth" effect on a panorama please?

[Example](http://www.bitrebels.com/wp-content/uploads/2011/05/Tiny-Planet-Earth-Photography-8.jpg)

**Comment by BradLarson** [comment]
Not in the current framework, no, but you could write your own distortion shader to do this.
