### ISSUE TITLE
heavy metal filter

### ISSUE THREAD

**Issue by bianzhifeng** [BradLarson/GPUImage#2425]
hi , i need a heavy metal filter, can you tell me how do i?, thanks!

**Comment by erickingxu** [comment]
hi @bianzhifeng ,
what meaning of heavy metal ?

**Comment by bianzhifeng** [comment]
you can download MIX app and choose heavy metal filter

**Comment by erickingxu** [comment]
Hi @bianzhifeng ,
Can you provide your question with more details, like website address for others could help you quickly?
Thanks

**Comment by bianzhifeng** [comment]
https://itunes.apple.com/app/id913947918.

**Comment by bianzhifeng** [comment]
sorry, i don't know how to describe this filter.

**Comment by bianzhifeng** [comment]
can you find this filter at MIX App? @erickingxu
