### ISSUE TITLE
Capture UIView to video

### ISSUE THREAD

**Issue by ObelixSoftware** [BradLarson/GPUImage#2436]
I render some OpenGL content to my UIView together with the camera, how can i use GPUImage to capture this to a video like recording the screen ?

**Comment by zuodd** [comment]
have you resolved this?
i setup an OpenGL view and rendered some content (triangles lots of...), but how can i render the content to gpuimage? i don't know if the OpenGL view is conflict to the GPUimage.

**Comment by ruinfire** [comment]
@ObelixSoftware you can use GPUImageUIElement class. but this class is too slow for draw every frame.

**Comment by BradLarson** [comment]
What you'll want to do is render your OpenGL content to a texture-backed framebuffer and then take that texture and feed it into GPUImage. The CubeExample sample application does just this.

One thing you'll need to make sure of is that your OpenGL context and GPUImage's internal context are on the same sharegroup. Again, I show how to do this in the CubeExample application.
