### ISSUE TITLE
Push Image to GPUImage Filters

### ISSUE THREAD

**Issue by djcomy** [BradLarson/GPUImage#2438]
Is there ANY possibility to push an image from one ViewController taken by camera or chosen from gallery to the next ViewController in which GPUImage will be implemented? And then after filter is picked simply get back that "filtered" photo to previous screen?

**Comment by BradLarson** [comment]
Sure, you can process a UIImage and receive a UIImage as output. From there, it's just a matter of passing images back and forth between your view controllers.
