### ISSUE TITLE
GPUImageUIElement  添加的水印模糊不清晰

### ISSUE THREAD

**Issue by OrangeFLJ** [BradLarson/GPUImage#2449]
GPUImageUIElement  添加的水印模糊不清晰, 而且 
        UIView *subView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, size.width, size.height)];
        ThemeData *theme = [[[NSBundle mainBundle] loadNibNamed:@"ThemeData" owner:nil options:nil] firstObject];
        theme.frame = CGRectMake(0, 0, 30, 30);
        theme.center = subView.center;
        [subView addSubview:theme];
       GPUImageUIElement *uielement = [[GPUImageUIElement alloc] initWithView:subView]; 
这样添加水印的话   会不现实我们自定义的themeData

**Comment by hezhk3** [comment]
subview.layer.contentsScale = [UIScreen mainScreen].scale;
