### ISSUE TITLE
memory leak in GPUImageCreateResizedSampleBuffer method..

### ISSUE THREAD

**Issue by donobono** [BradLarson/GPUImage#246]
I found a leak in GPUImageCreateResizedSampleBuffer method of GPUImageStillCamera class with leaks tool..
You commented CFRelease(videoInfo); line of the end of that method, but it looks to make a leak.
After I uncommented CFRelease(videoInfo); and tried to test, there was no leak..

I wonder it makes another problem or not.
Please check this issue..

Thank you for sharing your great and awesome source.. :-)

**Comment by hydyy** [comment]
me too,,,
