### ISSUE TITLE
GPUImageVideoCamera

### ISSUE THREAD

**Issue by OrangeFLJ** [BradLarson/GPUImage#2462]
There will be noise using the front camera.

**Comment by BradLarson** [comment]
I don't really know what this means.

**Comment by OrangeFLJ** [comment]
If you use GPUImageVideoCamera 
 [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset1280x720 cameraPosition:AVCaptureDevicePositionFront];  
 Set the parameters of cameraPosition is  AVCaptureDevicePositionFront. 
Taken out of the video with noise
