### ISSUE TITLE
Bitmap to Vector

### ISSUE THREAD

**Issue by victorstewart** [BradLarson/GPUImage#2471]
any thoughts on adding this capability, converting bitmaps (like png) to vectors (svg)?

**Comment by BradLarson** [comment]
That's well outside of the capabilities of a project like this, and is a pretty complex problem to solve. This project is geared towards pixel-based manipulation of a raster image, with some capabilities for gathering more abstract information (corners, lines, other vision-related features). It can provide the building blocks for more advanced machine vision, but it has no built-in support for extracting vectors from raster images, nor is any such support planned.

**Comment by Al-ImranRony** [comment]
@victorstewart later on, did you find any relative support or solution about vectors ?
