### ISSUE TITLE
Link in readme is dead for the paper on Hough Transform Detector

### ISSUE THREAD

**Issue by taixhi** [BradLarson/GPUImage#2483]
http://medusa.fit.vutbr.cz/public/data/papers/2011-SCCG-Dubska-Real-Time-Line-Detection-Using-PC-and-OpenGL.pdf

returns a 404, where can I find the original paper?

**Comment by BradLarson** [comment]
Try this one:

http://www.fit.vutbr.cz/research/groups/graph/pclines/papers/2011-SCCG-Dubska-Real-Time-Line-Detection-Using-PC-and-OpenGL.pdf
