### ISSUE TITLE
FilterShowcase shows nothing when a filter name is clicked

### ISSUE THREAD

**Issue by sambudda** [BradLarson/GPUImage#2494]
I just downloaded this project. Opened up FilterShowcase in Xcode 8, clicked on one of the filters in list table in my iOS simulator and then it shows page with just a scroll bar. The page is blank. Where is a preview of image something? Comeon people at least have a working example. 
![what_pic](https://user-images.githubusercontent.com/3536867/28629124-82059340-71f4-11e7-93ec-0f391d5643f3.png)

**Comment by BradLarson** [comment]
You wouldn't happen to be running this in the Simulator, are you? The Simulator doesn't have proper camera support, and these examples all run through the device camera's input.

**Comment by sambudda** [comment]
Yes, I was using iOS simulator. I didn't know that this would only work on real device. Perhaps there needs to be a check to sees if its a simulator then show a pop-up to tell the user to run it on actual device. Or better yet if it finds that this example is run on a simulator then instead of launching camera it applies those effects to a static image provided within the project. Just a suggestion. Though thanks for replying quickly.
