### ISSUE TITLE
GPUImagePicture from AssetsLibrary loads upside down

### ISSUE THREAD

**Issue by brspurri** [BradLarson/GPUImage#250]
Just as the title says, when I load a `UIImage` that's been taken with the iPhone camera app into `GPUImagePicture`, it displays upside down. Has anyone else seen this?

However, if I capture an image from the `GPUImageStillCamera`, and then load it into a separate `GPUImagePicture`, it displays in the correct orientation.

However, It appears that the orientation flag in the `UIImage` for both are identical.

Has anyone found a solution to this?

Cheers,
Brett

**Comment by dazzli** [comment]
Hi. Read this issue #895 
@zenvendof is have solution for this problem and @reddragon wrote this in objective-c:

// self.chosenImg is the image that you took, replace it with the appropriate image.
GPUImagePicture *stillImageSource = [[GPUImagePicture alloc] initWithImage:self.chosenImg];
GPUImageSepiaFilter *stillImageFilter = [[GPUImageSepiaFilter alloc] init];

[stillImageSource addTarget:stillImageFilter];
[stillImageFilter useNextFrameForImageCapture];
[stillImageSource processImage];

UIImage* processedImg = [stillImageFilter imageFromCurrentFramebuffer];
processedImg = [UIImage imageWithCGImage:[processedImg CGImage] scale:1.0 orientation:self.chosenImg.imageOrientation];

**Comment by Jane930525** [comment]
Above solution is for UIImage, please suggest a solution for video too for Swift GPUImage2
