### ISSUE TITLE
CVOpenGLESTextureCacheRef leak when I'm using GPUImageMovieWriter

### ISSUE THREAD

**Issue by without2002** [BradLarson/GPUImage#2500]
Hi, Brad, GPUImage is a wonderful framework in github. 
I profile my app by the leak template of instrument. Then I found some leak from CoreVideo. I found you don't release the CVOpenGLESTextureCacheRef in the dealloc method of GPUImageContext. I release the object, then CVOpenGLESTextureCacheRef will not be leaked.
I don't know it is a bug or not?

**Comment by artemtkachenko** [comment]
Same issue happened with me;
put this code:

`- (void)dealloc {
    CFRelease(_coreVideoTextureCache);
}`

inside GPUImageContext.m file

and GPUImageContext is not leaked anymore;

**Comment by without2002** [comment]
Thank you, I have fixed the leak with same code.
