### ISSUE TITLE
GPUImage project makes Xcode crash on MacOS 10.13 beta

### ISSUE THREAD

**Issue by gaojinhsu** [BradLarson/GPUImage#2503]
OS: macOS 10.13 Beta(17A352a)

I know this could be a bug of macOS or Xcode, but I still wanna try my luck here.

Xcode(both Xcode 8 and Xcode 9-Beta) crashes on opening project as long as the project or workspace contains GPUImage.
![39ccdbe6-509c-4498-a50b-8492977c057a](https://user-images.githubusercontent.com/2178687/29758409-ea036466-8b78-11e7-8e34-4384ac26772d.png)

**Comment by BradLarson** [comment]
This appears to be a bug in CoreFoundation in the current macOS betas: https://twitter.com/kcase/status/901900659154235392 and impacts all large Xcode projects.
