### ISSUE TITLE
GPUImage After processing image blur

### ISSUE THREAD

**Issue by kai120897660** [BradLarson/GPUImage#2508]
When I input image is 3024 x4032 images, in outputView (GUPImageView) in real-time display pixels below the original image.Is better than the original image blurred

**Comment by BradLarson** [comment]
I have no idea what you are asking here.

**Comment by kai120897660** [comment]
GPUImageExposureFilter *exposureFilter = [[GPUImageExposureFilter alloc]init];
    exposureFilter.exposure = global.num * 0.01;
    [exposureFilter forceProcessingAtSize:CGSizeMake(3024, 4032)];

    [picture addTarget:exposureFilter];
    [exposureFilter addTarget:outputView];
    
    [picture processImage];
    
    [exposureFilter useNextFrameForImageCapture];



When I set up an exposure filter like this, enter the picture, which is the size of 3024x4032. But in the above outputView to receive the image size is 640x854, and I set up a forceProcessingAtSize:, is my code error?  or else can set the output image size of 3024x4032 on outputView.
