### ISSUE TITLE
What is the correct way to set Focus and Exposure?

### ISSUE THREAD

**Issue by ScofieldYeh** [BradLarson/GPUImage#254]
I would like add  gesture to allow user to set focus and exposure by tapping the screen. 
in viewDidLoad, I add gesture to photoview (which is a GPUImageView)

```
UITapGestureRecognizer *tgr = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(cameraViewTapAction:)];
[self.photoView addGestureRecognizer:tgr];
```

And below is my code of gesture for setting focus and exposure. 
# pragma mark - Gesture recognition
- (void)cameraViewTapAction:(UITapGestureRecognizer *)tgr
  {
  if (tgr.state == UIGestureRecognizerStateRecognized) {
     CGPoint location = [tgr locationInView:self.photoView];
      [videoCamera.inputCamera lockForConfiguration:nil];  
      [videoCamera.inputCamera setFocusPointOfInterest:location];
      [videoCamera.inputCamera setFocusMode:AVCaptureFocusModeAutoFocus];
  
  ```
  [videoCamera.inputCamera setExposurePointOfInterest:location];
  [videoCamera.inputCamera setExposureMode:AVCaptureExposureModeContinuousAutoExposure];
  
  [videoCamera.inputCamera unlockForConfiguration];
  ```
  
  }
  }

But on my iPhone4 /iPhone4S it does not work. Even I tried to adjust Focus or Exposure alone.  
So what is the correct way to set the Focus and Exposure? Thank you!

**Comment by TranChuong** [comment]
I have issues, camera no focus when using front camera, while standard camera app run ok
I test on iPhone 5s, iOS 8.1.2
Who can help me?

if ([device isFocusPointOfInterestSupported] && [device isFocusModeSupported:AVCaptureFocusModeAutoFocus]) {
    NSError *error;
    if ([device lockForConfiguration:&error]) {
        [device setFocusPointOfInterest:pointOfInterest];

        [device setFocusMode:AVCaptureFocusModeAutoFocus];

        if([device isExposurePointOfInterestSupported] && [device isExposureModeSupported:AVCaptureExposureModeContinuousAutoExposure])
        {


        [device setExposurePointOfInterest:pointOfInterest];
        [device setExposureMode:AVCaptureExposureModeContinuousAutoExposure];
        }

        [device unlockForConfiguration];

        NSLog(@"FOCUS OK");
    } else {
        NSLog(@"ERROR = %a", error);
    }  
}

**Comment by TechbirdsYogendra** [comment]
Instead of 
[device setExposureMode:AVCaptureExposureModeContinuousAutoExposure];
use
[device setExposureMode:AVCaptureExposureModeAutoExposure];

Because in when you set AVCaptureExposureModeContinuousAutoExposure it will adjust focus according to the whole screen.
