### ISSUE TITLE
Are there any algorithm specifications or helpful references about the "GPUImageLookupFilter.m"?

### ISSUE THREAD

**Issue by FinleyPan** [BradLarson/GPUImage#2578]
I am reading and trying to understand the threads in ["GPUImageLookupFilter.m"](https://github.com/BradLarson/GPUImage/blob/master/framework/Source/GPUImageLookupFilter.m). But there are too few information for me, so can anyone porvide me some enlightening and relevant documentations about it?

**Comment by BradLarson** [comment]
This explains the process in detail, from the one who created it:

http://liovch.blogspot.com/2012/07/add-instagram-like-effects-to-your-ios.html
