### ISSUE TITLE
GPUImageMovie WithPlayerItem not found in Gpuimage 2 Swift

### ISSUE THREAD

**Issue by jagadeeshkadumula** [BradLarson/GPUImage#2593]
GPUImageMovie WithPlayerItem not found in Gpuimage 2(swift)

[[GPUImageMovie alloc] initWithPlayerItem:playerItem] not found this method
Got this only
 let movie = MovieInput(asset: , playAtActualSpeed: , loop:)

I worked on using Gpuimage objective c code, Its working fine, but for new project I'm working in swift so used gpuimage 2. In this framework i didnt got this method "GPUImageMovie(playerItem: playerItem)". please give me solution. Thanks in Advance.

**Comment by jagadeeshkadumula** [comment]
Any alternative is there for [[GPUImageMovie alloc] initWithPlayerItem:playerItem]  this in Gpuimage 2??

**Comment by khush004** [comment]
is there any solution found?

**Comment by jagadeeshkadumula** [comment]
Yes, You can use gpu image(objective c) library in swift project
