### ISSUE TITLE
Blend two movie inputs, maintaining sync

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [BradLarson/GPUImage#261]
It would be good to be able to have videos as inputs to the two input filters....
I'm trying to do something like...

GPUImageMovie *colourMovie; //init correctly etc...
GPUImageMovie *reflectionMovie;

GPUImageScreenBlendFilter\* reflectionFilter;

 [colourMovie addTarget:reflectionFilter];
 [reflectionMovie addTarget:reflectionFilter];

 [reflectionFilter addTarget:self.viewer];

 [colourMovie startProcessing];
 [reflectionMovie startProcessing];

This sometimes works if I change the order in which the movies are started, but has threading sync issues as both movies are driving the processing. 

I get an assert:  Incomplete filter FBO: most of the time.

Is there any way to do this? Do I need to add some semaphores to the rendering?

**Comment by tuo** [comment]
hi @efesus, I think this one might help you on this:  [GPUImage Video Merging: Timestamp Synchronization](http://tuohuang.info/gpuimage-video-merging--timestamp-synchronization)
