### ISSUE TITLE
React-native error: RCTBridgeDelegate.h file not found

### ISSUE THREAD

**Issue by saran1985** [BradLarson/GPUImage#2626]
I have created a new project using npm install init auth(auth is the name of the project).
Tried to run the project using react-native run-ios at the terminal.Build failed and i get this error.

fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>

**Comment by BradLarson** [comment]
Sorry, I don't believe this is an issue related to this project.
