### ISSUE TITLE
GPUImage +OpenGL

### ISSUE THREAD

**Issue by priyanka6692** [BradLarson/GPUImage#2627]
Im using GPUImage video camera and detect face landmark with the help of Dlib and render a mask on live feed.
 Now the problem is I want beautify filter on my camera feed + I want to add mask on the same feed but when I try to enqueue mask layer with samplebuffer my filter goes away bcz I'm using AVSampleBufferDisplay layer.
I didn't find Display layer in GPUImage library so that I can use the same layer for rendering.
Can you please help me with this.

**Comment by soham24** [comment]
:o
