### ISSUE TITLE
“GPUImage.h” not found

### ISSUE THREAD

**Issue by oliverwolfson** [BradLarson/GPUImage#407]
Excuse the basic question. I have not found this issue here or elsewhere, so I assume it's basic. Any help?

I have added the framework, setup the target dependency, added the Header Search path as: framework, and added other linker flag -ObjC. Still no luck. 

The file is here if anyone would care to take a look: http://owolf.net/uploads/StackOverflow/GPUITest.zip

**Comment by apprisingapps** [comment]
Thanks for the information Brad, and a great Framework!
