### ISSUE TITLE
Front camera landscape 

### ISSUE THREAD

**Issue by oiledCode** [BradLarson/GPUImage#418]
Can someone explain how to deal with device rotation when using the front camera? 
At the moment I start my app using the back camera setting :
    self.camera.outputImageorientation = UIInterfaceOrientationPortrait;

but when I switch to the front camera turning the device in landscape cause a wrong rotation (image mirrored).
What's the best approach to deal with this.

**Comment by RajIET** [comment]
self->_stilCamera = [[GPUImageStillCamera alloc]initWithSessionPreset:AVCaptureSessionPresetInputPriority cameraPosition:AVCaptureDevicePositionFront];
    
    self->_gpuImageView = [[GPUImageView alloc]initWithFrame:CGRectMake(0.0, 0.0, self.view.frame.size.width, self.view.frame.size.height)];
    self->_gpuImageView.fillMode = kGPUImageFillModePreserveAspectRatioAndFill;
    
    GPUImageFilter *filter = [[FilterProcessing sharedInstance] originalFilter];
    [self.view addSubview:self->_gpuImageView];
    
    [self->_gpuImageView setInputRotation:kGPUImageFlipHorizonal atIndex:0];
    
    [self->_stilCamera addTarget:filter];
    [filter addTarget:self->_gpuImageView];
    [self->_stilCamera startCameraCapture];

Camera preview seems correct but captured image is not correct in orientation. I gone through the google and nothing get helpful.

Can provide code for camera preview and captured image is correct in orientation.
