### ISSUE TITLE
Measurement using GPUImage

### ISSUE THREAD

**Issue by artoq** [BradLarson/GPUImage#453]
Hi there,

I'm trying to use (awesome) GPUImage to get some useful data from the camera. Therefore: Is there any way to use a filtered frame beside displaying it on the screen, like save it or use it for further calculations?

For e.g.: What I'm trying to do is get a frame from a live video, calculate the average luminescence and save this value including it's timestamp into a table. 

Well, I guess the monochrome filter is a beginning but I hope I made my point: Where to go from here - can I use a framelike output and use it the way I mentioned before? 

Thanks for helping a "lost in opengles" guy ;)

**Comment by AaronBratcher** [comment]
If I could add on to this question: I'm trying to get the luminosity of a UIImage. How do I set a completionBlock? It seems my imageFilter doesn't have the setLuminosityProcessingFinishedBlock method.

// check luminosity is high enough
			let picture = GPUImagePicture(image: image)
			let imageFilter = GPUImageLuminosity()
			picture.addTarget(imageFilter)

**Comment by tattle** [comment]
Hi Brad, May I knwo how to get the luminosity in GPUImageLuminosity in swift? Thanks!
