### ISSUE TITLE
Error in GPUImageMovie after loading the same mov 4 or 5 times in a row

### ISSUE THREAD

**Issue by taberrr** [BradLarson/GPUImage#503]
I'm trying to load (and then filter) a .mov after pressing a button. I'm waiting until my "finished!" notice between button presses, but while using my iOS 5.1.1 iPhone 4, I get a "Error reading from file at URL: (null)" error every time, on the 5th time loading the asset. There are no errors while using my iPhone 5/iOS 6.

Here are the relevant lines in my test app:

```
- (void)filterVideoAtURL:(NSURL *)url
{
    AVAsset *asset = [AVAsset assetWithURL:url];

    self.movieFile = [[[GPUImageMovie alloc] initWithAsset:asset] autorelease];
    self.pixellateFilter = [[[GPUImagePixellateFilter alloc] init] autorelease];

    [_movieFile addTarget:_pixellateFilter];
    ...
}
```

Relevant lines in GPUImageMovie.m:

```
if ([reader startReading] == NO) 
{
    NSLog(@"Error reading from file at URL: %@", weakSelf.url);
    return;
}
```

If you need more info or the test app, let me know.

Thanks!

**Comment by ergunkocak** [comment]
I have the same issue with an HD quality mov file which is 446MB. I can share the mov over wetransfer if anyone can debug.

Regards
