### ISSUE TITLE
Rotate UIImage with GPUImageTransformFilter 

### ISSUE THREAD

**Issue by paulli** [BradLarson/GPUImage#582]
Hi, 
I am trying to rotate an image by 90 degree using GPUImageTransformFilter. This is what I tried

```
GPUImageTransformFilter *transformFilter = [[GPUImageTransformFilter alloc] init];
[transformFilter setAffineTransform:CGAffineTransformMakeRotate(M_PI_2)];

UIImage *rotatedImage = [transformFilter imageByFilterImage: originalUiImage];
```

originalUiImage is an image of size 1600x1200. rotatedImage is also 1600x1200, with the top and bottle clipped. This seems a bit weird and not what I expected. I want to get an image of size 1200x1600, an exactly the same image as originalUiImage but rotated 90 degree. Could you let me know if this is possible?

Thanks

**Comment by mobihunterz** [comment]
Could anyone let me know any code here?

I have used,

```
GPUImageTransformFilter *filter = [[GPUImageTransformFilter alloc] init];
filter.affineTransform = CGAffineTransformMakeRotation(180);
UIImage *resultedimage = [filter imageByFilteringImage:  [UIImage imageNamed: "imageName.png"]];
```

This code gives proper rotation for 90 degrees but not able to give rotation for 180 degrees. It even does well with 179 degrees. Is there any way I can utilise this function?
