### ISSUE TITLE
How to switch cameras position mid video?

### ISSUE THREAD

**Issue by vu0tran** [BradLarson/GPUImage#585]
I looked inside all the examples, searched the issues and wiki and can't seem to find an answer on this. I apologize if I'm overlooking something.

I understand I can initialize a new videoCamera with a different device position:

videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionBack];

But how do I change it in the middle of recording? For instance, I record from back camera for 5 seconds then switch to the front camera.

videoCamera.cameraPosition does not have any setters. 

What's the best way to go about doing this?

**Comment by omeara13** [comment]
This is still an issue. Did anyone figure out a solution?
