### ISSUE TITLE
imageView.fillMode , NOT WORK !!!

### ISSUE THREAD

**Issue by imodeveloper** [BradLarson/GPUImage#593]
Hi !  Sorry for my english

I use SimpleImageFilter EXAMPLE , and i want to filter an image with sie 591x288 px 
I have not changed anything essential in the project
I added a picture only xxx.png

https://www.dropbox.com/s/hmlim4glqyc6rqd/Screen%20Shot%202012-10-29%20at%2011.23.39%20PM.png 

but it gets stretched 

https://www.dropbox.com/s/pyje9kwe7wh8v7z/IMG_0152.PNG

And in console i have this debug message

2012-10-29 23:16:54.545 SimpleImageFilter[3675:907] Application windows are expected to have a root view controller at the end of application launch
2012-10-29 23:16:54.751 SimpleImageFilter[3675:907] Received memory warning.

Please help to fix that problem

**Comment by dhruvvarde** [comment]
> No need to shout.
> 
> Don't use -forceProcessingAtSize:, because that will force your image to be at that size and aspect ratio. Instead, use -forceProcessingAtSizeRespectingAspectRatio:, which will resize your image to be within the bounds you set, but still at the proper aspect ratio.
> 
> The memory warning and root view controller one are separate issues. The root view controller one is fixed by setting a root view controller on startup (which I think I forget to do in a couple of the examples) and the memory warning probably has to do with you holding some large images in memory.

- That's work !!...thanks.
