### ISSUE TITLE
Compositing cropped video while maintaining geometry of cropped frame

### ISSUE THREAD

**Issue by stevegraham** [BradLarson/GPUImage#679]
I've been trying to composite processed video that has been cropped with the original video frame. The result should look something like this:

![http://i.imgur.com/OxYAz.png](http://i.imgur.com/OxYAz.png)

Everything I have tried just stretches the smaller image out to fill the GPUImageView instance, even when I'm not blending images. 

What am I doing wrong?

**Comment by UweMeier** [comment]
@stevegraham have you found a solution for this problem? Right now, I'm experiencing the same problem.
