### ISSUE TITLE
Crashing when saving an image from GPUImageStillCamera

### ISSUE THREAD

**Issue by rafiki270** [BradLarson/GPUImage#69]
the app is crashing on 4s if an image is taken and is being manipulated (with original code, with UIImageWriteToSavedPhotosAlbum() as well as with ALAssetsLibrary)

So far it looks like not enough memory on the device to process the image, this is just a guess as I am not getting any message even with zombies enabled. 8 maga pixel camera might be just too much for image handling? I have even tried to save the image on a separate thread (don't really kno why) :(

**Comment by tomscheney** [comment]
*** Assertion failure in -[GPUImageFramebuffer unlock], /Users/Tom/Desktop/miaohi-ios/Pods/GPUImage/framework/Source/GPUImageFramebuffer.m:269
reason: Tried to overrelease a framebuffer, did you forget to call -useNextFrameForImageCapture before using -imageFromCurrentFramebuffer?

**Comment by tomscheney** [comment]
blow is the code.
-(GPUImageLookupFilter*)lookkupImageFilterWithFilterName:(NSString *)filterName{
    UIImage *sourceImg = [UIImage imageNamed:filterName];
    self.lookupImageSource = [[GPUImagePicture alloc] initWithImage:sourceImg];
    GPUImageLookupFilter *filter = [[GPUImageLookupFilter alloc] init];
    filter.intensity = 1;
    [self.lookupImageSource addTarget:filter atTextureLocation:1];

    [filter useNextFrameForImageCapture];
    [self.lookupImageSource processImage];
    
    return filter;
}

**Comment by tomscheney** [comment]
@BradLarson  help me. i make  GPUImageLookupFilter with sample image . but using filter video processing crash. thanks.

**Comment by tomscheney** [comment]
#pragma mark -生成滤镜

#pragma mark - 视频添加滤镜和贴纸

- (void)addedFiltererForVideo:(FragmentModel*)model{
    
    NSLog(@"开始滤镜");
    AVAsset *asset = [AVAsset assetWithURL:model.videoURL];
    AVAssetTrack *videoTrack;
    NSArray *videoTracks = [asset tracksWithMediaType:AVMediaTypeVideo];
    if (videoTracks.count > 0) {
        videoTrack = [videoTracks objectAtIndex:0];
    } else {
        _overLayProgress += _fragmentDenominator;
        return;
    }
    CGSize movieSize = videoTrack.naturalSize;
    
    self.lookupFilter = [self lookkupImageFilterWithFilterName:model.filterName];
    
    _movieFile = [[GPUImageMovie alloc] initWithURL:model.videoURL];
    __weak  GPUImageMovie *weakMovieFile = _movieFile;
    
    [_movieFile addTarget:_lookupFilter];
    
    //加水印的过滤器
    self.blendFilter = [[GPUImageAlphaBlendFilter alloc] init];
    __weak  GPUImageAlphaBlendFilter *weakBlendFilter =  _blendFilter;
    
    self.blendFilter.mix = 1.0;
    
    [self.lookupFilter addTarget:weakBlendFilter];
    
    UIImageView *contentView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, movieSize.width, movieSize.height)];
    contentView.backgroundColor = [UIColor clearColor];
    contentView.image = model.waterMask;
    
    _uiElementInput = [[GPUImageUIElement alloc] initWithView:contentView];
    
    [_uiElementInput addTarget:_blendFilter];
    
    NSString *pathToMovie = [CHCaptureToolKit getFilteredVideoFilePath];
    unlink([pathToMovie UTF8String]);
    NSURL *movieURL = [NSURL fileURLWithPath:pathToMovie];
    
    mergeURL = movieURL;//如果文件只有一个直接赋值，不需要merge操作
    resultVideoURL = movieURL;
    [filterResultList addObject:movieURL];
    
    _movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:movieSize];
    
    [self.blendFilter addTarget:_movieWriter];
    __weak GPUImageUIElement *weakUIElementInput = _uiElementInput;
    
    [self.lookupFilter setFrameProcessingCompletionBlock:^(GPUImageOutput *filter, CMTime time) {
        [weakUIElementInput update];
    }];
    //添加音频输入
    _movieWriter.shouldPassthroughAudio = YES;
    
    if ([[asset tracksWithMediaType:AVMediaTypeAudio] count] > 0){
        weakMovieFile.audioEncodingTarget =  _movieWriter;
        
    } else {//no audio
        weakMovieFile.audioEncodingTarget = nil;
    }
    [_movieFile enableSynchronizedEncodingUsingMovieWriter:_movieWriter];
    
    [_movieWriter startRecording];
    [_movieFile startProcessing];
    
    dispatch_semaphore_t  semaphore = dispatch_semaphore_create(0);
    
    __weak GPUImageLookupFilter *weakLookFilter = _lookupFilter;
    __weak GPUImageMovieWriter *weakMovieWriter = _movieWriter;
    [_movieWriter setCompletionBlock:^{
        NSLog(@"视频滤镜输出完成");

        [weakLookFilter removeTarget:weakMovieWriter];
        [weakMovieWriter finishRecording];
        [weakMovieFile removeAllTargets];
        [weakMovieFile endProcessing];
        weakMovieFile.audioEncodingTarget = nil;
        [weakBlendFilter removeAllTargets];
        [weakBlendFilter endProcessing];
        [weakUIElementInput removeAllTargets];
        
        dispatch_semaphore_signal(semaphore);
        
    }];
    NSLog(@"滤镜，等着.....");

    dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER);
    
    NSLog(@"滤镜，下一步.....");
}
