### ISSUE TITLE
Alpha blending text and vector/line art leaves stroke around the edge

### ISSUE THREAD

**Issue by iamcam** [BradLarson/GPUImage#768]
I've been putting this off for some time now, but it's really starting to bug me:

When I add a crisp watermark (line art or text) and blend it with the photo, the watermark seems to have a grey stroke around it. It's most noticeable with white text on a light background. I've tried using higher-resolution watermarks and scaling down, alpha blend and GPUImageSourceOverBlendFilter, but it doesn't seem to make a difference. I also noticed that the UIElement filter has more or less a similar effect.

Low resolution:
http://screencast.com/t/DOCRkaZwWY

Increasing the resolution on the watermark helps a bit, but doesn't solve it (4x the above resolution):
http://screencast.com/t/963agvVf

It seems the alpha is blending down to light gray, but not entirely transparent. Is there any way to improve this situation short of using CPU-based rendering to add the watermark and vector/line art?

**Comment by hhhlhy** [comment]
Is there a solution?
