### ISSUE TITLE
CVOpenGLESTextureCacheCreateTextureFromImage Error -6661

### ISSUE THREAD

**Issue by fengally** [BradLarson/GPUImage#77]
Hi, I met a problem when finish record from camera. It shows,
Camera CVOpenGLESTextureCacheCreateTextureFromImage failed (error: -6661)

I found some buffer that the camera buffer handler got is null.

Can you help fixing that?

**Comment by brizzly** [comment]
Hello I get the same issue with xCode 6.4, iPad Air, iOS 8.3.

Reboot done, everything done, always get this error :
<img width="878" alt="screen shot 2015-07-14 at 5 58 14 pm" src="https://cloud.githubusercontent.com/assets/634736/8677922/13fe5b8e-2a52-11e5-8c86-9e0650bf2b6a.png">

**Comment by CM137** [comment]
I am now receiving the same error as brizzly has shown above.  Any idea why this is happening? Everything was running fine last time I ran the application, but now it is broken.

**Comment by BradLarson** [comment]
@CM137 - I believe that's a bug in iOS 8.3, as described in issue #2041 . Something broke in 8.3, then was fixed in 8.4. Only affects that specific iOS version.
