### ISSUE TITLE
Is it possible to connect GPUImageOutput to AVCaptureMetadataOutput and access iOS 6's GPU Face Detections?

### ISSUE THREAD

**Issue by npinto** [BradLarson/GPUImage#794]
Thanks a ton for your hard work on this framework, it's been very useful to us!

This may seem like a stupid question but I'd like to be able to "connect" the output of a GPUFilter to AVCaptureMetadataOutput in order to get a list of detected faces (with pose estimations, unavailable in CIFaceDetector). Is there any way to achieve this? 

Since AVCaptureMetadataOutput's face detector runs on the GPU, it must be accessing some gpu memory -- is it possible to take control of this buffer with the GPUImage framework?

Another way could be to simulate an AVCaptureInput with the appropriate ports -- is this even possible?

Thanks!

**Comment by erickingxu** [comment]
Hi @MattFoley, I think it is not give an answer for this topic , when we want to detect a video after gpuimage processing, it is still slow with Metadata or cifacedetector.
Anyone can provide a thought for this problem?
