### ISSUE TITLE
Memory leaks (GPUImageMovie processImage:)

### ISSUE THREAD

**Issue by pradyumnad** [BradLarson/GPUImage#799]
![Screenshot_30_01_2013_16_18](https://f.cloud.github.com/assets/894746/110649/f46b055e-6aca-11e2-9689-dd7a0fa28b4d.png)

Guys can anyone help me solve those memory leaks.. I dont understand why there are many leaks in GPUImage library..

**Comment by foyer** [comment]
I was having an issue with memory leakage while using GPUImageChromaKeyBlendFilter with GPUImageMovie. What seemed to fix it was calling endProcessing on the GPUImageMovie object when the view disappears or just whenever I was done with it.
