### ISSUE TITLE
[UIView nextAvailableTextureIndex]: unrecognized selector

### ISSUE THREAD

**Issue by sambudda** [BradLarson/GPUImage#838]
This is quite frustrating. This question is for Xcode 4.2 with iOS 5 in storyboard mode. 

I have downloaded GPUImage code and am trying to incorporate in a very simple brand new project. 

I keep getting the following errors

2013-02-11 18:10:25.872 FXCam HD[3081:707] -[UIView nextAvailableTextureIndex]: unrecognized selector sent to instance 0x458270
2013-02-11 18:10:25.876 FXCam HD[3081:707] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView nextAvailableTextureIndex]: unrecognized selector sent to instance 0x458270'
**\* First throw call stack:
(0x36f978bf 0x323071e5 0x36f9aacb 0x36f99945 0x36ef4680 0x268ff 0x32e1 0x31ba87ff 0x31ba6f9d 0x31b99941 0x31c0b541 0x31ba79bb 0x31ba13bd 0x31b6f921 0x31b6f3bf 0x31b6ed2d 0x32bc9e13 0x36f6b553 0x36f6b4f5 0x36f6a343 0x36eed4dd 0x36eed3a5 0x31ba0457 0x31b9d743 0x2f79 0x2f10)
terminate called throwing an exceptionkill
Current language:  auto; currently objective-c
Program ended with exit code: 0

This is what I have done so far
- I added GPUImage framework
- I added all the other required frameworks
- I added "-ObjC" "-fobjc-arc" in other linker flags
- I literally copied and pasted code from SampleVideoFilter project that is included. 
- I have read all the read me and documentation available on this project and I didn't miss anything.

All I am trying to do is show a filter when my camera app is launched but I get nowhere. 

Here are the contents of my *.m & *.h files
# import <UIKit/UIKit.h>
# import "GPUImage.h"

@interface v1ViewController : UIViewController
{
    GPUImageVideoCamera *videoCamera;
    GPUImageOutput<GPUImageInput> *filter;
    GPUImageMovieWriter *movieWriter;
}
- (IBAction)updateSliderValue:(id)sender;

@end
# import "v1ViewController.h"

@implementation v1ViewController
- (void)didReceiveMemoryWarning
  {
  [super didReceiveMemoryWarning];
  // Release any cached data, images, etc that aren't in use.
  }
# pragma mark - View lifecycle
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionBack];
  //    videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset640x480 cameraPosition:AVCaptureDevicePositionFront];
  //    videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset1280x720 cameraPosition:AVCaptureDevicePositionBack];
  //    videoCamera = [[GPUImageVideoCamera alloc] initWithSessionPreset:AVCaptureSessionPreset1920x1080 cameraPosition:AVCaptureDevicePositionBack];
  
  videoCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
  videoCamera.horizontallyMirrorFrontFacingCamera = NO;
  videoCamera.horizontallyMirrorRearFacingCamera = NO;
  
  filter = [[GPUImageSepiaFilter alloc] init];
  
  //    filter = [[GPUImageTiltShiftFilter alloc] init];
  //    [(GPUImageTiltShiftFilter *)filter setTopFocusLevel:0.65];
  //    [(GPUImageTiltShiftFilter *)filter setBottomFocusLevel:0.85];
  //    [(GPUImageTiltShiftFilter *)filter setBlurSize:1.5];
  //    [(GPUImageTiltShiftFilter *)filter setFocusFallOffRate:0.2];
  
  //    filter = [[GPUImageSketchFilter alloc] init];
  //    filter = [[GPUImageSmoothToonFilter alloc] init];
  //    GPUImageRotationFilter *rotationFilter = [[GPUImageRotationFilter alloc] initWithRotation:kGPUImageRotateRightFlipVertical];
  
  [videoCamera addTarget:filter];
  GPUImageView *filterView = (GPUImageView *)self.view;
  [filter addTarget:filterView];
  //    filterView.fillMode = kGPUImageFillModeStretch;
  //    filterView.fillMode = kGPUImageFillModePreserveAspectRatioAndFill;
  
  // Record a movie for 10 s and store it in /Documents, visible via iTunes file sharing
  
  NSString *pathToMovie = [NSHomeDirectory() stringByAppendingPathComponent:@"Documents/Movie.m4v"];
  unlink([pathToMovie UTF8String]); // If a file already exists, AVAssetWriter won't let you record new frames, so delete the old movie
  NSURL *movieURL = [NSURL fileURLWithPath:pathToMovie];
  movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(480.0, 640.0)];
  //    movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(640.0, 480.0)];
  //    movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(720.0, 1280.0)];
  //    movieWriter = [[GPUImageMovieWriter alloc] initWithMovieURL:movieURL size:CGSizeMake(1080.0, 1920.0)];
  [filter addTarget:movieWriter];
  
  [videoCamera startCameraCapture];
  
  double delayToStartRecording = 0.5;
  dispatch_time_t startTime = dispatch_time(DISPATCH_TIME_NOW, delayToStartRecording \* NSEC_PER_SEC);
  dispatch_after(startTime, dispatch_get_main_queue(), ^(void){
      NSLog(@"Start recording");
  
  ```
  videoCamera.audioEncodingTarget = movieWriter;
  [movieWriter startRecording];
  
  //        NSError *error = nil;
  //        if (![videoCamera.inputCamera lockForConfiguration:&error])
  //        {
  //            NSLog(@"Error locking for configuration: %@", error);
  //        }
  //        [videoCamera.inputCamera setTorchMode:AVCaptureTorchModeOn];
  //        [videoCamera.inputCamera unlockForConfiguration];
  
  double delayInSeconds = 10.0;
  dispatch_time_t stopTime = dispatch_time(DISPATCH_TIME_NOW, delayInSeconds * NSEC_PER_SEC);
  dispatch_after(stopTime, dispatch_get_main_queue(), ^(void){
  
      [filter removeTarget:movieWriter];
      videoCamera.audioEncodingTarget = nil;
      [movieWriter finishRecording];
      NSLog(@"Movie completed");
  
      //            [videoCamera.inputCamera lockForConfiguration:nil];
      //            [videoCamera.inputCamera setTorchMode:AVCaptureTorchModeOff];
      //            [videoCamera.inputCamera unlockForConfiguration];
  });
  ```
  
  });
  }
- (void)viewDidUnload
  {
  [super viewDidUnload];
  }
- (void)viewWillAppear:(BOOL)animated
  {
  [super viewWillAppear:animated];
  }
- (void)viewDidAppear:(BOOL)animated
  {
  [super viewDidAppear:animated];
  }
- (void)viewWillDisappear:(BOOL)animated
  {
  [super viewWillDisappear:animated];
  }
- (void)viewDidDisappear:(BOOL)animated
  {
  [super viewDidDisappear:animated];
  }
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
  {
  // Return YES for supported orientations
  if ([[UIDevice currentDevice] userInterfaceIdiom] == UIUserInterfaceIdiomPhone) {
      return (interfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
  } else {
      return YES;
  }
  }
- (IBAction)updateSliderValue:(id)sender
  {
  [(GPUImageSepiaFilter *)filter setIntensity:[(UISlider *)sender value]];
  }

@end

**Comment by chrisallick** [comment]
I know this is closed, but as a developer I have a view controller and i programmatically make subviews from classes. I don't want that view to be view controller, its just a uiview, so am i always going to get this error? Here is what I'd like to do

    GPUImageView *primaryView = [[GPUImageView alloc] initWithFrame:CGRectMake(0.0, 0.0, self.frame.size.width, self.frame.size.width)];
    [self addSubview:primaryView];
    
    stillCamera = [[GPUImageStillCamera alloc] init];
    stillCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
    //
    filter = [[GPUImageSketchFilter alloc] init];
    //
    [stillCamera addTarget:filter];
    //
    GPUImageView *filterView = (GPUImageView *)self;
    [filter addTarget:filterView];
    [stillCamera startCameraCapture];

**Comment by chrisallick** [comment]
If you want to solve all of this just use this code. Apparently it's not what you're "supposed to do" but it gives you the control you want and is more what iso devs are used to

http://stackoverflow.com/questions/28333594/how-to-add-multiple-filters-to-uiimage-gpuimage/28333595?noredirect=1#comment45097136_28333595

**Comment by chrisallick** [comment]
Wait, jk, this will get you close

    stillCamera = [[GPUImageStillCamera alloc] init];
    stillCamera.outputImageOrientation = UIInterfaceOrientationPortrait;
    filter = [[GPUImageSketchFilter alloc] init];
    [stillCamera addTarget:filter];
    GPUImageView *filterView = [[GPUImageView alloc] initWithFrame:self.frame];
    [self addSubview:filterView];
    [filter addTarget:filterView];

    [stillCamera startCameraCapture];

**Comment by BradLarson** [comment]
A GPUImageView is just a UIView subclass, so it can be added to UIViews like any other UIView. The issue all the way at the top here was in setting up a UIView in Interface Builder and not defining it as a GPUImageView there.

You can easily define a completely programmatic interface and use GPUImageViews there. In fact, at least one of the sample applications does this.
