### ISSUE TITLE
GPUImageTransformFilter background color

### ISSUE THREAD

**Issue by otite** [BradLarson/GPUImage#855]
Hi,

i'm trying to overlay a video on top of the cam capture. but when i resize/rotate the top video, the output background is black, even with "setBackgroundColorRed:0. green:0. blue:0. alpha:0.".
# EDIT

using a GPUImageAlphaBlendFilter at the end of my chain solved my problem ! sorry about this.

cheers,

guillaume

**Comment by cgmaier** [comment]
hey @otite would you mind explaining how an alpha blend filter can help with this?
