### ISSUE TITLE
<Error>: CGImageCreate: invalid image size: 0 x 0.

### ISSUE THREAD

**Issue by pawankmrai** [BradLarson/GPUImage#908]
hello

i am getting error----  <Error>: CGImageCreate: invalid image size: 0 x 0.

SMPCollectionViewCell *cell = [cv dequeueReusableCellWithReuseIdentifier:@"MyCell" forIndexPath:indexPath];

```
UIImage *proImage1=(UIImage *)[self.imageArray objectAtIndex:indexPath.row];
UIImage *proImage2=(UIImage *)[self.proArray objectAtIndex:indexPath.row];



GPUImagePicture *source1=[[GPUImagePicture alloc] initWithImage:proImage1];
GPUImagePicture *source2=[[GPUImagePicture alloc] initWithImage:proImage2];

[source1 addTarget:_filter];
[source2 addTarget:_filter];

[source1 processImage];
[source2 processImage];
```

   UIImage *tempImage=[self.filter imageFromCurrentlyProcessedOutput];

```
if ([tempImage isKindOfClass:[UIImage class]]) {

    NSLog(@"good image");
}
else{

    NSLog(@"bad image");
}

[cell.imageView setImage:tempImage];
```

where _filter = [[GPUImageAddBlendFilter alloc] init]

please help me here

**Comment by Nidhisood** [comment]
@pawankmrai Hi. Can you please tell me how did you solve this issue? Because I'm getting the same error while applying filters to videos using GPUImage library in xamarin.ios. 
Thanks in advance.

**Comment by pawankmrai** [comment]
@nidhisood it's been quite long time, I worked on this issue and I don't have the source code of that project as well.
but what I remember is "issue was with source1 & source 2 objects that were created inside the cell as these objects take time in initialization ". 
The fix was to do it on the background thread, put the code from source 1 to apply filter inside a dispatch block and return tempImag on the main thread.
Let me know if this fixes your problem.

**Comment by Nidhisood** [comment]
Thanks @pawankmrai  for your response. Actually I'm doing something different just to test. I've put my code inside a background thread and it stopped crashing, but the problem is it also stopped playing my video now. I can only hear the audio playing and there is no video displaying. I'm sharing my code as well:


`                                               if (mainPlayer == null)
							mainPlayer = new AVPlayer ();
						if (e.MediaUrl != null)
							playerItem = AVPlayerItem.FromUrl (e.MediaUrl);
						else if (e.ReferenceUrl != null)
							playerItem = AVPlayerItem.FromUrl (e.ReferenceUrl);
						else if (e.Info [UIImagePickerController.MediaURL].ToString () != null)
							playerItem = AVPlayerItem.FromUrl (new NSUrl (e.Info [UIImagePickerController.MediaURL].ToString ()));
						mainPlayer.ReplaceCurrentItemWithPlayerItem (playerItem);

						var shared = AVAudioSession.SharedInstance ();
						shared.SetCategory (AVAudioSessionCategory.Playback);
						AudioSession.OverrideCategoryMixWithOthers = true;
						AudioSession.SetActive (true);

						filter = new GPUImagePixellateFilter ();
						//filter.ForceProcessingAtSize (new CGSize (192.0f, 144.0f));
						//filter.VignetteCenter = gpuImageView.Center;
						//filter.VignetteStart = gpuImageView.Frame.Left;
						//filter.VignetteEnd = gpuImageView.Frame.Right;


						var documents = Environment.GetFolderPath (Environment.SpecialFolder.MyDocuments);
						var pathToMovie = Path.Combine (Path.GetTempPath (), "Movie.m4v");

						if (File.Exists (pathToMovie)) {
							File.Delete (pathToMovie);
							File.Delete (pathToMovie);
						}

						var movieURL = new NSUrl (pathToMovie, false);
						if (File.Exists (movieURL.Path)) {
							File.Delete (movieURL.Path);
						}

						var asset = AVAsset.FromUrl (movieURL);

						AVAssetExportSession av = new AVAssetExportSession (asset, AVAssetExportSession.PresetMediumQuality);
						av.OutputUrl = NSUrl.FromFilename (pathToMovie);

						movieWriter = new GPUImageMovieWriter (av.OutputUrl, new CGSize (640.0f, 480.0f));
						movieFile = new GPUImageMovie (playerItem.Asset);

						movieFile.RunBenchmark = true;
						movieFile.PlayAtActualSpeed = false;
						movieFile.PlayerItem = playerItem;

						var thread = new Thread (new ThreadStart (() => {
							FilterVideo ();
						}));
						thread.Start ();

						InvokeOnMainThread (() => {

							movieFile.AddTarget (filter);
							filter.AddTarget (gpuImageView);
						});
					
		}

		public async void FilterVideo ()
		{
			if (movieWriter.AssetWriter.Status != AVAssetWriterStatus.Writing) {
				filter.AddTarget (movieWriter);
				movieWriter.Enabled = true;
				movieWriter.ShouldPassthroughAudio = true;
				movieFile.AudioEncodingTarget = movieWriter;
				movieFile.EnableSynchronizedEncoding (movieWriter);

			} else {
				movieWriter.AssetWriter.DirectoryForTemporaryFiles = null;
				await movieWriter.AssetWriter.FinishWritingAsync ();
			}

			movieWriter.StartRecording ();

			InvokeOnMainThread (() => {

				movieFile.StartProcessing ();
				mainPlayer.Play ();
			});

			var timer = NSTimer.CreateRepeatingScheduledTimer (0.3, _ => {
				if (movieFile != null)
					InvokeOnMainThread (() => label.Text = movieFile.Progress.ToString ("P0"));
			});

			movieWriter.CompletionHandler = async () => {
				filter.RemoveTarget (movieWriter);
				await movieWriter.FinishRecordingAsync ();
				await movieWriter.AssetWriter.FinishWritingAsync ();
				movieWriter.CompletionHandler = null;
				//	movieURL = null;

				InvokeOnMainThread (() => {
					timer.Invalidate ();
					label.Text = 1.ToString ("P0");
				});
			};
		}
`

I think the problem is with this line of code:

`movieWriter.StartRecording ();`

If I put this line inside the thread, then it doesn't crash but also it stops displaying my video and if I put it outside the thread block then it starts crashing but displays my video. Can you see my code and help with this?

**Comment by pawankmrai** [comment]
@nidhisood
I do not see any issue with the code. I think you should do more debugging with the breakpoint to find the problem.
I don't think, I would be able to help you without the whole code & debug it myself.
