### ISSUE TITLE
[UIView nextAvailableTextureIndex]

### ISSUE THREAD

**Issue by OlyRice** [BradLarson/GPUImage#92]
HI

I am trying to setup the project using the simple examples. The build is fine but I seem to get the following error.

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView nextAvailableTextureIndex]: unrecognized selector sent to instance 0x1ed75700'

This is my code.
- (void)viewDidLoad
  {
  [super viewDidLoad];
  
  stillCamera = [[GPUImageStillCamera alloc] init];
  filter = [[GPUImageGammaFilter alloc] init];
  GPUImageRotationFilter *rotationFilter = [[GPUImageRotationFilter alloc] initWithRotation:kGPUImageRotateRight];
  
  [stillCamera addTarget:rotationFilter];
  [rotationFilter addTarget:filter];
  GPUImageView *filterView = (GPUImageView *)self.view; -- Error Seems To Call Here
  [filter addTarget:filterView];
  
  [stillCamera startCameraCapture];

}

**Comment by migee** [comment]
Same issue here, though I am following a different guide elsewhere. I had GPUImageView set in storyboard which still caused issues. After printing out the class that the storyboard was returning I noticed that it regressed to UIView. ObjC as a linker flag cleared that up however and it was able to progress. However immediately after it left my code it came back up with this. Im at a loss. I'm down to the point where my code is exactly the same as the other project except for the GPUImage version and possibly some other compiler settings.

**Comment by migee** [comment]
-ObjC fixed it for me, thanks!

**Comment by erickingxu** [comment]
Hi,All
I STILL had a confused problem about how to using GPUImageView rightly...
When the display view for GPUImageView is my rewritten UIView, it is not a nib file in interface builder one , How to connect my display UIView with GPUImageView?
Any one meet it ?
@BradLarson , Can you give me some advice for this?
