### ISSUE TITLE
GPUImage Sketch filter

### ISSUE THREAD

**Issue by HrishiPol** [BradLarson/GPUImage#993]
Hi,
I am started looking into GPUImage sdk for ios. I have tried sketch filter but it not getting perfect sketch. You can check the link http://picpaste.com/Screen_Shot_2013-05-23_at_5.45.37_PM-jukcIHSh.png How we can achieve the perfect sketch?

**Comment by maniyarpayal** [comment]
@HrishiPol  Have achieved sketch image same as the "http://stackoverflow.com/questions/12317858/create-sketch-effect-to-photos-using-brad-larson-gpuimage-in-obj-c. "
is your problem solved? Can you help me for that?
